// Five guides prepared for publication on 28 September 2026.
const makeDraft = ({ body, faq, ...post }) => ({
  ...post,
  published: "2026-09-28",
  modified: "2026-09-28",
  imageCaption: "Illustrative editorial image. All amounts in this guide are modeling assumptions.",
  features: ["Visible assumptions and checked arithmetic", "A practical capacity or risk check", "A clear method to use your own records"],
  faq,
  html: `${body.trim()}\n<h2>FAQs</h2>\n${faq.map(({ q, a }) => `<h3>${q}</h3><p>${a}</p>`).join("\n")}\n<p>Explore the <a href="/blogs/">MyBreakeven guide library</a> for related business planning guides.</p>`,
});

export const september28Drafts = [
  makeDraft({
    slug: "commercial-cleaning-contract-bid",
    tag: "Cleaning",
    name: "Cleaning Business",
    cluster: "commercial contract bidding",
    title: "How to Bid a Commercial Cleaning Contract Without Guessing",
    seoTitle: "How to Bid a Commercial Cleaning Contract",
    description: "Build an office cleaning bid from a site walk, task frequency, paid crew hours, account costs, and target margin. Includes a worked monthly proposal.",
    metaDescription: "Bid a commercial cleaning contract from scope, paid labor hours, supplies and margin. Follow a worked office example and test the monthly price.",
    image: "/images/blog/commercial-cleaning-contract-bid-editorial.webp",
    alt: "Commercial cleaner reviews an office service checklist and timing before preparing a bid",
    calculatorSlug: "cleaning-business-break-even-calculator",
    opening: "A commercial cleaning bid starts with the work the building actually needs, not its square footage alone. Walk the site, count visits and tasks, estimate paid crew hours, add direct account costs and overhead, then set a margin the contract can support. Check that the proposed monthly price still works when the schedule changes or a cleaner is absent.",
    unit: "visits",
    singular: "visit",
    tags: ["Cleaning", "Commercial Cleaning", "Contract Bidding"],
    body: `
<p>A commercial cleaning bid starts with the work the building actually needs, not its square footage alone. Walk the site, count visits and tasks, estimate paid crew hours, add direct account costs and overhead, then set a margin the contract can support. Check that the proposed monthly price still works when the schedule changes or a cleaner is absent.</p>
<blockquote><strong>Quick answer:</strong> Scope the building, calculate paid cleaner-hours per visit, multiply by monthly visits, add supplies, travel and account overhead, then divide total cost by one minus your target margin. In the example below, a 20-visit office contract costs $4,860 a month to deliver and support. A 20% margin calls for a $6,075 monthly bid, assuming the stated scope and costs.</blockquote>
<h2>Build the bid from tasks and paid labor hours</h2>
<p>Before you quote, ask for access to every area in the proposed scope. Note cleanable floor area, number of restrooms, waste stations, kitchens, touchpoints, security procedures, floor materials, permitted work hours and who provides consumables. A hallway with carpet does not take the same time as a restroom or a break room. Confirm whether windows, floors, periodic deep cleans and replenishment are included or priced separately.</p>
<p>Write a task schedule: vacuum and trash each visit, restroom cleaning each visit, kitchen wipe-down each visit, and a defined frequency for dusting and other periodic jobs. Time a comparable job using your own records, or estimate by room and revise after a trial. Count setup, loading, transit between accounts, key handling and paid closeout. “Two cleaners for two hours” means <strong>four cleaner-hours</strong> for that visit; do not mistake two hours on the wall clock for two hours of payroll.</p>
<p>For a fictional small office, assume four cleaner-hours per visit and 20 visits in a planning month. At a fully loaded labor cost of $32 per paid cleaner-hour, labor is 4 × 20 × $32 = <strong>$2,560</strong>. This rate is an assumption, not a national wage benchmark. Add $18 of supplies per visit ($360), $22 of account-specific travel and parking per visit ($440), and $500 for monthly account supervision and allocated operating overhead. Add $1,000 for minimum owner management pay and a service contingency that is genuinely expected to be spent. Total monthly cost is $2,560 + $360 + $440 + $500 + $1,000 = <strong>$4,860</strong>.</p>
<p>If you want a 20% margin on the selling price, divide $4,860 by 0.80: the bid is <strong>$6,075 per month</strong>, or $303.75 per planned visit. At that price, revenue minus budgeted costs is $1,215; $1,215 ÷ $6,075 is exactly 20%. Adding 20% to cost would produce $5,832, which is a 16.67% margin. The <a href="https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point">SBA break-even explanation</a> is a useful reference when separating fixed expenses from costs that move with visits.</p>
<h2>What changes the number you should quote?</h2>
<p><strong>Scope and usage:</strong> an office of the same size with a busy kitchen and more restrooms can take longer than one with mostly desks. Walkthrough notes beat a blanket price per square foot. <strong>Frequency:</strong> two visits a week do not equal five; periodic tasks must be assigned to specific visits. <strong>Hours and access:</strong> after-hours entry, alarm procedures and a required second cleaner change the paid hours and schedule. <strong>Account geography:</strong> a short visit far from your existing route can consume a surprising share of a shift. <strong>Payment terms:</strong> a monthly invoice paid later creates a cash need for wages and supplies even when the accounting margin is healthy.</p>
<p>Document those assumptions in the quote. Define the service location, included rooms, weekly frequency, monthly price, periodic task schedule, consumable responsibility, exclusions, approval process for extra work and billing cycle. Have an actual contract and insurance requirements reviewed for your location; the arithmetic here is a pricing model, not contract or legal advice.</p>
<h2>Three bid scenarios with the same service method</h2>
<p>These invented scenarios show why a profitable-looking per-visit rate may not scale across buildings. Treat each cost line as a modeling input and replace it with your time sheets, supply receipts and account-specific travel.</p>
<div class="article-table-scroll"><table><thead><tr><th>Monthly scenario</th><th>Paid labor</th><th>Other cost, including allocated overhead</th><th>Total cost</th><th>Price for 20% margin</th></tr></thead><tbody><tr><td>Small office: 8 visits × 3 hours × $30</td><td>$720</td><td>$680</td><td>$1,400</td><td>$1,750</td></tr><tr><td>Standard office: 20 visits × 4 hours × $32</td><td>$2,560</td><td>$2,300</td><td>$4,860</td><td>$6,075</td></tr><tr><td>Large site: 20 visits × 10 hours × $34</td><td>$6,800</td><td>$3,200</td><td>$10,000</td><td>$12,500</td></tr></tbody></table></div>
<p>The small office requires $1,750 ÷ 8 = $218.75 per visit. If it is outside your route, the assumed $680 nonlabor cost may be too low. The large site needs 200 cleaner-hours per month. Two cleaners available for 25 hours a week each supply roughly 200 cleaner-hours in a four-week schedule before leave, travel and other clients: the plan is already full. A larger building may require a dedicated shift or backup crew.</p>
<p>Now stress-test the standard office. If each visit needs five cleaner-hours instead of four, labor increases by 20 × $32 = $640. Total cost becomes $5,500; at the quoted $6,075, the margin falls to $575 ÷ $6,075 = <strong>9.47%</strong>. A site walk and measured first week are worth more than a copied rate sheet. If your agreement permits it, specify how changed scope will be priced before accepting extra work.</p>
<h2>How to run your own numbers</h2>
<p>Enter average revenue per completed visit, the labor and supplies that rise with each visit, monthly fixed costs, owner pay, expected booked-to-completed visits and realistic team hours in the <a href="https://mybreakeven.com/calculators/cleaning-business-break-even-calculator/">cleaning business break-even calculator</a>. For a commercial contract, also keep a separate account-level schedule so its specific travel, supplies and invoice timing do not disappear into a company-wide average. The calculator supports other currencies if USD is not yours.</p>
<p>For background on which costs belong in monthly overhead, use the <a href="/blogs/cleaning-business-monthly-expenses/">cleaning business monthly expenses guide</a>. If you also quote homes, keep that distinct from this office-contract method and consult the <a href="/blogs/how-much-to-charge-for-house-cleaning/">house-cleaning pricing guide</a>. A contract bid answers a different question from your overall <a href="/blogs/cleaning-business-break-even/">cleaning business break-even target</a>.</p>
<h2>Common mistakes in commercial cleaning bids</h2>
<ul><li><strong>Pricing only by square feet:</strong> it ignores restroom counts, kitchen use, floors and service frequency.</li><li><strong>Using on-site time as paid time:</strong> setup, closing, transit and supervisory time still consume payroll or owner hours.</li><li><strong>Leaving out periodic work:</strong> a monthly floor task becomes an unpriced obligation if it is promised but not budgeted.</li><li><strong>Confusing markup with margin:</strong> a 20% markup on $4,860 is not a 20% margin.</li><li><strong>Assuming every invoice arrives immediately:</strong> delayed collections can leave an otherwise profitable account short of payroll cash.</li><li><strong>Quoting unspecified extras:</strong> define consumables, windows and event cleanups before they become disputes about scope.</li></ul>
<h2>Takeaways</h2><ul><li>Inspect the building and describe the work before calculating price.</li><li>Quote using cleaner-hours, direct account costs, allocated overhead and a clearly defined margin.</li><li>Test the bid against your actual crew capacity and a slower first week.</li><li>Give the client a written scope and a process for changes.</li></ul>`,
    faq: [
      { q: "How do I price an office cleaning contract per month?", a: "Estimate paid hours for each visit, multiply by visits in the billing period and add account-specific supplies, travel, supervision and overhead. Divide by one minus your target margin. State the assumed number of visits, because months have different numbers of weekdays." },
      { q: "Is price per square foot enough for a commercial cleaning bid?", a: "Use square footage as one scoping input, not the entire bid. Restrooms, kitchens, floor materials, traffic, access rules and cleaning frequency determine the actual workload." },
      { q: "Should I include travel time in the quote?", a: "Yes, if travel and loading consume paid hours or restrict how many accounts a crew can serve. Allocate the specific trip to the account or distribute shared route cost consistently." },
      { q: "How should I bid periodic deep cleaning?", a: "Name each periodic task and frequency, estimate its separate hours and materials, and either include its monthly allowance in the contract or quote it as approved extra work. Avoid calling it included while assigning no labor to it." },
      { q: "What is the difference between a 20% markup and 20% margin?", a: "Markup divides profit by cost; margin divides profit by the client price. A $4,860 cost plus 20% markup is $5,832, while a 20% price margin requires $6,075." },
      { q: "Can a profitable cleaning contract still create a cash shortage?", a: "Yes. Wages and supplies may be due before the customer's invoice is collected. Forecast collection dates and payroll dates separately from operating margin." },
    ],
  }),
  makeDraft({
    slug: "salon-booth-rent-vs-commission-owner",
    tag: "Salon",
    name: "Salon",
    cluster: "salon owner business model",
    title: "Salon Booth Rent vs Commission: The Owner's Break-Even Math",
    seoTitle: "Salon Booth Rent vs Commission: Owner Math",
    description: "Compare booth rent and commission from the salon owner's side using occupied chairs, service sales, labor costs and shared overhead.",
    metaDescription: "Compare salon booth rent and commission from the owner's view. Work out occupied-chair income, service costs and the break-even crossover point.",
    image: "/images/blog/salon-booth-rent-vs-commission-owner-editorial.webp",
    alt: "Empty salon chairs beside an owner's notebook and calculator for comparing rental and commission models",
    calculatorSlug: "salon-break-even-calculator",
    opening: "For a salon owner, booth rent and commission earn money in different ways. Rent gives a contracted payment for an occupied chair; commission gives the salon a share of service sales while the salon usually carries more operating costs. Compare the net contribution of each occupied chair and then test the whole room against its fixed bills.",
    unit: "services",
    singular: "service",
    tags: ["Salon", "Booth Rent", "Commission"],
    body: `
<p>For a salon owner, booth rent and commission earn money in different ways. Rent gives a contracted payment for an occupied chair; commission gives the salon a share of service sales while the salon usually carries more operating costs. Compare the net contribution of each occupied chair and then test the whole room against its fixed bills.</p>
<blockquote><strong>Quick answer:</strong> Calculate monthly net contribution per occupied chair for both models. If rent is $1,200 and chair-specific costs are $100, the rental chair contributes $1,100. If the salon retains 45% of $4,000 in service sales and pays $500 of salon-funded service costs, the commission chair contributes $1,300. The commission option is ahead by $200 in this illustration, before shared overhead.</blockquote>
<h2>Compare the money that stays with the salon owner</h2>
<p>Under a rental model, the salon invoices a renter for the agreed use of a station and any separately agreed services. Under a commission model, the salon receives client payments and pays a stylist under the actual arrangement. From the <em>owner's</em> side, the useful comparison is monthly contribution after costs specifically caused by that chair. Do not compare rent with the stylist's total client sales: the rental client's payment may belong to the renter.</p>
<p>Here is a fictional one-chair example using one consistent month. The rental chair collects $1,200 in rent and consumes $100 of extra utilities and administration, leaving <strong>$1,100</strong> to cover shared salon overhead. The commission chair performs $4,000 of services. Assume the salon retains 45%, or $1,800, after the stylist's agreed 55% share. Salon-funded color, laundry, processing, employer costs where applicable and incremental front-desk support cost another $500. Contribution is <strong>$1,300</strong>. On those inputs commission contributes $200 more, but that difference can disappear when services slow.</p>
<p>The commission chair reaches the rental contribution when its share of service sales minus the $500 chair-specific costs equals $1,100: 0.45 × sales − $500 = $1,100. Divide $1,600 by 0.45 for a crossover of <strong>$3,555.56 monthly service sales</strong>. At $3,000 of services, commission contribution is $850 and rent is ahead by $250. At $5,000, commission contribution is $1,750 and commission is ahead by $650. If the $500 includes costs that change with sales, replace the simple equation with a variable-cost rate before trusting the crossover.</p>
<p>Worker status, payroll obligations, control of schedules and state licensing do not follow from the label “booth rent.” The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/independent-contractor-defined">IRS explanation of independent contractors</a> emphasizes the actual relationship. Ask qualified local advisers to review the arrangement before acting on this financial comparison; the figures here do not classify any worker or recommend a legal structure.</p>
<h2>What changes the result?</h2>
<p><strong>Occupancy:</strong> four stations with three renters produce only three rent checks while the lease covers all four. <strong>Service demand:</strong> commission income rises with completed client services but often falls with quiet weeks and cancellations. <strong>What the salon supplies:</strong> products, booking, reception, towels, utilities and marketing may differ under the two written arrangements. <strong>Collection risk:</strong> an invoiced rental fee is not cash until received. <strong>Owner workload:</strong> recruiting, coaching and scheduling require time; include that work in the relevant model.</p>
<p>Put fixed salon rent, base utilities, insurance, software and owner management pay in a shared monthly budget. Keep the incremental station expenses in the per-chair comparison. If a receptionist is required only under the commission model, either charge the extra shift to commission chairs or run a separate whole-salon scenario. Apply the same cost boundary to both models.</p>
<h2>Three operating scenarios for four chairs</h2>
<p>Assume the salon has four usable chairs and $4,000 monthly shared overhead including a defined owner management-pay target. Figures below are fictional operating cases, not common salon benchmarks.</p>
<div class="article-table-scroll"><table><thead><tr><th>Illustrative use of four chairs</th><th>Monthly chair contribution</th><th>Less shared overhead</th><th>Operating result</th></tr></thead><tbody><tr><td>Four occupied rental chairs at $1,100 each</td><td>$4,400</td><td>$4,000</td><td>+$400</td></tr><tr><td>Three occupied rental chairs at $1,100 each</td><td>$3,300</td><td>$4,000</td><td>−$700</td></tr><tr><td>Four commission chairs at $1,300 each</td><td>$5,200</td><td>$4,000</td><td>+$1,200</td></tr></tbody></table></div>
<p>At the assumed $1,100 contribution, $4,000 ÷ $1,100 = 3.64; you need <strong>four occupied rental chairs</strong> to cover the full monthly shared cost. At the assumed $1,300 contribution, $4,000 ÷ $1,300 = 3.08; you also need four equally productive commission chairs. Three commission chairs generate $3,900 and leave a $100 gap. The model's attractive per-chair contribution means little if you cannot fill the stations or sell enough services.</p>
<figure><img src="/images/blog/salon-booth-rent-vs-commission-crossover.svg" alt="At 3000 dollars of monthly service sales the rental chair earns more for the owner; commission crosses rent at about 3556 dollars and earns more at 5000 dollars" width="960" height="480" loading="lazy"><figcaption>Illustrative crossover based on 45% salon share, $500 commission-chair costs, and $1,100 net rental contribution.</figcaption></figure>
<p>A mixed salon can be modeled chair by chair: two rental chairs contribute $2,200 and two commission chairs at $1,300 each contribute $2,600. Total contribution is $4,800; after $4,000 shared overhead, the example leaves $800. Do not double-count the same chair as rental and commission income unless your actual contract supports both charges.</p>
<h2>How to run your own numbers</h2>
<p>For the commission case, enter collected service sales, the salon's actual stylist pay and other per-service costs, monthly overhead, owner pay and realistic booked capacity into the <a href="https://mybreakeven.com/calculators/salon-break-even-calculator/">salon break-even calculator</a>. For rental, first calculate monthly net rental contribution separately, then compare that total with the salon's fixed bills: the service-sales model should not be mistaken for a booth-rent calculator. The tool supports other currencies if USD is not yours.</p>
<p>For the service-side cost inputs, see <a href="/blogs/salon-service-pricing/">how salon services are priced</a>. For the shared bills, use the <a href="/blogs/salon-break-even/">salon break-even guide</a>; the <a href="/blogs/salon-clients-per-day-break-even/">clients-per-day guide</a> deals with service demand rather than chair-rental income.</p>
<h2>Common mistakes when comparing the models</h2>
<ul><li><strong>Counting renters' service sales as salon revenue:</strong> rent received and commission-service receipts have different owners and cost bases.</li><li><strong>Using a full-chair assumption:</strong> empty stations still cost rent and utilities.</li><li><strong>Assuming a flat cost for growing services:</strong> color and card fees may rise with commission sales; use a rate when appropriate.</li><li><strong>Leaving receptionist or manager time out:</strong> extra scheduling work changes the effective contribution.</li><li><strong>Conflating labels with worker classification:</strong> the written contract and actual work relationship require professional local review.</li><li><strong>Quoting the crossover as a universal number:</strong> it depends entirely on your rent, split, service mix and costs.</li></ul>
<h2>Takeaways</h2><ul><li>Compare the owner's net contribution per occupied chair on both models.</li><li>Check the crossover at slow, base and busy service-sales levels.</li><li>Cover the full salon's fixed bills with realistically occupied stations.</li><li>Have the actual employment and rental arrangement reviewed locally.</li></ul>`,
    faq: [
      { q: "Is booth rent or commission more profitable for a salon owner?", a: "Neither wins for every salon. On the example's assumptions, commission contributes more when that chair sells more than about $3,555.56 per month; below that, the rental chair contributes more. Check occupancy and the full salon's fixed expenses too." },
      { q: "How do I find the salon owner's crossover point?", a: "Set net rent per occupied chair equal to the salon's retained service sales less incremental chair costs. If incremental costs rise with sales, subtract their percentage before dividing by the remaining share." },
      { q: "Do booth renters' client payments count as salon revenue?", a: "Do not assume so. For an independent rental arrangement, start with the amounts the salon actually receives under the agreement and ask your accountant how to record them. The salon's own retail sales, if any, are separate." },
      { q: "What happens if a salon chair is empty?", a: "That chair brings in no rent or commission contribution while part of the salon's lease and insurance remains. Use an occupied-chair forecast and calculate the minimum occupied stations needed to pay fixed bills." },
      { q: "Can a salon offer a mix of rentals and commission chairs?", a: "Financially you can model each occupied chair separately and sum its net contribution. Whether a proposed mixed operation complies with local licensing, employment and contract rules requires qualified local review." },
      { q: "Does the salon calculator directly model booth rent?", a: "Its main model is service sales and operating break-even. Work out rent contribution separately and compare it with shared fixed costs; use the calculator to stress-test commission service volume and capacity." },
    ],
  }),
  makeDraft({
    slug: "mobile-detailing-maintenance-plan-pricing",
    tag: "Mobile Detailing",
    name: "Mobile Detailing",
    cluster: "recurring maintenance plans",
    title: "Mobile Detailing Maintenance Plan Pricing: Keep the Monthly Margin",
    seoTitle: "Mobile Detailing Maintenance Plan Pricing",
    description: "Price weekly and monthly detailing maintenance visits from labor, travel, plan frequency and real capacity instead of discounting a one-time detail.",
    metaDescription: "Price mobile detailing maintenance plans using visit frequency, labor, supplies and travel. See monthly examples and protect your recurring margin.",
    image: "/images/blog/mobile-detailing-maintenance-plan-pricing-editorial.webp",
    alt: "Mobile detailer cleans a vehicle beside a stocked service van with a visit calendar nearby",
    calculatorSlug: "mobile-detailing-break-even-calculator",
    opening: "A mobile detailing maintenance plan is a promise to revisit a vehicle on a defined schedule and perform a defined scope. Price the time and trip for every included visit, then check whether recurring plans fit your calendar. A low monthly fee can lock up your best service hours while leaving too little money after travel and supplies.",
    unit: "visits",
    singular: "visit",
    tags: ["Mobile Detailing", "Maintenance Plan", "Recurring Pricing"],
    body: `
<p>A mobile detailing maintenance plan is a promise to revisit a vehicle on a defined schedule and perform a defined scope. Price the time and trip for every included visit, then check whether recurring plans fit your calendar. A low monthly fee can lock up your best service hours while leaving too little money after travel and supplies.</p>
<blockquote><strong>Quick answer:</strong> Price the promised monthly visits, not the word “subscription.” Add technician time, consumables, travel and card costs for each visit, then divide that total by one minus your target contribution margin. Two $70-cost visits require at least $200 monthly to leave 30% contribution before fixed overhead. Define which vehicles and conditions qualify for maintenance.</blockquote>
<h2>Start with the service promise and the visit count</h2>
<p>Define an initial reset or full detail separately from the maintenance work. A vehicle that has not been cleaned for months may take longer than a vehicle on a four-week routine. Spell out whether the plan covers exterior wash, interior vacuum, glass, touch surfaces, stain treatment, pet hair, oversized vehicles and weather-related rescheduling. A monthly plan means one visit per month unless your agreement says something else. “Every two weeks” produces roughly 26 visits per year, which is more than two visits every calendar month.</p>
<p>For one invented two-visit month, assume each maintenance visit sells 90 minutes of technician work at a budgeted $30 per hour, including paid setup and wrap-up. Labor is $45. Chemicals, water, cloth wear and consumables add $8; account-specific travel adds $12; transaction fees and appointment reminders add $5. Variable cost per visit is $45 + $8 + $12 + $5 = <strong>$70</strong>. Two visits therefore cost <strong>$140 per month</strong> before van insurance, software and other shared monthly overhead.</p>
<p>If the plan must leave 30% contribution after those variable costs, monthly price is $140 ÷ 0.70 = <strong>$200</strong>. Contribution is $60 monthly, or $30 per visit. This is a planning example, not a typical market price. If you charge $170, contribution shrinks to $30 monthly; a single unpriced $20 stain treatment would consume two-thirds of that. The <a href="https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point">SBA break-even formula</a> uses the contribution remaining after variable costs to cover fixed costs.</p>
<p>Explain frequency using calendar dates rather than assuming every month has four weeks. If a plan promises a visit every two weeks, its annual visit count is about 26, so at $70 each annual variable cost is $1,820. A $200 monthly fee collects $2,400 annually and leaves $580 contribution, or about $48.33 per month, before fixed costs. Pricing this same plan as if it had only 24 visits would overstate annual contribution by <strong>$140</strong>.</p>
<h2>What changes plan economics?</h2>
<p><strong>Condition at each visit:</strong> a maintenance clean stays short only if the vehicle is eligible and visits occur at the agreed interval. <strong>Route density:</strong> two nearby clients can reduce unpaid travel relative to opposite sides of town. <strong>Service frequency:</strong> weekly, every-two-week and monthly plans use different annual visit counts. <strong>Weather and missed visits:</strong> decide what happens when outdoor work is impossible or the customer is unavailable. <strong>Vehicle mix:</strong> larger interiors, heavy use and multiple cars can change paid time. Do not offer a single unlimited-service promise with a fixed labor assumption.</p>
<p>State plan boundaries and schedule rules clearly: initial condition, number of visits, time window, rescheduling policy, travel area and price of work beyond routine upkeep. These are commercial terms to confirm with your local advisers as needed. Keep any prepaid customer balance in your cash schedule: cash collected before the work is performed is not automatically earned operating profit.</p>
<h2>Three plans with different visit patterns</h2>
<p>The following fictional cases use a contribution target of 30% after visit-level cost. They do not assume identical vehicles or routes. Round a quote upward if you need a whole-dollar posted price.</p>
<div class="article-table-scroll"><table><thead><tr><th>Plan</th><th>Annual visits</th><th>Cost per visit</th><th>Annual variable cost</th><th>Monthly price at 30% contribution</th></tr></thead><tbody><tr><td>Monthly routine visit</td><td>12</td><td>$80</td><td>$960</td><td>$114.29</td></tr><tr><td>Twice per month</td><td>24</td><td>$70</td><td>$1,680</td><td>$200</td></tr><tr><td>Every two weeks</td><td>26</td><td>$70</td><td>$1,820</td><td>$216.67</td></tr></tbody></table></div>
<p>The monthly routine visit needs $960 ÷ 0.70 ÷ 12 = $114.2857, rounded up to $114.29. Two scheduled visits in every month need $1,680 ÷ 0.70 ÷ 12 = $200. An every-two-week plan needs $1,820 ÷ 0.70 ÷ 12 = $216.6667, rounded up to $216.67. Prices exclude sales tax where applicable and remain assumptions for illustration. The two extra annual visits in the last row compared with twice per month are real work, even if both offers are called “recurring.”</p>
<p>Then check slot capacity. Suppose ten every-two-week customers require 260 visits annually, an average of five weekly. At two hours reserved per visit including setup and local travel, you commit roughly ten calendar hours each week before one-time details, weather gaps and administration. If five peak-week slots are not reliably available, charging the correct margin per visit will not make the schedule feasible.</p>
<h2>How to run your own numbers</h2>
<p>Convert each plan into monthly average visits and an average price per visit. Put technician hours, per-visit products and account-specific travel into variable cost; add van, insurance, software and a defined owner-pay target to fixed monthly costs. Run the <a href="https://mybreakeven.com/calculators/mobile-detailing-break-even-calculator/">mobile detailing break-even calculator</a> to test required paid jobs and available hours, then check the separate annual visit schedule above. It accepts other currencies if USD is not yours.</p>
<p>For a one-off service menu, see the <a href="/blogs/car-detailing-prices-list/">car-detailing service pricing guide</a>. For a week-by-week capacity baseline, use the <a href="/blogs/how-many-detailing-jobs-week/">detailing jobs per week guide</a>. The <a href="/blogs/mobile-detailing-break-even/">mobile detailing break-even guide</a> deals with the whole business; this article is specifically about a recurring service promise.</p>
<h2>Common maintenance-plan pricing mistakes</h2>
<ul><li><strong>Calling a deep clean maintenance:</strong> an initial reset and unusually dirty visits need their own scope and time.</li><li><strong>Confusing twice monthly with every two weeks:</strong> the latter usually entails about two extra visits a year.</li><li><strong>Discounting price without repricing travel:</strong> repeat visits still use a vehicle and a time slot.</li><li><strong>Counting prepaid money as completed work:</strong> schedule the service obligation against the cash already collected.</li><li><strong>Ignoring weather or rescheduling:</strong> moved visits can pile up and displace new jobs.</li><li><strong>Skipping the capacity check:</strong> recurring revenue is only useful if the promised visit slots can be delivered.</li></ul>
<h2>Takeaways</h2><ul><li>Describe exactly what each recurring visit includes.</li><li>Calculate annual visits before converting a frequency into a monthly fee.</li><li>Price labor and travel at the real cost of each appointment.</li><li>Protect enough calendar space for both members and other work.</li></ul>`,
    faq: [
      { q: "How do I price a monthly mobile detailing maintenance plan?", a: "Define its visits and tasks, estimate labor, supplies, travel and payment cost per visit, and divide the monthly visit cost by one minus your intended contribution margin. Check afterward that the resulting contribution covers a realistic share of fixed overhead." },
      { q: "Is biweekly the same as twice monthly?", a: "No. Every two weeks is about 26 visits in a 52-week year; two visits in each of 12 months is 24 visits. State the actual schedule before writing the price." },
      { q: "Should the first deep clean be included?", a: "You can bundle it only after budgeting its extra time and products. Many operators prefer an initial reset quoted separately so routine visits can be priced on a genuinely maintained vehicle." },
      { q: "What if a client misses a planned visit?", a: "Define the rescheduling and expiration rules in the plan. Model the visit you remain obligated to deliver rather than treating an unperformed prepaid appointment as automatic profit." },
      { q: "How many recurring detail clients can one operator serve?", a: "Divide realistic weekly service hours by reserved hours per member visit, then leave space for one-off jobs, travel, weather and administration. Ten every-two-week clients can require around five visits weekly on average." },
      { q: "Does the calculator have a subscription setting?", a: "Use average monthly visit count and per-visit economics to assess recurring work against the business's break-even and capacity. Keep the exact annual visit obligation in a separate schedule." },
    ],
  }),
  makeDraft({
    slug: "ecommerce-chargeback-cost-per-order",
    tag: "Ecommerce",
    name: "Ecommerce",
    cluster: "payment dispute economics",
    title: "Ecommerce Chargeback Cost per Order: What a Dispute Does to Margin",
    seoTitle: "Ecommerce Chargeback Cost per Order",
    description: "Translate lost payment disputes, unrecovered merchandise and processor fees into a defensible cost per order and a revised break-even target.",
    metaDescription: "Calculate ecommerce chargeback cost per order from lost sales, dispute fees and unrecovered goods. See the full effect on margin and break-even.",
    image: "/images/blog/ecommerce-chargeback-cost-per-order-editorial.webp",
    alt: "Online store owner reviews a payment dispute beside a shipped package and inventory shelves",
    calculatorSlug: "ecommerce-break-even-calculator",
    opening: "A chargeback reverses a payment after a customer disputes a card transaction. A merchant can also lose dispute fees, fulfillment spending and sometimes the item itself. To price the risk, calculate the loss on each resolved dispute and spread the expected loss across all orders from the same period. Keep returns and disputes in separate records so the same order is not counted twice.",
    unit: "orders",
    singular: "order",
    tags: ["Ecommerce", "Chargebacks", "Order Economics"],
    body: `
<p>A chargeback reverses a payment after a customer disputes a card transaction. A merchant can also lose dispute fees, fulfillment spending and sometimes the item itself. To price the risk, calculate the loss on each resolved dispute and spread the expected loss across all orders from the same period. Keep returns and disputes in separate records so the same order is not counted twice.</p>
<blockquote><strong>Quick answer:</strong> Chargeback allowance per order equals total incremental loss from expected disputes divided by total orders. If a lost dispute on a $60 order reverses $60 of revenue and adds an assumed $15 fee, two such disputes among 1,000 orders reduce contribution by $150, or $0.15 per original order. Already-booked product and shipping costs should not be added again.</blockquote>
<h2>Separate a chargeback's extra loss from the original order cost</h2>
<p>Suppose a fictional online store sells 1,000 orders at $60 each. On an ordinary completed order, product cost is $22, shipping and fulfillment cost $5 and transaction fees $3. Variable cost is $30 and contribution is $30 per order. Across 1,000 orders, the baseline is $60,000 sales less $30,000 already budgeted variable costs, or <strong>$30,000 contribution</strong> before fixed overhead.</p>
<p>Now assume two of those 1,000 orders become lost disputes. The original $30 cost of each has already been subtracted in the $30,000 baseline. If each $60 payment is reversed and a fictional $15 dispute fee is charged, incremental loss relative to that baseline is $60 + $15 = <strong>$75 per lost dispute</strong>. Two cost $150, leaving <strong>$29,850 contribution</strong>, or $29.85 on average per original order. Adding another $22 product cost and $5 shipping at this step would double count spending already included in the baseline.</p>
<p>There are two equally useful views. The <em>all-in</em> economics of a lost order in the example are −$30 of original variable spending minus a further $15 dispute fee, or <strong>−$45 contribution</strong> after its $60 revenue is reversed. Compared with a normal order's +$30 contribution, that is a $75 swing. If merchandise or fees are recovered, calculate the actual amount instead of applying this worst-case example. <a href="https://docs.stripe.com/disputes/how-disputes-work">Stripe's dispute documentation</a> explains that disputed funds and dispute-related fees have their own process; your provider's account terms determine actual fees, timing and reimbursements.</p>
<p>Keep a log with original order ID, amount, original product and fulfillment cost, fee assessed, dispute date, outcome, funds restored, merchandise recovered and any separate recovery spending. A chargeback and an ordinary refund can start with the same customer complaint but follow different payment flows. Record one financial event per actual outcome, rather than stacking a hypothetical refund and a chargeback on the same order.</p>
<h2>What changes the cost per order?</h2>
<p><strong>Dispute outcome:</strong> funds may be returned when a dispute is won; fees may have different treatment depending on the provider. <strong>Product recovery:</strong> an item that never shipped differs from one already delivered and unrecoverable. <strong>Channel mix:</strong> sales channels can differ in buyer behavior and payment handling; calculate each cohort from its own records. <strong>Order value:</strong> losing a $200 payment is a different exposure from losing a $20 one. <strong>Timeliness:</strong> a fee charged now and funds restored later can create a cash squeeze even if the final loss is smaller.</p>
<p>Do not publish a universal “average chargeback fee” as if every processor and country uses the same schedule. Our $15 is explicitly an example input. Likewise, the illustrative two disputes per 1,000 orders is a scenario, not an observed industry rate or a warning threshold. Review your processor statements and documented dispute outcomes for a real loss allowance.</p>
<h2>Three monthly dispute scenarios</h2>
<p>Hold 1,000 orders, a $60 sale, $30 ordinary variable cost, a $15 illustrative dispute fee and $6,000 monthly fixed overhead constant. Assume each dispute is lost, the original $60 payment is reversed and no inventory is recovered. The “incremental dispute loss” column subtracts only revenue reversals and new fees from the baseline that has already counted product and fulfillment costs.</p>
<div class="article-table-scroll"><table><thead><tr><th>Lost disputes</th><th>Incremental dispute loss</th><th>Average allowance per order</th><th>Contribution after disputes</th><th>After $6,000 fixed overhead</th></tr></thead><tbody><tr><td>0 of 1,000</td><td>$0</td><td>$0</td><td>$30,000</td><td>$24,000</td></tr><tr><td>2 of 1,000</td><td>$150</td><td>$0.15</td><td>$29,850</td><td>$23,850</td></tr><tr><td>5 of 1,000</td><td>$375</td><td>$0.375</td><td>$29,625</td><td>$23,625</td></tr></tbody></table></div>
<p>For planning a similarly mixed future month, two lost disputes per 1,000 orders at $75 incremental loss imply $0.15 of expected dispute loss for each new order. Adjusted expected contribution becomes $30 − $0.15 = <strong>$29.85 per order</strong>. To cover $6,000 monthly fixed overhead, divide $6,000 by $29.85 and round up to <strong>202 orders</strong>; without the allowance, the simple threshold is 200. This expected-value shortcut is a planning assumption. A small shop can face a single large dispute rather than a smooth fractional fee on every sale.</p>
<p>Chargebacks can also consume owner time. If dispute evidence takes two paid hours, include that cost only when it is incremental to your original labor budget. Avoid adding the value of a product twice: one shipping cost, one product cost and one actual reversal belong in one reconciled record.</p>
<h2>How to run your own numbers</h2>
<p>Calculate expected loss per order from your settled disputes, then include it once in average variable cost when you use the <a href="https://mybreakeven.com/calculators/ecommerce-break-even-calculator/">ecommerce break-even calculator</a>. Enter actual average selling price, other per-order costs, fixed overhead and a feasible order and fulfillment capacity. Test a second scenario with a larger number of lost disputes if your sample is small. The calculator supports currencies other than USD.</p>
<p>The <a href="/blogs/ecommerce-return-cost-per-order/">ecommerce return-cost guide</a> deals with accepted returns and restocking. Use the <a href="/blogs/ecommerce-profit-margin/">ecommerce profit-margin guide</a> to reconcile all cost categories, and the <a href="/blogs/ecommerce-orders-per-day-profitable/">orders-per-day guide</a> to turn a revised monthly threshold into a realistic sales target.</p>
<h2>Common mistakes in dispute-cost estimates</h2>
<ul><li><strong>Double counting goods:</strong> the item cost was already included in the original ordinary-order contribution.</li><li><strong>Counting every opened dispute as lost:</strong> separate pending, won, lost and restored amounts.</li><li><strong>Using one fee for every processor:</strong> read the actual pricing and statement for the payment method in question.</li><li><strong>Combining refunds and disputes:</strong> reconcile an order ID before subtracting two revenue reversals.</li><li><strong>Ignoring cash timing:</strong> the amount may leave the account before the final decision.</li><li><strong>Assuming old rates predict a launch:</strong> a tiny sample can make one event dominate the percentage.</li></ul>
<h2>Takeaways</h2><ul><li>Keep one reconciled record for each disputed order.</li><li>Compute incremental loss against a baseline that already includes normal order costs.</li><li>Use actual outcomes to find an allowance per order.</li><li>Run the adjusted contribution through both break-even and cash planning.</li></ul>`,
    faq: [
      { q: "What costs should an ecommerce chargeback calculation include?", a: "Track the reversed payment, any dispute fees and truly incremental recovery or handling costs. Product, fulfillment and processing cost already counted in normal order economics should appear once, not again in the incremental loss line." },
      { q: "Is a chargeback the same as a customer return?", a: "No. A return normally follows a merchant's refund and merchandise process, while a chargeback begins as a cardholder dispute through payment channels. Reconcile the order so its final financial outcome is recorded correctly." },
      { q: "How do I calculate chargeback cost per order?", a: "Sum the incremental losses from settled disputes in a defined period and divide by all orders in that same period. In the example, two $75 incremental losses across 1,000 orders make a $0.15 allowance per order." },
      { q: "If I win a payment dispute, do I still pay a fee?", a: "Fee handling varies by payment provider, contract, dispute type and region. Check the provider statement for the funds and fees actually restored before calculating your final cost." },
      { q: "Can one chargeback make a small store unprofitable?", a: "It can materially change a thin month's contribution, especially on a high-value product. Compare the actual disputed amount and fee with the monthly contribution remaining after fixed costs." },
      { q: "Should I add a chargeback allowance to my product price?", a: "First calculate actual expected loss by product or channel and compare it with the contribution you need. If you change price, model possible effects on conversion and volume rather than assuming the full increase will be collected on unchanged demand." },
    ],
  }),
  makeDraft({
    slug: "landscaping-seasonal-break-even",
    tag: "Landscaping",
    name: "Landscaping",
    cluster: "seasonal cash planning",
    title: "Landscaping Seasonal Break-Even: Pay for the Slow Months",
    seoTitle: "Landscaping Seasonal Break-Even Guide",
    description: "Calculate the active-season jobs needed to cover a full year of landscaping overhead, then size the cash reserve for slow winter months.",
    metaDescription: "Find landscaping seasonal break-even across busy and slow months. Calculate required jobs, winter cash needs and a practical annual reserve.",
    image: "/images/blog/landscaping-seasonal-break-even-editorial.webp",
    alt: "Landscaping owner plans the coming months with a calendar beside lawn equipment and autumn trees",
    calculatorSlug: "landscaping-break-even-calculator",
    opening: "A landscaping company can cover its bills during the mowing season and still lose money across the year. If fixed costs continue through winter, the active months must earn enough contribution to pay for both active operations and the slow months. Calculate the annual target first, then check when the cash actually arrives and leaves the account.",
    unit: "jobs",
    singular: "job",
    tags: ["Landscaping", "Seasonality", "Break-Even"],
    body: `
<p>A landscaping company can cover its bills during the mowing season and still lose money across the year. If fixed costs continue through winter, the active months must earn enough contribution to pay for both active operations and the slow months. Calculate the annual target first, then check when the cash actually arrives and leaves the account.</p>
<blockquote><strong>Quick answer:</strong> Add fixed costs for all 12 months, subtract contribution you can reliably earn in the slow season, and divide the remainder by contribution per active-season job. If fixed bills are $5,000 monthly, there is no winter work and a $100 job costs $40 to deliver, eight active months need 1,000 paid jobs total: 125 jobs per active month. Cash timing needs a separate reserve.</blockquote>
<h2>Make the active months carry the full year</h2>
<p>For a fictional owner in a climate with eight strong service months and four slow months, assume fixed monthly costs of $5,000 year-round. That includes base vehicle and equipment payments, insurance, storage, software and a specified owner management-pay target. It excludes costs that occur only when crews perform a job. Twelve months of fixed cost are <strong>$60,000</strong>. Your own season may have a very different length, and not every landscaping business slows in winter.</p>
<p>Now assume an average completed job sells for $100 and costs $40 in direct labor, fuel, disposal and job-specific supplies. Contribution is <strong>$60 per job</strong>. With zero contribution from winter services, annual break-even jobs are $60,000 ÷ $60 = <strong>1,000 jobs</strong>. Spread across eight active months, that is 125 completed and collected jobs a month. A target of 100 jobs a month would create only 8 × 100 × $60 = $48,000 annual contribution and leave a <strong>$12,000 annual shortfall</strong>, even though each active month covers its own $5,000 fixed bill and shows $1,000 left over.</p>
<p>“Break even in June” is therefore different from “break even for the year.” Use your actual cost schedule. If a seasonal crew is laid off during the slow period, some payroll changes with activity; if you retain supervisors, their guaranteed pay remains due. Finance principal and tax remittances affect cash but should not be silently mixed into operating contribution. The <a href="https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point">SBA break-even method</a> separates fixed costs from variable costs when calculating required sales volume.</p>
<h2>What changes the seasonal target?</h2>
<p><strong>Regional climate:</strong> the number of workable weeks determines how many jobs must fit into a shorter period. <strong>Contract terms:</strong> monthly payments across 12 months may smooth cash even when work is concentrated in eight; check the actual service obligation. <strong>Winter services:</strong> snow, cleanup or other work may contribute, but do not rely on contracts you have not secured. <strong>Route density:</strong> travel between dispersed jobs eats crew hours and contribution. <strong>Fixed obligations:</strong> changing rent, insurance, retained payroll or vehicle finance changes the amount due when work stops.</p>
<p>Use contribution from each service type rather than counting every landscape job as the same. A mowing visit, leaf cleanup and installation can have different prices, labor, materials and weather exposure. If the mix shifts during the year, calculate contribution for each activity and add the totals. Capacity matters: 125 active-month jobs over 20 service days require an average of 6.25 jobs a day. If each job and its share of travel require 90 minutes, that is 9.375 crew-hours daily; one person cannot deliver that in an eight-hour workday.</p>
<h2>Three annual operating scenarios</h2>
<p>Keep eight active months, four slow months, $5,000 monthly fixed costs and $60 active-job contribution. Winter contribution, if any, is after winter service variable costs. Every figure is illustrative rather than a regional benchmark.</p>
<div class="article-table-scroll"><table><thead><tr><th>Scenario</th><th>Active jobs each month</th><th>Active contribution in year</th><th>Slow-month contribution</th><th>Less annual fixed costs</th><th>Annual result</th></tr></thead><tbody><tr><td>Busy-month comfort trap</td><td>100</td><td>$48,000</td><td>$0</td><td>$60,000</td><td>−$12,000</td></tr><tr><td>Year-round break-even</td><td>125</td><td>$60,000</td><td>$0</td><td>$60,000</td><td>$0</td></tr><tr><td>Same jobs plus contracted slow-season work</td><td>125</td><td>$60,000</td><td>$8,000</td><td>$60,000</td><td>+$8,000</td></tr></tbody></table></div>
<p>In the third row, $8,000 of winter contribution means $2,000 each of four slow months after the direct cost of that work. That improves the annual result but does not eliminate the monthly gap: $5,000 fixed costs less $2,000 winter contribution still require $3,000 of cash support per slow month. If the winter work is unreliable, model it as a separate upside case, not money already in the bank.</p>
<figure><img src="/images/blog/landscaping-seasonal-reserve.svg" alt="Four slow months each require 5000 dollars of cash to cover fixed expenses without winter income, for a total winter funding need of 20000 dollars" width="960" height="500" loading="lazy"><figcaption>Illustrative winter funding need when monthly fixed cash outflow is $5,000 and no winter receipts arrive.</figcaption></figure>
<h2>Budget the winter cash separately</h2>
<p>At $5,000 a month of actual fixed cash payments and no cash collected in four slow months, the simple winter funding need is <strong>$20,000</strong>. That is a timing requirement, not an additional operating expense on top of the $60,000 annual fixed-cost total. Save it from collected peak-season cash or arrange another reliable funding source; do not subtract it twice from annual profit. If some monthly $5,000 items are noncash accounting allocations, remove them from the cash schedule, and add principal, tax and equipment payments that actually become due.</p>
<p>A plan that just breaks even over the year can still run out of money if the busy-season surplus has been spent before winter. A simple monthly cash table should show opening bank balance, collected sales, supplier payments, payroll, fixed bills, debt principal, taxes and closing balance. The <a href="https://blog.landscapeprofessionals.org/business-smarts-managing-cash-flow-through-the-slow-season/">National Association of Landscape Professionals' slow-season cash-flow guidance</a> likewise emphasizes planning the cash needed through the off-season. Confirm seasonality for your region rather than copying someone else's winter calendar.</p>
<h2>How to run your own numbers</h2>
<p>Run an active month with realistic average job price, variable job cost, fixed monthly obligations, owner pay and crew availability in the <a href="https://mybreakeven.com/calculators/landscaping-break-even-calculator/">landscaping break-even calculator</a>. Then extend its monthly contribution to your actual number of workable months and subtract the full year's fixed costs and separately estimated slow-season contribution. Maintain a month-by-month cash schedule beside it. Other currencies are supported if USD is not yours.</p>
<p>For fuller annual cost context, read the <a href="/blogs/landscaping-break-even/">landscaping break-even guide</a>. To validate whether a daily target physically fits the route, see the <a href="/blogs/landscaping-route-density-profit/">landscaping route-density guide</a>. The <a href="/blogs/how-many-lawns-100k/">lawns needed for a $100,000 goal</a> answers an income-target question; here the task is to fund the months with fewer jobs.</p>
<h2>Common seasonal planning mistakes</h2>
<ul><li><strong>Using one profitable summer month as annual proof:</strong> the other months still have costs.</li><li><strong>Counting unsigned winter work:</strong> forecast secured and speculative revenue separately.</li><li><strong>Double counting a winter reserve:</strong> it funds costs already included in the annual budget.</li><li><strong>Using booked instead of completed jobs:</strong> weather delays and cancellations can reduce realized contribution.</li><li><strong>Ignoring crew hours:</strong> daily jobs required by the model may exceed safe available capacity.</li><li><strong>Assuming profit equals bank cash:</strong> invoices, tax payments and loan principal have different timing.</li></ul>
<h2>Takeaways</h2><ul><li>Use 12 months of fixed costs even if sales occur in fewer months.</li><li>Divide the remaining annual target by contribution from completed jobs.</li><li>Test the resulting daily volume against crew hours and weather.</li><li>Keep an independent monthly cash forecast for the slow period.</li></ul>`,
    faq: [
      { q: "How do I calculate landscaping break-even with a winter slowdown?", a: "Add annual fixed costs, subtract dependable slow-season contribution and divide by contribution per completed active-season job. Then divide the job count by the number of months you can actually serve customers." },
      { q: "Can a landscaping business profit in summer and lose money for the year?", a: "Yes. In the worked example, 100 monthly jobs create $1,000 above fixed bills in each active month, but eight such months still leave a $12,000 shortfall against the full year's fixed costs." },
      { q: "How much cash should I keep for winter?", a: "Forecast each slow month's actual cash receipts and payments, then fund the largest cumulative shortfall with an allowance for timing uncertainty. Four months at $5,000 fixed cash cost with no income need $20,000 in the simple illustration, before other cash obligations." },
      { q: "Is a winter reserve an extra expense in break-even math?", a: "No. A reserve is cash set aside to pay costs already budgeted for the winter. Treating both the winter costs and the reserve as expenses would count the same obligation twice." },
      { q: "Do annual service contracts remove seasonality?", a: "They may smooth invoicing and collections, but the work and costs can still cluster in particular months. Follow the agreement's payment and service schedule in a cash forecast." },
      { q: "What if I offer snow or cleanup services in winter?", a: "Estimate their contribution after direct labor, fuel and materials, and subtract only dependable contribution from the annual target. Check contract terms and weather uncertainty with separate scenarios." },
    ],
  }),
];
