// Practical unit-economics guides. All figures below are explicitly illustrative;
// they are not market averages or promises of future results.
const makePost = ({ faq, body, ...post }) => ({
  ...post,
  published: "2026-09-27",
  modified: "2026-09-27",
  imageCaption: "Illustrative scene. Replace the figures in this guide with your own records.",
  unit: post.unit,
  singular: post.singular,
  features: ["Worked examples with stated assumptions", "A practical capacity or demand check", "Costs you can reconcile against your own records"],
  faq,
  html: `${body.trim()}\n<h2>FAQs</h2>\n${faq.map(({ q, a }) => `<h3>${q}</h3><p>${a}</p>`).join("\n")}\n<p>Browse the <a href="https://mybreakeven.com/blogs/">MyBreakeven guide library</a> for more planning guides.</p>`,
});

export const unitEconomicsPosts = [
  makePost({
    slug: "cleaning-business-monthly-expenses",
    tag: "Cleaning",
    name: "Cleaning Business",
    cluster: "operating costs",
    title: "Cleaning Business Monthly Expenses: Build a Job-Based Budget",
    seoTitle: "Cleaning Business Monthly Expenses Guide",
    description: "Build a monthly cleaning business budget that separates job costs from overhead, owner pay and cash timing, then calculates required recurring jobs.",
    metaDescription: "Build a cleaning business budget from labor, supplies, travel, overhead and owner pay. See worked examples and the jobs needed to cover the month.",
    image: "/images/blog/cleaning-business-monthly-expenses-editorial.webp",
    alt: "Cleaning business owner reviews expense records beside supplies, a calculator and vehicle keys",
    calculatorSlug: "cleaning-business-break-even-calculator",
    opening: "A cleaning business does not have one useful monthly expense number. A business with five deep cleans and a business with forty recurring visits can spend the same on insurance but very different amounts on labor, supplies and fuel. Budget the cost of each completed job separately from bills you owe even when nobody books.",
    unit: "jobs",
    singular: "job",
    tags: ["Cleaning", "Monthly Expenses", "Job Costing"],
    body: `
<p>A cleaning business does not have one useful monthly expense number. A business with five deep cleans and a business with forty recurring visits can spend the same on insurance but very different amounts on labor, supplies and fuel. Budget the cost of each completed job separately from bills you owe even when nobody books.</p>
<blockquote><strong>Quick answer:</strong> List recurring monthly bills, calculate the variable cost of one typical paid visit, and divide monthly fixed costs plus desired owner pay by the contribution per visit. If a visit brings in $180, costs $72 to complete, and fixed costs plus owner pay total $4,320, you need 40 paid visits that month. That is a planning example, not an industry average.</blockquote>
<h2>Which expenses belong in a monthly cleaning budget?</h2>
<p>Start with the service itself. For each job, log cleaner hours, the full employer cost of those hours when you have employees, supplies consumed, laundry, disposal, payment fees, parking and the travel required to arrive and leave. A subcontractor invoice is also a job cost. If a client supplies chemicals, record that assumption for that account rather than erasing supplies from the whole business.</p>
<p>Next list costs you owe even in a slow month: insurance premiums, software, phone, storage, equipment finance, base vehicle costs, bookkeeping, minimum payroll and recurring advertising commitments. Separate advertising spend paid per lead from a fixed monthly campaign. The <a href="https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point">SBA break-even formula</a> divides fixed costs by price less variable costs; use the same boundary consistently when you apply it to cleaning jobs.</p>
<p>Write owner pay as its own planning target. An owner who performs cleans may already have a job-specific labor cost in the model. Do not count that wage again as monthly owner pay: decide whether you are planning for wages for cleaning hours, an additional management draw, or both. Keep personal income tax and financing principal in a separate cash plan, since operating profit and money in the bank are different questions.</p>
<h2>Work through one job before budgeting the whole month</h2>
<p>Suppose a recurring two-person visit sells for $180. Total paid cleaning and travel time for the team costs $52, supplies and laundry cost $8, allocated job-specific fuel and parking cost $7, and payment fees cost $5. These are illustrative inputs you should replace with invoices and time records. The variable cost is $52 + $8 + $7 + $5 = <strong>$72</strong>. Contribution per visit is $180 − $72 = <strong>$108</strong>.</p>
<p>Assume monthly insurance, software, storage, minimum marketing and equipment costs total $1,320, and you require $3,000 of owner pay beyond any labor already counted per job. You need $4,320 in monthly contribution. Divide $4,320 by $108 to get <strong>40 completed, paid visits</strong>. At forty visits, sales are $7,200; job-specific costs are $2,880; contribution is $4,320. After $1,320 overhead, $3,000 remains for the owner target before taxes and debt principal. At 35 visits, the contribution is $3,780, leaving a $540 gap against the same target.</p>
<p>A booked visit is not the same as a completed, collected visit. If cancellations and nonpayment reduce 44 scheduled visits to 40 collected visits, plan capacity and lead demand from the conversion you actually observe. Do not silently add five extra jobs to the revenue line.</p>
<h2>Three budgets with different constraints</h2>
<h3>Solo recurring route</h3>
<p>A solo cleaner collects $150 per visit and spends $30 on supplies, travel, fees and paid help. Contribution is $120. Fixed overhead plus planned owner pay is $3,600. Break-even against that combined target is 30 paid visits ($3,600 ÷ $120). At 20 working days, that is 1.5 visits a day. If each appointment consumes three hours including travel and cleanup, 30 visits require 90 hours before sales and administration. The arithmetic works only if demand and the diary both work.</p>
<h3>Two-person team</h3>
<p>A crew charges $240 per job and incurs $144 in labor, transport, supplies and fees. Contribution is $96. With $5,760 in overhead and owner-pay target, it needs 60 jobs. At three jobs per day across twenty service days that is exactly full planned capacity. A single lost workday or a long drive makes the target unattainable unless the route, price or cost structure changes. More revenue per visit does not automatically mean more contribution.</p>
<h3>Deep-clean mix</h3>
<p>A deep clean sells for $400 and uses $220 in variable resources, leaving $180. If the same $4,320 monthly target from the first example applies, 24 deep cleans are needed. But six-hour on-site appointments plus two hours for travel and reset require 192 block hours for one team. If the team has only 160 sellable hours, the plan fails on capacity despite the attractive contribution. Blend recurring and deep cleans with their own prices and costs; do not divide one mixed revenue total by the lowest-cost job.</p>
<h2>What changes the answer in your business?</h2>
<p><strong>Client concentration:</strong> one large account can fill the calendar but may pay slowly or demand night work. Compare contribution by account after transit and supplies, not only invoice size. <strong>Service frequency:</strong> a weekly client may need less setup and quoting time per visit than a one-off. <strong>Travel radius:</strong> a packed local route may fit three jobs where a scattered route fits two. <strong>Paid time:</strong> include loading, transit, setup, rework and paid breaks in the hours you budget.</p>
<p><strong>Timing:</strong> payroll and supplies may leave the account before an invoice is paid. Keep a separate weekly cash schedule for collections, deposits and payroll. <strong>Equipment:</strong> if a machine costs $1,200 to replace every 24 months under your own plan, reserving $50 a month is useful for cash planning; it is not proof that every accounting treatment is the same. <strong>Pricing:</strong> if a price increase costs regular clients, model both the extra contribution per job and the possible volume loss.</p>
<h2>How to run your own numbers</h2>
<p>Export the last month's completed jobs. For each one, record the amount collected, crew hours including paid travel, consumables, transport, card fees and any subcontractor payment. Compute contribution by job type. Add monthly overhead and a clearly defined owner-pay target, then divide by weighted contribution. Use the <a href="https://mybreakeven.com/calculators/cleaning-business-break-even-calculator/">cleaning business break-even calculator</a> to compare required visits, revenue, lead demand and team capacity. Enter realistic available hours rather than every hour in the month. The calculator supports other currencies if USD is not yours.</p>
<p>Review at least one slow week separately from the monthly average. If the model requires 40 paid visits and your team can deliver 36, the shortfall is four visits, or $432 contribution in our first example. You can test a denser route, a more profitable service mix, higher prices or lower fixed costs. Do not label an impossible visit count a forecast.</p>
<h2>Common mistakes that hide the true cost</h2>
<ul><li><strong>Using take-home cash as profit:</strong> deposits may be for next month's work while this month's payroll remains unpaid.</li><li><strong>Charging a crew by on-site hours only:</strong> a 90-minute drive and reset can wipe out the margin on a short job.</li><li><strong>Leaving owner labor at zero:</strong> the business can appear profitable only because the owner works free.</li><li><strong>Mixing one-off and recurring cleans:</strong> they use different labor, materials and customer acquisition effort.</li><li><strong>Assuming 100% collection:</strong> canceled visits and late-paying accounts do not cover today's fixed bills.</li></ul>
<p>For decisions about prices and scale, pair this budget with the <a href="https://mybreakeven.com/blogs/how-much-to-charge-for-house-cleaning/">house cleaning pricing guide</a>, the <a href="https://mybreakeven.com/blogs/how-many-cleaning-clients-5000/">client-count planning guide</a>, and the <a href="https://mybreakeven.com/blogs/is-a-cleaning-business-profitable/">cleaning profitability analysis</a>. Keep the same cost definitions across all three.</p>
<h2>Key takeaways</h2><ul><li>Budget variable cost per completed visit and monthly overhead separately.</li><li>State exactly how owner pay and owner cleaning hours enter the calculation.</li><li>Divide your monthly contribution target by contribution per job, then round up.</li><li>Check paid crew hours, routes, cancellations and cash timing before treating the target as achievable.</li></ul>`,
    faq: [
      { q: "What are the biggest monthly cleaning business expenses?", a: "The answer depends on whether you work alone or employ a crew. Track paid labor and travel per completed job, then add insurance, equipment, software and other fixed bills. Your invoices and time logs are more useful than a generic industry percentage." },
      { q: "Should I include my salary in cleaning business expenses?", a: "Yes, set a realistic owner-pay target. If you already count your paid cleaning hours in the cost of each job, do not count those same hours a second time as a monthly salary." },
      { q: "How many cleaning jobs cover $4,320 a month?", a: "At $108 contribution per completed job, 40 jobs cover a $4,320 contribution target. At a different price or job cost the required number changes, so recalculate from your own contribution." },
      { q: "Is the monthly break-even figure enough to plan cash?", a: "No. Break-even describes operating economics; cash also depends on when clients pay and when payroll, tax reserves, equipment and financing payments are due." },
      { q: "Do cancellations belong in variable cost?", a: "Track cancellation losses and any paid labor or travel caused by them. Forecast completed paid visits separately from bookings, and include unavoidable cancellation costs where they actually arise." },
    ],
  }),
  makePost({
    slug: "ecommerce-return-cost-per-order",
    tag: "E-commerce",
    name: "E-commerce",
    cluster: "order economics",
    title: "Ecommerce Return Cost per Order: Price Refunds Into Your Margin",
    seoTitle: "Ecommerce Return Cost per Order Guide",
    description: "Calculate return cost per order from refund losses, shipping, processing, inspection and resale value, with worked examples and a break-even check.",
    metaDescription: "Calculate ecommerce return cost per order from refunds, freight, fees and lost resale value. Use worked examples to protect contribution margin.",
    image: "/images/blog/ecommerce-return-cost-per-order-editorial.webp",
    alt: "Online store owner scans a returned package at a packing station",
    calculatorSlug: "ecommerce-break-even-calculator",
    opening: "A return does more than reverse a sale. Outbound freight may already be spent; payment processing, a return label, inspection and repackaging can remain even when the product comes back. Measure the loss on a returned order, then spread expected return losses across every order you price.",
    unit: "orders",
    singular: "order",
    tags: ["E-commerce", "Returns", "Contribution Margin"],
    body: `
<p>A return does more than reverse a sale. Outbound freight may already be spent; payment processing, a return label, inspection and repackaging can remain even when the product comes back. Measure the loss on a returned order, then spread expected return losses across every order you price. The numbers below are an illustrative model, not a claimed average return rate.</p>
<blockquote><strong>Quick answer:</strong> Expected return burden per placed order equals return probability times the contribution lost when a customer returns, compared with a kept order. If a kept $80 order contributes $29, a returned order loses $31, and 10% of orders are returned, expected contribution is 90% × $29 + 10% × (−$31) = $23. The return burden is $6 per placed order.</blockquote>
<h2>Decide what "cost of a return" means</h2>
<p>There are two useful views. <strong>Cash loss on the returned order</strong> counts unrecovered outbound freight, handling, card fees, return freight, inspection, damaged stock and refunds, less any resale proceeds. <strong>Incremental cost versus a kept order</strong> measures the contribution you expected but lost. The second view is what belongs in an expected-contribution comparison across all placed orders. Do not subtract both the entire refund and the forgone contribution from the same order: that double counts the lost sale.</p>
<p>Whether a processing fee is returned depends on the payment provider and contract. For example, <a href="https://help.shopify.com/en/manual/payments/shopify-payments/payouts/refunds">Shopify Payments says its original card fee is not refunded</a> when a merchant refunds a transaction; that is a provider-specific rule, not a universal rate. Check your own gateway, return policy and fulfillment invoices. Return shipping may be paid by you, the customer or split. A restockable item and one that must be discarded have very different economics.</p>
<h2>A complete $80 order example</h2>
<p>Assume a product sells for $80. If kept, its product cost is $28; fulfillment and outbound shipping cost $12; payment processing and platform charges cost $4; and acquisition spend attributable to that order is $7. Kept-order contribution is $80 − $28 − $12 − $4 − $7 = <strong>$29</strong>. Keep acquisition cost in the model even when it was spent days before the purchase; it is still money the sale must recover.</p>
<p>If the customer returns the product for a full refund, assume the unit can be sold again at full price later. Restore the $28 unit to inventory rather than treating it as destroyed, but record $6 return freight and $2 inspection and repackaging. The spent $12 outbound freight, $4 fees and $7 acquisition remain. That return produces a <strong>$31 loss</strong> on the order: −$12 − $4 − $7 − $6 − $2 = −$31. The product cost is recovered as sellable inventory under this assumption. If the unit cannot be resold, account for the unrecovered stock value too.</p>
<p>The difference between a kept order's $29 contribution and a returned order's −$31 is <strong>$60</strong>. At a hypothetical 10% return probability, expected contribution per placed order is 0.90 × $29 + 0.10 × (−$31) = <strong>$23.00</strong>. The return burden relative to the no-return $29 case is $6 per placed order. On 200 orders, that is $4,600 expected contribution before fixed overhead. Use observed returns by category; an order-level storewide rate can hide a costly product line.</p>
<p>If the returned unit has only $12 recoverable value instead of $28, write down $16 in the return case. Returned-order contribution becomes −$47 and expected contribution at the same 10% return assumption becomes $21.40. Check the actual recovered value when the item resells; do not book a hoped-for resale as guaranteed cash.</p>
<h2>Three practical return scenarios</h2>
<h3>Lower return volume, same $80 order</h3>
<p>At a 5% return probability with $29 kept contribution and −$31 returned contribution, expected contribution is 0.95 × $29 + 0.05 × (−$31) = $26.00. Compared with the 10% assumption above, the extra $3 per order across 200 orders amounts to $600 of monthly contribution. That does not mean lowering returns is free; product photos, fit guidance and service may themselves cost money.</p>
<h3>Merchant pays a more expensive return label</h3>
<p>Keep the 10% probability but raise return freight from $6 to $16. Returned-order result drops from −$31 to −$41. Expected contribution is 0.90 × $29 + 0.10 × (−$41) = $22.00. The extra $10 on each return costs $1 per placed order at this return probability. Model the difference before promising free returns on every SKU.</p>
<h3>Partial refund or exchange</h3>
<p>Suppose an $80 order is exchanged for another $80 item, with $14 for reverse and replacement freight and $3 extra handling. It is not equivalent to a full refund: revenue stays $80 if the replacement is paid for and the original unit is saleable, but contribution falls by $17 from $29 to $12. If the original cannot be resold, add its unrecovered value too. Exchanges need a separate line in your data, and repeat customer value is a separate decision from immediate order contribution.</p>
<h2>How returns affect break-even orders</h2>
<p>Suppose fixed overhead and owner-pay target total $4,600 a month. With no returns and $29 contribution, $4,600 ÷ $29 means 159 whole orders. With the 10% return scenario's $23 expected contribution, $4,600 ÷ $23 means <strong>200 placed orders</strong>. That is 41 additional orders before accounting for changes in traffic quality or capacity. Neither count guarantees that the projected return mix will occur, so monitor actual outcomes weekly.</p>
<h2>How to run your own numbers</h2>
<p>Export a recent cohort of placed orders by SKU and channel. Mark kept, refunded, exchanged, canceled before shipment and partially refunded orders separately. For each returned item, record cash refunded, outbound and reverse freight, nonreturned fees, handling, acquisition spend and actual recoverable inventory value. Calculate contribution for kept and returned orders with the same cost boundary. Feed your weighted average product price, variable costs, expected returns, overhead and fulfillment capacity into the <a href="https://mybreakeven.com/calculators/ecommerce-break-even-calculator/">ecommerce break-even calculator</a>. It is a planning aid; replace modeled return assumptions with actual cohorts as they mature.</p>
<p>Refunds and exchanges are not the same as fraudulent chargebacks, which may add other fees. Read the <a href="https://mybreakeven.com/blogs/ecommerce-shipping-costs/">ecommerce shipping cost guide</a> for the outbound and subsidized-shipping side, the <a href="https://mybreakeven.com/blogs/how-to-price-products-for-ecommerce/">product pricing guide</a> to rebuild price, and the <a href="https://mybreakeven.com/blogs/ecommerce-orders-per-day-profitable/">orders-per-day guide</a> to test demand and fulfillment.</p>
<h2>Common mistakes</h2><ul><li><strong>Calling the full refund a second expense:</strong> if you already remove the sale from revenue, subtracting the same $80 again makes the loss look twice as large.</li><li><strong>Assuming all returned products can be resold:</strong> inspect actual condition and recovery value before giving inventory full credit.</li><li><strong>Using one return percentage for all SKUs:</strong> channel, product and customer cohort can change both probability and loss severity.</li><li><strong>Ignoring time:</strong> a refund in a later month can leave a cash gap today even if the model balances eventually.</li><li><strong>Assuming gateway fees behave alike:</strong> verify the refund terms for your own provider.</li></ul>
<h2>Key takeaways</h2><ul><li>Compare kept-order and returned-order contribution using one consistent cost definition.</li><li>Weight those outcomes by observed return frequency for each product and channel.</li><li>Price shipping, processing, handling and unsellable inventory into the decision.</li><li>Convert expected contribution into required orders and check fulfillment capacity.</li></ul>`,
    faq: [
      { q: "How do I calculate ecommerce return cost per order?", a: "Compute contribution for a kept order and a returned order. Multiply the difference by your observed return probability. In the worked example a $60 difference at a 10% return probability reduces expected contribution by $6 per placed order." },
      { q: "Should returned inventory be counted as lost?", a: "Only to the extent that value cannot be recovered. If the item can be resold, record a supportable recoverable value; if it is damaged or obsolete, include its write-down." },
      { q: "Are card processing fees refunded on returns?", a: "Policies vary by provider and contract. Shopify Payments says its original credit card fee is not returned when a refund is issued. Verify your own gateway terms before forecasting." },
      { q: "Is a 10% return rate a benchmark for my store?", a: "No. Ten percent is only an illustrative assumption in this article. Measure your own mature orders by SKU, channel and period before using a return probability in pricing." },
      { q: "How do exchanges affect the model?", a: "Track exchanges separately from full refunds. If revenue is retained, extra shipping and handling reduce contribution; if the original item cannot be resold, add its unrecovered value." },
    ],
  }),
  makePost({
    slug: "agency-billable-utilization-rate",
    tag: "Agency",
    name: "Agency",
    cluster: "delivery capacity",
    title: "Agency Billable Utilization Rate: Plan Retainers and Team Capacity",
    seoTitle: "Agency Billable Utilization Rate Guide",
    description: "Calculate agency billable utilization from real working hours, scope retainers against capacity, and test contribution before adding clients.",
    metaDescription: "Calculate agency billable utilization from working hours and client scope. See retainers, delivery capacity and break-even worked through together.",
    image: "/images/blog/agency-billable-utilization-rate-editorial.webp",
    alt: "Agency team allocates client delivery time on a weekly planning board",
    calculatorSlug: "agency-break-even-calculator",
    opening: "A retainer can be profitable on paper and impossible to deliver with the people you have. Billable utilization is the share of practical working time spent on client delivery you can charge for. It helps you price scope and protect room for sales, training, management and rework.",
    unit: "clients",
    singular: "client",
    tags: ["Agency", "Billable Utilization", "Retainers"],
    body: `
<p>A retainer can be profitable on paper and impossible to deliver with the people you have. Billable utilization is the share of practical working time spent on client delivery you can charge for. It helps you price scope and protect room for sales, training, management and rework. Choose a clear definition before comparing months: invoiced hours, hours worked for clients, and hours sold in fixed-fee contracts are not always equal.</p>
<blockquote><strong>Quick answer:</strong> Divide billable client-delivery hours by practical available working hours for the same people and period. A two-person team with 320 available hours and 192 billable delivery hours has 60% utilization. If its sustainable planning ceiling is 65%, that leaves 16 more billable hours for the month, not an unlimited number of new retainers.</blockquote>
<h2>Define the denominator before calculating a rate</h2>
<p>For a simple four-week planning month, two full-time people at 40 hours a week offer 2 × 40 × 4 = <strong>320 scheduled hours</strong>. If you expect vacation, holidays or a shorter paid schedule, subtract them first. If an owner splits time between delivery and sales, put only the owner's actual available delivery allocation in a delivery-capacity model. Record which definition you chose; changing the denominator can make utilization look better while the team is no less busy. <a href="https://asana.com/resources/utilization-rate">Asana's utilization guide</a> also uses billable hours divided by available hours; the difficult part is choosing an honest available-hours figure for your team.</p>
<p>Track work on accounts at task level: production, meetings, client revisions and reporting all consume time even when a fixed retainer does not itemize hours. Nonbillable time includes proposals, internal meetings, hiring, training, administration, business development and unbilled overruns. Aiming for 100% billable time would leave no capacity to win or support future work. The right planning ceiling is a deliberate assumption based on your team and service, not an asserted universal benchmark.</p>
<h2>Turn hours into a client limit</h2>
<p>Assume two people have 320 practical working hours this month. You reserve 35% for nonbillable work and schedule risk, leaving 320 × 0.65 = <strong>208 billable hours</strong>. Eight client retainers each require 24 actual delivery hours: 8 × 24 = <strong>192 hours</strong>. Utilization is 192 ÷ 320 = <strong>60%</strong>, with sixteen billable hours of planning room. If one client needs thirty hours rather than twenty-four, only ten hours remain.</p>
<p>A ninth 24-hour retainer raises planned billable hours to 216, or 67.5% of available time. The team would exceed its 208-hour billable ceiling by eight hours. That is a capacity signal, not proof the extra contract has bad economics. You could rescope work, improve a documented workflow, shift part of delivery to a contractor with a real cost, or hire after testing demand and supervision load. Do not promise the ninth client based on a time budget that already has no room for emergencies.</p>
<h2>Check contribution alongside utilization</h2>
<p>Suppose a retainer pays $2,000 a month. Assigned delivery labor costs $900 and project-specific software or contractors cost $100, so contribution is <strong>$1,000 per retainer</strong>. If fixed agency overhead and the owner's pay target total $6,000, the break-even target is six retained clients at this mix. Six clients need 144 delivery hours (6 × 24), below the 208-hour ceiling. The business needs enough clients to reach the financial target, and enough delivery room to keep them well served.</p>
<p>At eight clients, contribution is $8,000; $2,000 remains above the $6,000 target. But if actual hours rise to 32 per client because proposals understated revision work, the delivery requirement becomes 256 hours. The economic model based on $900 labor per account must also be updated: extra paid hours are a cost, not merely a utilization statistic. Treat time logs and job costs as the same operating record.</p>
<h2>Three scope situations worth testing</h2>
<h3>Fixed-fee work grows quietly</h3>
<p>Eight retainers were sold at 24 hours each, yet they now average 27 hours. Delivery becomes 216 hours, eight above the 208-hour planning ceiling. If the additional three hours per account cost $45 per hour in loaded labor, monthly delivery cost rises by 8 × 3 × $45 = $1,080. Contribution falls from $8,000 to $6,920 before any overtime premium. Identify which change requests or meetings produced the overrun before simply asking the team to work faster.</p>
<h3>One small client leaves</h3>
<p>If one of six equal $1,000-contribution retainers cancels, the monthly contribution drops from $6,000 to $5,000 and misses the target by $1,000. Utilization falls from 144 ÷ 320 = 45% to 120 ÷ 320 = 37.5%. Capacity is now available, but the immediate problem is replacing contribution. Sales pipeline timing and cash reserves matter as much as staff hours.</p>
<h3>Contractor adds capacity at a cost</h3>
<p>Imagine a ninth client needs 24 hours while only sixteen hours remain under the planning ceiling. A specialist covers eight hours for $400. The team's modeled time becomes 208 hours, exactly at the ceiling; the new $2,000 retainer's contribution falls from $1,000 to $600 if the $400 is additional to the assumed delivery costs. Keep supervision and revisions in the hours budget. Outsourcing eight production hours may create more than zero management hours.</p>
<h2>What actually changes utilization?</h2>
<p><strong>Service mix:</strong> a strategy account can need more senior review and fewer production hours than a content retainer. <strong>Client behavior:</strong> delayed approvals compress work into one week even when the monthly total looks manageable. <strong>Skill bottlenecks:</strong> a writer cannot replace a developer hour one-for-one. <strong>Time off:</strong> four-week averages conceal a holiday week. Make a weekly capacity view before promising launch dates.</p>
<p><strong>Billing definition:</strong> if time worked is not invoiced under a fixed fee, it is still delivery work and should appear in cost and utilization. <strong>New-business time:</strong> reducing it may improve this month's percentage while drying up next quarter's pipeline. <strong>Owner workload:</strong> a founder's client work is real capacity, but a founder doing sales and account management cannot offer forty billable hours every week.</p>
<h2>How to run your own numbers</h2>
<p>List each person, practical hours available, client work by account, loaded delivery cost, contractor commitments and reserved nonbillable time. For fixed-fee retainers, compare promised scope with last month's actual task hours. Use the <a href="https://mybreakeven.com/calculators/agency-break-even-calculator/">agency break-even calculator</a> to test revenue, contribution, required retainer clients, leads and delivery capacity. Enter the same hours and owner-pay definition you used in your account worksheet. The calculator supports other currencies if you bill outside USD.</p>
<p>For the money side of this model, use the <a href="https://mybreakeven.com/blogs/agency-retainer-pricing/">retainer pricing guide</a>. For a second view of labor, overhead and available work, read <a href="https://mybreakeven.com/blogs/agency-profit-margin/">agency margin and utilization</a>. To turn an owner-pay target into a client count, see the <a href="https://mybreakeven.com/blogs/how-many-agency-retainer-clients/">agency retainer client-count example</a>.</p>
<h2>Common mistakes</h2><ul><li><strong>Counting every salaried hour as deliverable:</strong> proposals, QA, sick time and management still occur.</li><li><strong>Using sold hours instead of actual hours:</strong> overruns can erase contribution even without a scope change.</li><li><strong>Averaging unlike roles:</strong> the designer may be full while the account manager has room; one team average hides the bottleneck.</li><li><strong>Treating a full calendar as success:</strong> the agency can be fully utilized and below the contribution target.</li><li><strong>Buying capacity without supervision time:</strong> contractors need briefs, QA and client coordination.</li></ul>
<h2>Key takeaways</h2><ul><li>Use the same time period and worker set in the numerator and denominator.</li><li>Budget nonbillable and contingency time explicitly.</li><li>Test client count against both contribution and role-specific available hours.</li><li>Update scope estimates from actual task records each month.</li></ul>`,
    faq: [
      { q: "How do you calculate agency billable utilization?", a: "Divide actual billable client-delivery hours by practical available working hours for the same people and period, then multiply by 100. In the example, 192 ÷ 320 is 60%." },
      { q: "Is 65% a good agency utilization rate?", a: "It is a planning assumption in this guide, not a universal benchmark. Your sustainable rate depends on services, roles, sales work, leave, support obligations and delivery risk." },
      { q: "Should fixed-fee retainers count as billable hours?", a: "Record actual client-delivery hours even when you invoice a fixed amount. That lets you see whether the retainer price covers the labor and other work consumed." },
      { q: "Can a contractor increase billable capacity?", a: "Yes, if their work replaces a real delivery bottleneck. Include contractor fees, briefs, review and coordination before deciding whether the added client improves contribution." },
      { q: "What if the agency reaches break-even but utilization is low?", a: "That can happen if contribution per client is strong or fixed costs are low. Check sales pipeline and individual role workloads before treating unused time as a problem on its own." },
    ],
  }),
  makePost({
    slug: "landscaping-route-density-profit",
    tag: "Landscaping",
    name: "Landscaping",
    cluster: "route capacity",
    title: "Landscaping Route Density: Price Drive Time Into Each Stop",
    seoTitle: "Landscaping Route Density and Job Profit",
    description: "Calculate how drive time changes lawn-care route capacity, contribution per visit and monthly break-even stops, with three practical scenarios.",
    metaDescription: "See how travel time changes landscaping route profit. Calculate contribution per stop, visits per day and monthly break-even with worked examples.",
    image: "/images/blog/landscaping-route-density-profit-editorial.webp",
    alt: "Landscaping truck and mower travel between nearby lawns on a suburban route",
    calculatorSlug: "landscaping-break-even-calculator",
    opening: "Two lawn-care routes can bill the same price per stop and produce different profits. The difference may be miles between customers, crew loading time and whether the schedule fits another paid visit. Route density is useful only when you connect travel to both cost per visit and available hours.",
    unit: "jobs",
    singular: "job",
    tags: ["Landscaping", "Route Density", "Capacity"],
    body: `
<p>Two lawn-care routes can bill the same price per stop and produce different profits. The difference may be miles between customers, crew loading time and whether the schedule fits another paid visit. Route density is useful only when you connect travel to both cost per visit and available hours. A short straight-line distance is no substitute for recorded drive time and actual paid crew hours.</p>
<blockquote><strong>Quick answer:</strong> Add on-site service, drive, loading and reset time for each stop. Divide practical route hours by that block time to estimate daily capacity, then compare contribution per paid stop with monthly overhead. If a $95 stop contributes $53 and the monthly target is $4,240, the route needs 80 paid visits; with twenty workdays that means four visits each day.</blockquote>
<h2>What route density measures</h2>
<p>You can measure visits per paid crew hour, dollars of contribution per route hour, or average travel minutes per completed stop. Pick the metric that answers your question. "Customers per ZIP code" can help map demand, but it does not show whether a route crosses a river at rush hour or requires a long equipment reset. Track actual start and end times by stop for several weeks, including the first drive from the yard and the last return.</p>
<p>Fuel is only one travel cost. The crew may be paid while driving; vehicles wear, equipment is tied up and a large gap may block the next booking. For financial planning, record loaded crew labor, fuel, materials, disposal, card fees and any visit-specific subcontracting as variable costs. Allocate fixed vehicle, insurance and shop expenses consistently. The <a href="https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point">SBA fixed-versus-variable break-even method</a> gives you a useful starting point for monthly required visits.</p>
<h2>Work one illustrative mowing route</h2>
<p>Suppose a routine property brings in $95. Paid labor attributable to the visit is $30, fuel and route-specific vehicle use $6, and consumables plus payment fees $6. Variable cost is $42 and contribution is <strong>$53 per completed stop</strong>. If fixed expenses plus a defined owner-pay target total $4,240 per month, required visits are $4,240 ÷ $53 = <strong>80 visits</strong>. Over twenty service days, the plan needs four paid stops daily.</p>
<p>Assume each service takes one hour on-site, and the route plus loading and reset averages thirty minutes per stop. Four stops take 4 × 1.5 = <strong>six block hours</strong>. A seven-hour practical route day leaves one hour for weather, calls and surprises. Across twenty days, eighty stops produce $7,600 revenue, $3,360 variable costs and $4,240 contribution, exactly covering the target. These figures describe a model, not a quote for lawn care in your market.</p>
<h2>Three route designs from the same service</h2>
<h3>Spread-out stops</h3>
<p>If travel and reset rise to one hour per stop, a visit takes two block hours. Only three whole visits fit in the seven-hour practical day. Twenty days yield 60 visits and 60 × $53 = $3,180 contribution, <strong>$1,060 short</strong> of the same monthly target. The cost of extra paid travel might also push labor and fuel above the original $42, making the gap larger. Recompute contribution from the actual route rather than carrying the dense-route number forward uncritically.</p>
<h3>Compact route with one extra opening</h3>
<p>If a neighborhood cluster reduces travel and reset to twenty minutes, each visit uses one hour twenty minutes. Four visits use five hours twenty minutes, leaving time for an occasional fifth or a slower property. Five every day would mean 100 visits and 5,300 contribution at the original $53 per stop, but do not budget all 100 until season, weather, demand and the crew schedule justify them.</p>
<h3>Higher price, same four stops</h3>
<p>Suppose the price rises to $110 and visit-specific cost rises to $45 after wage and fuel changes. Contribution is $65. At 80 paid visits, contribution is $5,200, which is $960 above a $4,240 target. But the stronger contribution does not create the missing two hours in a spread-out route. Price and capacity must pass separate checks, and lost clients after a price change would affect total visits.</p>
<h2>Weather and season change the monthly plan</h2>
<p>If you can work only fifteen service days in a month, four visits a day produce sixty visits. At $53 contribution, that is $3,180 and a $1,060 gap. You might pre-sell weather-resilient work, hold a cash reserve from stronger months, reschedule where possible or revisit the owner-pay target for that period. Do not count rainy days as available capacity when mowing is physically impossible.</p>
<p>A visit can also be more than one crew's work. For two simultaneous crews, keep each crew's hours, vehicle and job-specific labor separate; adding both crews' stops to one capacity denominator inflates performance. For quoted landscaping projects, use the same block-time logic but track materials and equipment on a project basis rather than treating every job as one identical lawn.</p>
<p>When one outbound drive serves four nearby properties, allocate that trip across the four stops instead of charging the whole drive to the first customer. The same applies to the drive back to the yard. Keep the route's total paid hours and total contribution as the control figure: allocations can show which prices to revisit, but moving travel minutes between customers cannot create additional capacity. Compare two route plans on the same service-day assumption before rearranging repeat customers.</p>
<h2>What changes the answer?</h2>
<p><strong>Property scope:</strong> acreage, slopes, gates, hedges, trimming and disposal change service minutes. <strong>Geography:</strong> bridge crossings and school traffic matter more than map distance. <strong>Schedule:</strong> customers may allow service only on a particular day. <strong>Stops per account:</strong> weekly and fortnightly contracts create different monthly visit counts. <strong>Team skills:</strong> time estimates from a seasoned crew may not transfer to new staff. <strong>Collections:</strong> an invoiced stop does not support current payroll until the money arrives.</p>
<h2>How to run your own numbers</h2>
<p>Keep a two-week route log with property, charged price, arrival, departure, all drives, paid crew time, materials and completed payment. Calculate contribution for each service type and total block hours for each route day. Use the <a href="https://mybreakeven.com/calculators/landscaping-break-even-calculator/">landscaping break-even calculator</a> with your price, variable cost, overhead, lead demand and actual crew capacity. Recheck it for a slow-weather month. Other currencies can be used if your business does not price in USD.</p>
<p>For a different service mix, pair this route model with the <a href="https://mybreakeven.com/blogs/lawn-care-pricing-per-acre/">lawn care pricing guide</a>, the <a href="https://mybreakeven.com/blogs/how-many-lawns-100k/">lawns needed for an owner-pay goal</a>, and the <a href="https://mybreakeven.com/blogs/landscaping-business-profit-margin/">landscaping margin analysis</a>. The same route can be well priced per lawn and still have too few sellable hours.</p>
<h2>Common mistakes</h2><ul><li><strong>Counting only mowing time:</strong> load, unload, travel and disposal take paid hours.</li><li><strong>Using a map radius as a time estimate:</strong> real route times vary with traffic and permitted service windows.</li><li><strong>Assuming a fifth stop fits because four fit:</strong> use whole block time and leave a realistic buffer.</li><li><strong>Combining all job types into one average:</strong> cleanup and routine mowing have different materials and hours.</li><li><strong>Planning every month like peak season:</strong> weather and daylight limit deliverable visits.</li></ul>
<h2>Key takeaways</h2><ul><li>Measure contribution per completed stop and paid block hours for the entire route.</li><li>Convert monthly contribution target into whole paid visits.</li><li>Check that those visits fit real days, weather and customer locations.</li><li>Rebuild the model whenever route geography or crew mix changes.</li></ul>`,
    faq: [
      { q: "How do I measure lawn-care route density?", a: "Use actual route records: completed stops per paid crew hour, average travel minutes per stop and contribution per route hour. Map distance by itself does not capture traffic, gates or setup time." },
      { q: "How many lawn-care stops fit in a day?", a: "Divide practical route hours by the complete service, travel, loading and reset block for your stops, then round down. In the example, four 90-minute visits fit within a seven-hour route day." },
      { q: "Can route density improve profit without raising prices?", a: "It can free paid crew time and reduce some travel costs, provided enough nearby customers exist and the route remains serviceable. Recheck job contribution and actual demand before forecasting extra visits." },
      { q: "Should I count the drive from my yard?", a: "Yes, include the paid time and relevant vehicle cost for the first outbound leg and the return. Allocating that time across stops gives a more realistic picture of the whole route." },
      { q: "What if bad weather removes five workdays?", a: "At four visits per day, the illustrative route loses twenty possible visits. At $53 contribution per visit, that is $1,060 of the monthly target, before any change in other costs." },
    ],
  }),
  makePost({
    slug: "photography-cost-per-session-editing",
    tag: "Photography",
    name: "Photography Business",
    cluster: "session economics",
    title: "Photography Cost per Session: Include Editing and Delivery Time",
    seoTitle: "Photography Cost per Session and Editing",
    description: "Work out photography session cost beyond shoot hours, including editing, travel, assistant fees and delivery capacity, with complete examples.",
    metaDescription: "Price a photography session using shoot, editing, travel and delivery time. Calculate contribution and the bookings your schedule can actually fulfill.",
    image: "/images/blog/photography-cost-per-session-editing-editorial.webp",
    alt: "Camera and laptop with an editing workspace show photography work after a session",
    calculatorSlug: "photography-business-break-even-calculator",
    opening: "A two-hour shoot can occupy most of a workday after planning, travel, culling, editing and delivery. If you divide your session fee only by camera time, you can overestimate the number of clients your calendar will support. Measure the whole block and its job-specific costs.",
    unit: "sessions",
    singular: "session",
    tags: ["Photography", "Editing Time", "Session Pricing"],
    body: `
<p>A two-hour shoot can occupy most of a workday after planning, travel, culling, editing and delivery. If you divide your session fee only by camera time, you can overestimate the number of clients your calendar will support. Measure the whole block and its job-specific costs. The <a href="https://www.bls.gov/ooh/media-and-communication/photographers.htm">Bureau of Labor Statistics describes photo editing and postproduction</a> as part of photographers' work; count those hours in your own service model.</p>
<blockquote><strong>Quick answer:</strong> Add shoot, preparation, travel, editing, delivery and communication hours per booking. Subtract print or gallery, assistant, travel and payment expenses from the collected session fee to find contribution. In an illustrative $650 booking with $180 job-specific expenses, contribution is $470; if overhead and an owner-pay target total $4,700, you need ten completed bookings and enough working hours to deliver them.</blockquote>
<h2>Define a session from inquiry to delivery</h2>
<p>Record consultation, planning, location scouting, packing, travel, setup, shooting, backup, culling, retouching, proofing, revisions, gallery delivery, invoicing and follow-up. Some steps are shared across bookings, others are specific. A studio portrait and a wedding should not share a single editing-hour assumption. If you outsource editing, count the vendor invoice as a variable cost and keep your brief and review time in your own capacity plan.</p>
<p>Separate job-specific cash costs from fixed monthly bills. Assistant fees, prints, online gallery fees charged per session, location or permit fees and payment processing may vary with each booking. Rent, subscriptions, insurance and owned-equipment replacement planning often persist in a month with few bookings. Decide how your own shooting and editing labor enters the plan. An owner-pay target in fixed monthly need can stand in for owner labor; do not then subtract the same owner's hourly pay from each job unless that is a deliberate separate wage.</p>
<h2>A complete $650 booking</h2>
<p>Assume a session fee of $650. This illustrative job costs $50 for prints or gallery delivery, $80 for an assistant, $30 for travel and $20 for fees. Variable cash expense is $50 + $80 + $30 + $20 = <strong>$180</strong>. Contribution is $650 − $180 = <strong>$470</strong>. If fixed costs plus planned owner pay total $4,700 a month, ten completed sessions supply $4,700 contribution. Ten bookings generate $6,500 sales and $1,800 session-specific cash expenses before fixed bills.</p>
<p>Now count time. A typical booking might use one hour of planning, two hours of shooting, four hours of culling and editing, and one hour of delivery, revisions and admin: <strong>eight hours</strong>. Ten sessions use eighty working hours. If your realistic monthly client-delivery time after marketing, bookkeeping and time off is 100 hours, the plan fits with twenty hours of headroom. That is a capacity example, not a claim about how long all sessions take.</p>
<h2>Three changes that alter the plan</h2>
<h3>Editing takes longer than quoted</h3>
<p>If editing takes six hours rather than four, a booking uses ten total hours. Ten sessions need all 100 available hours; the financial break-even number stays ten if cash expenses and price stay unchanged, but no delivery buffer remains. If revisions extend editing further, either scope or capacity must change. Track actual culling and retouching by package rather than inferring editing effort from gallery size.</p>
<h3>Lower price, unchanged cash cost</h3>
<p>At a $500 fee and $180 variable cash cost, contribution is $320. A $4,700 monthly target now requires 15 whole sessions because 14 × $320 = $4,480 while 15 × $320 = $4,800. At eight hours each, 15 sessions need 120 hours, above the 100-hour capacity. Lowering the headline price may increase inquiries, but it does not create twenty extra hours to deliver the work.</p>
<h3>Outsourcing edits</h3>
<p>Suppose an editor charges $120 per booking, and your own edit time drops from four hours to one hour of selecting, briefing and quality review. Variable cash expense rises to $300, so contribution at a $650 fee becomes $350. Monthly $4,700 target requires 14 sessions, since 13 × $350 = $4,550. Your own block is now five hours per booking, so fourteen sessions use seventy hours; that could fit if demand, editor availability, quality and revision turnaround hold. Paying an editor changes both capacity and contribution.</p>
<h2>Price scope, not just your shooting hour</h2>
<p>Put deliverables in writing: shoot duration, selected image count, editing level, turnaround, revision rounds, prints, travel boundary and licensing terms where relevant. A package with basic color correction has different hours from detailed retouching. Build prices from expected total work and costs, then test whether enough bookings exist at that price. The point is to make a promise you can deliver profitably, not to assign an unsupported industry rate to every image.</p>
<p>Late gallery delivery can also shift collections into the next month. A deposit helps schedule cash but is not an additional sale on top of the total package fee. Keep booking, earned revenue and cash collection on separate lines if you use deposits. Equipment replacement belongs in your planning even if the camera was paid for years ago; decide how you will fund its future replacement without counting the same expense twice.</p>
<p>Bookings also need a demand check. If ten completed sessions are required and only one in four qualified inquiries becomes a completed, paid booking under your own records, you need about forty qualified inquiries. That is ten ÷ 0.25, before accounting for reschedules or seasonal demand. Do not use a generic inquiry conversion rate from another photographer; track inquiries by service, source and month. A cheaper package might increase inquiry volume and still reduce contribution per available editing hour.</p>
<h2>How to run your own numbers</h2>
<p>Review your last ten to twenty completed bookings by package. Time each phase, record actual collected fees, assistants, travel, printing, platform fees and revisions. Use the average for a comparable package, not one unusually easy job. Enter package revenue, variable cost, overhead, monthly owner-pay target, leads and available time into the <a href="https://mybreakeven.com/calculators/photography-business-break-even-calculator/">photography business break-even calculator</a>. Compare required sessions with editing and delivery hours before making a sales target. The calculator supports other currencies where relevant.</p>
<p>For broader packages, see the <a href="https://mybreakeven.com/blogs/photography-pricing-packages/">photography pricing guide</a>; for bookings required by an income goal, use the <a href="https://mybreakeven.com/blogs/how-many-photography-clients-month/">monthly photography client-count guide</a>; and for overhead and owner pay, read the <a href="https://mybreakeven.com/blogs/photography-business-profit-margin/">photography profitability analysis</a>.</p>
<h2>Common mistakes</h2><ul><li><strong>Billing the two-hour shoot and giving away editing:</strong> the client buys a finished deliverable, and your calendar must hold all its work.</li><li><strong>Calling deposits new revenue twice:</strong> a deposit is part of the package price, not an added booking.</li><li><strong>Ignoring assistant and gallery fees:</strong> those costs reduce contribution on each relevant session.</li><li><strong>Quoting unlimited revisions:</strong> unbounded editing can consume capacity even when cash expenses do not change.</li><li><strong>Using one average for unlike sessions:</strong> weddings, headshots and commercial product work have different scopes.</li></ul>
<h2>Key takeaways</h2><ul><li>Record every phase from inquiry through delivered gallery.</li><li>Separate session-specific cash expenses from monthly costs and owner-pay target.</li><li>Calculate whole bookings needed from contribution, then compare with available hours.</li><li>Price editing and revisions into the scope before accepting another client.</li></ul>`,
    faq: [
      { q: "Should editing time be included in photography session pricing?", a: "Yes. Culling, retouching and revisions consume working hours even when the client only sees the finished photographs. Measure actual hours for the package you sell." },
      { q: "How many $650 sessions cover $4,700 a month?", a: "With $180 variable cash expense per booking, each session contributes $470, so ten completed bookings cover a $4,700 contribution target. You must also confirm there is time and demand to complete them." },
      { q: "Does hiring an editor always increase profit?", a: "No. It releases your time but adds a per-booking expense. Compare the new contribution, your remaining review time, quality control and the extra bookings you can actually sell." },
      { q: "Is my deposit additional revenue?", a: "No. A deposit is an early payment toward the agreed package total. Record when cash arrives separately from the total sale to avoid counting the fee twice." },
      { q: "What if editing time varies by client?", a: "Group completed bookings by comparable package and scope, then use a realistic range rather than one storewide average. Define revision rounds and update your estimate when actual time changes." },
    ],
  }),
];
