import React, { useState } from 'react';
import { authorityPages, worksheetFile, exampleJobs, demoPlans } from './authorityResources.js';
import { calculate, FORMULA_ENGINE_VERSION } from './engine.js';
import { trackProductEvent } from './productAnalytics.js';
import './authority-pages.css';

const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const ReferenceLinks = () => <nav className="authority-links" aria-label="Methods and resources"><a href="/calculation-methodology/">Calculation methodology</a><a href="/editorial-policy/">Editorial standards and corrections</a><a href="/founder/">Founder</a><a href="/resources/">Free resources</a></nav>;
const Section = ({title,children,id}) => <section id={id}><h2>{title}</h2>{children}</section>;
const Download = () => <a className="authority-button" href={worksheetFile} download onClick={()=>trackProductEvent('resource_download','cleaning')}>Download editable worksheet (.xlsx)</a>;
function Methodology(){return <>
  <p>Your selling price and the costs of delivering one sale determine its contribution. Monthly commitments determine how many sales you need. Available productive hours determine whether you can deliver them.</p>
  <Section title="Define the inputs before dividing"><dl><dt>Selling price</dt><dd>The revenue from one consistent job, appointment, order or client period. Keep the unit and tax treatment consistent.</dd><dt>Direct costs per sale</dt><dd>Materials, directly attributable labor, other variable delivery costs and the acquisition allowance you enter.</dd><dt>Monthly commitments</dt><dd>Operating overhead plus separately entered owner pay. Add target profit only when calculating a target beyond operating break-even. Do not count the same salary or expense in two fields.</dd></dl><p>Payment fees apply to the entered selling price. Include a flat per-transaction charge in another direct-cost field. Currency selection labels amounts; it does not convert exchange rates.</p></Section>
  <Section title="The core formulas" id="formulas"><div className="authority-formulas"><code>fee per sale = price × fee percentage ÷ 100</code><code>contribution = price − fees − materials − labor − other costs − acquisition allowance</code><code>monthly target = overhead + owner pay + target profit</code><code>exact sales = monthly target ÷ contribution</code><code>required whole sales = round exact sales upward</code><code>exact revenue = exact sales × price</code><code>practical revenue = required whole sales × price</code></div><p>If contribution is zero or negative, this model cannot calculate a finite sales target that funds monthly commitments. Change the cost mix or price before interpreting required sales. An acquisition allowance per sale is a simplified average; repeat-client and new-client economics may need separate scenarios.</p></Section>
  <Section title="Reproduce this monthly example"><p>Illustrative USD assumptions, not a customer result: price $100; materials $10; direct labor $8; other costs $2; acquisition allowance $0; payment fees 3%; overhead $2,500; owner pay $1,500; target profit $0.</p><table><caption>One consistent sale and monthly cost period</caption><thead><tr><th>Step</th><th>Result</th></tr></thead><tbody><tr><td>Fees: $100 × 3%</td><td>$3</td></tr><tr><td>Contribution: $100 − $3 − $10 − $8 − $2</td><td>$77</td></tr><tr><td>Monthly target: $2,500 + $1,500</td><td>$4,000</td></tr><tr><td>Exact sales: $4,000 ÷ $77</td><td>51.948…</td></tr><tr><td>Required whole sales</td><td>52</td></tr><tr><td>Exact / practical revenue</td><td>$5,194.81 / $5,200</td></tr></tbody></table><p>At 52 sales, contribution is $4,004. At 40 sales it is $3,080, leaving a $920 shortfall against these commitments. These figures exclude any cost you did not enter.</p></Section>
  <Section title="Check productive hours and customer demand"><div className="authority-formulas"><code>monthly capacity = workers × weekly hours × (52 ÷ 12) × utilization ÷ 100 ÷ worker-hours per sale</code><code>whole-sale capacity = round monthly capacity downward</code><code>practical inquiries = round (required whole sales ÷ conversion rate) upward</code></div><p>Hours per sale must be total worker-hours: two people working for two hours use four worker-hours. Weekly hours are per worker. Utilization reserves time for work outside delivery. Include editing, setup or travel consistently; do not subtract the same time twice.</p><p>Example: one worker × 30 weekly hours × 52/12 × 80% ÷ 2.6 worker-hours gives 40 sales per month. The target of 52 therefore exceeds capacity by 12 whole sales. At an assumed 25% inquiry-to-sale conversion, 52 sales need 208 inquiries. This is a planning assumption, not evidence those inquiries exist.</p></Section>
  <Section title="Why industry and small-tool results differ"><p>The eight industry calculators share the monthly contribution and capacity model, with different input labels and example values. A focused tool may answer a different question. The cleaning contract tool, for example, averages weekly visits using 52/12 and subtracts modeled labor, supplies, travel and entered contract overhead from the contract fee. Its assumptions do not automatically add payment fees, owner pay or acquisition costs. Read each tool's own formula and limits before comparing results.</p><p>Discount tools compare contribution before and after a discount. Cash-runway tools use entered cash flows, not accounting profit. The <a href="/resources/cleaning-job-cost-worksheet/">job-cost worksheet</a> compares one job before monthly overhead. Its contribution should not be labelled final business profit.</p></Section>
  <Section title="Precision, limits and review scope"><p>Core engine version {FORMULA_ENGINE_VERSION} uses decimal arithmetic at 40-digit precision before converting results for display. Currency normally displays two decimals. Required units round upward; capacity rounds downward. Near-zero positive contribution can produce a very large required volume; inspect the assumptions rather than treating that volume as a forecast.</p><p>The capacity indicator and planning score are formula-based summaries, not probabilities of success. Demand, booking patterns, inventory payment timing, debts, taxes, replacement equipment and seasonal peaks require separate consideration when not included in your inputs. Weekly averages do not represent every calendar month.</p><p>On October 10, 2026, the formulas on this page were compared with the core engine and the examples were recomputed. This is a calculation consistency check, not independent accounting certification. <a href="/editorial-policy/#corrections">Report a formula or content error</a>.</p></Section>
  <Section title="Reference and next step"><p>The <a href="https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs">U.S. Small Business Administration startup-cost guide</a> provides general context for identifying business costs. MyBreakeven's exact implementation is described above; the SBA has not endorsed this product.</p><p><a href="/calculator-walkthroughs/">Follow an interactive walkthrough</a>, then use the <a href="/#calculator">free business calculator</a> with your own costs.</p></Section>
</>}
function Editorial(){return <>
  <p>MyBreakeven publishes planning guides and calculators for small-business owners. The purpose is to help you inspect prices, costs and delivery capacity using assumptions you can change.</p>
  <Section title="Responsibility and attribution"><p><a href="/founder/">Anis Ul Haq</a> is the founder. MyBreakeven is the publisher of the site's guides. Publisher attribution does not mean every article was personally written or independently reviewed by the founder. An individual author or reviewer is named only when their contribution is recorded.</p><p>AI tools assist with drafting, editing and software work. A name, credential, testimonial or business outcome must not be invented to make the content appear more authoritative.</p></Section>
  <Section title="Sources and examples"><p>Worked scenarios use explicitly stated assumptions. They are not industry averages, customer results or forecasts unless the page provides evidence for that description. Source links support the associated claim; a general reference does not verify every number on a page.</p><p>Real business walkthroughs require the owner's permission, a defined period and traceable inputs. Anonymized publication must still have underlying records. Quotes and endorsements require permission and accurate attribution.</p></Section>
  <Section title="What a calculation check covers"><p>A calculation check compares the stated inputs, formula, units and arithmetic. It can also examine rounding and whether a worked target fits the stated capacity. It is different from a financial professional reviewing tax treatment, bookkeeping or a business's complete accounts.</p><p>A review date applies to the scope stated on that page. Publication date remains the original release date; substantive edits receive an updated date. Changes to navigation alone do not establish a fresh review of every worked example. No independent professional review is implied where none is named.</p></Section>
  <Section title="Corrections" id="corrections"><p>Email <a href="mailto:support@mybreakeven.com?subject=MyBreakeven%20calculation%20or%20content%20correction">support@mybreakeven.com</a> with the page URL, the statement or formula, expected result and steps to reproduce it. Use redacted or illustrative inputs; do not email customer names, account credentials or private financial records.</p><p>We assess the report against the stated assumptions and implementation. Confirmed calculation errors are corrected with an affected check and a dated note when the change materially alters the answer. Reports remain unverified until reproduced. We do not promise a response time or a resolution before examining the evidence.</p><p>Recent material correction: on October 10, 2026, the <a href="/blogs/salon-membership-pricing/">salon membership example</a> minimum was rounded upward to $89.70. At $89.69, a 3% fee and $42 cost leave $44.9993; $89.70 leaves $45.009 and meets the stated $45 contribution goal.</p></Section>
  <Section title="Commercial relationships and limits"><p>MyBreakeven offers Free and Pro plans. A sponsored contribution or affiliate arrangement must be disclosed beside the relevant content. Payment does not establish the accuracy of an example or permission to claim an endorsement.</p><p>Tools are planning estimates based on entered assumptions. They do not replace accounting, tax, legal or lending advice. See our <a href="/calculation-methodology/">calculation methods</a> and <a href="/contact-us/">contact options</a>.</p></Section>
</>}
function Founder(){return <>
  <p className="authority-role">Founder, MyBreakeven</p><p>Anis Ul Haq is the founder of MyBreakeven, a business planning website for owner-operators. Its calculators connect prices and direct costs with monthly commitments, customer demand and delivery capacity.</p>
  <Section title="The purpose of the product"><p>A sales target is more useful when you can inspect both the calculation and the work needed to deliver it. MyBreakeven lets owners change their own assumptions and see which constraint moves the answer.</p><p>The site publishes industry guides alongside its Free and Pro tools. Example inputs illustrate how a model works; they do not represent a verified market rate or a customer's achieved result.</p></Section>
  <Section title="Publishing responsibility"><p>MyBreakeven is identified as the publisher. Individual authorship or specialist review is credited when documented. This founder profile is not a claim of independent accounting certification or personal authorship of every article.</p><p>Read the <a href="/editorial-policy/">editorial and correction standards</a> and <a href="/calculation-methodology/">calculation methodology</a> to understand the process and limits.</p></Section>
  <Section title="Contact"><p>Product questions, partnerships and corrections: <a href="mailto:support@mybreakeven.com">support@mybreakeven.com</a>. Browse <a href="/resources/">free resources</a> before deciding whether a tool fits your question.</p></Section>
</>}
function Worksheet(){const e=exampleJobs.estimated,a=exampleJobs.actual;const contribution=j=>j.revenue-j.hours*j.wage-j.supplies-j.travel-j.other-j.revenue*j.fee/100;return <>
  <p>Compare the quote with the costs of the completed cleaning job. The workbook contains a blank Job sheet and a separate Example sheet. The example is illustrative, not a customer result.</p><Download />
  <Section title="Use it in five steps"><ol><li>Enter a job reference and currency label. Leave customer identities out of shared copies.</li><li>Enter the quoted revenue and estimated total paid crew-hours, loaded hourly cost, supplies, travel, other direct costs and payment-fee percentage.</li><li>After delivery, fill every matching actual input from your records. Enter zero when a cost genuinely does not apply.</li><li>Compare contribution and the actual-minus-estimate differences. A negative contribution difference means the job left less than estimated.</li><li>Use the actual cost per job when revising the next quote and your monthly plan.</li></ol></Section>
  <Section title="Inspect the illustrative example"><div className="authority-table"><table><caption>USD, one cleaning job; crew-hours include all paid workers</caption><thead><tr><th>Input or result</th><th>Estimate</th><th>Actual</th></tr></thead><tbody>{[['Revenue',money(e.revenue),money(a.revenue)],['Paid crew-hours',e.hours,a.hours],['Loaded cost per crew-hour',money(e.wage),money(a.wage)],['Labor cost',money(e.hours*e.wage),money(a.hours*a.wage)],['Supplies',money(e.supplies),money(a.supplies)],['Travel cost',money(e.travel),money(a.travel)],['Payment fees',money(7.2),money(7.2)],['Contribution before monthly overhead',money(contribution(e)),money(contribution(a))]].map(row=><tr key={row[0]}>{row.map((v,i)=>i===0?<th scope="row" key={i}>{v}</th>:<td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p>Actual contribution is $32 lower, from $110.80 to $78.80: $25 more labor, $3 more supplies and $4 more travel.</p></Section>
  <Section title="Scope and missing inputs"><p>Use one currency and consistent treatment of taxes in both columns. The currency label does not convert amounts. The hourly cost should include payroll burden you need to recover; also assign a cost to owner delivery time if applicable. Do not add that same labor cost again in another field.</p><p>Contribution is revenue less the direct costs entered. It still has to fund monthly overhead and any owner pay or profit goal outside these job costs. The worksheet does not forecast bookings, allocate monthly overhead, or assess taxes and cash collection timing. Required inputs remain visibly incomplete until entered, including explicit zeros.</p><p>Excel-compatible formulas calculate locally after download. Save your copy privately. <a href="/blogs/cleaning-estimate-vs-actual-job-cost/">Read the estimate-vs-actual job-cost guide</a>, then use the <a href="/calculators/cleaning-business-break-even-calculator/">cleaning business break-even calculator</a>.</p></Section>
</>}

export function Walkthroughs(){const [industry,setIndustry]=useState('cleaning');const [step,setStep]=useState(0);const p=demoPlans[industry],r=calculate(p);const url=industry==='cleaning'?'/calculators/cleaning-business-break-even-calculator/':'/calculators/agency-break-even-calculator/';return <>
  <p>These guided demonstrations use illustrative USD assumptions and the same core calculation engine as the monthly business calculator. They are not customer case studies or market benchmarks.</p><div className="authority-demo-controls"><label>Choose a model <select value={industry} onChange={e=>{setIndustry(e.target.value);setStep(0)}}><option value="cleaning">Cleaning job</option><option value="agency">Agency client-month</option></select></label><div role="group" aria-label="Walkthrough steps">{['Inputs','Contribution','Monthly target','Capacity and demand'].map((label,i)=><button key={label} aria-pressed={step===i} onClick={()=>{setStep(i);trackProductEvent('walkthrough_step',industry)}}>{i+1}. {label}</button>)}</div></div>
  <div className="authority-demo-result" aria-live="polite">{step===0?<><h2>1. Start with consistent inputs</h2><p>Price {money(p.price)} per {industry==='cleaning'?'job':'client-month'}. Materials {money(p.materialCost)}, direct labor {money(p.laborCost)}, other direct costs {money(p.otherVariableCost)}, acquisition allowance {money(p.acquisitionCost)}, payment fees {p.paymentFeePct}%.</p><p>Monthly overhead {money(p.fixedCosts)}, owner pay {money(p.ownerPay)}, target profit {money(p.targetProfit)}. One worker, {p.hoursPerWorker} hours per week, {p.utilizationPct}% delivery utilization, {p.hoursPerJob} worker-hours per sale, {p.conversionPct}% inquiry conversion.</p></>:step===1?<><h2>2. What one sale leaves</h2><p>{money(p.price)} − {money(p.price*p.paymentFeePct/100)} fees − {money(p.materialCost+p.laborCost+p.otherVariableCost+p.acquisitionCost)} other direct costs = <strong>{money(r.contribution)} contribution</strong>.</p><p>This funds monthly commitments; it is not final net profit.</p></>:step===2?<><h2>3. Convert commitments into whole sales</h2><p>{money(r.fixedNeed)} ÷ {money(r.contribution)} = {r.jobs.toFixed(4)} exact sales. Round upward to <strong>{r.wholeJobs} whole sales</strong>, generating {money(r.practicalRevenue)} revenue.</p><p>Do not round contribution first or treat fractional clients as completed work.</p></>:<><h2>4. Compare the target with capacity</h2><p>1 × 30 × 52/12 × 80% ÷ {p.hoursPerJob} = {r.capacity.toFixed(4)} sales of capacity. Round downward to <strong>{r.wholeCapacity} whole sales</strong>. The target needs {r.wholeJobs-r.wholeCapacity} more than that capacity.</p><p>At {p.conversionPct}% assumed conversion, {r.wholeJobs} sales require <strong>{r.practicalLeads} inquiries</strong>. The model does not prove demand exists. Revisit scope, productive time or contribution before accepting the target.</p></>}</div>
  <Section title="Watch the captured steps"><p>Two silent, 40-second demonstrations made from the live walkthrough screens. Each step stays visible for ten seconds. The interactive explanation above provides the same text and figures.</p><div className="authority-cards">{['cleaning','agency'].map(model=><section key={model}><h3>{model==='cleaning'?'Cleaning job':'Agency client-month'}</h3><video controls playsInline preload="none" style={{width:'100%'}} aria-label={`${model} captured calculation steps`}><source src={`/downloads/${model}-guided-demo.mp4`} type="video/mp4"/></video><p><a href={`/downloads/${model}-guided-demo.mp4`} download>Download the silent demonstration</a></p></section>)}</div></Section>
  <p><a className="authority-button" href={url} onClick={()=>trackProductEvent('walkthrough_calculator_click',industry)}>Run your own {industry} plan</a></p><Section title="Try the cost question separately"><p>For cleaning, use the <a href="/resources/cleaning-job-cost-worksheet/">estimate-vs-actual worksheet</a> to inspect one completed job. For agency work, compare the <a href="/blogs/agency-scope-creep-cost/">cost of additional scope</a> and <a href="/blogs/agency-client-profitability/">client contribution</a>. Keep actual records separate from the example assumptions above.</p></Section>
</>}
function Resources(){return <><p>Start with the resource that matches your decision. These materials are free and require no account.</p><div className="authority-cards"><section><h2>Compare a cleaning quote with actual costs</h2><p>A blank editable job worksheet, separate illustrative example and instructions on crew-hours, fees and contribution.</p><a href="/resources/cleaning-job-cost-worksheet/">Open the worksheet guide</a></section><section><h2>Follow a monthly calculation</h2><p>Step through cleaning and agency examples from cost inputs to required whole sales and capacity.</p><a href="/calculator-walkthroughs/">Try the guided demonstrations</a></section><section><h2>Verify the method</h2><p>Definitions, formulas, rounding rules, core engine version and limitations you can inspect.</p><a href="/calculation-methodology/">Read the calculation methodology</a></section></div><Section title="Using or referencing these resources"><p>You may link to the original resource page and use the worksheet for your own business planning. Cite MyBreakeven and the resource URL when referencing its worked example. Do not present the example as a verified customer outcome or imply our endorsement of your product. Contact <a href="mailto:support@mybreakeven.com">support@mybreakeven.com</a> about republication or adaptations.</p><p>Read our <a href="/editorial-policy/">editorial and correction standards</a> or explore the <a href="/tools/">free calculators</a>.</p></Section></>}
export default function AuthorityPage({path}){const route=path.replace(/^\//,'');const meta=authorityPages[route];const components={'calculation-methodology':Methodology,'editorial-policy':Editorial,founder:Founder,resources:Resources,'resources/cleaning-job-cost-worksheet':Worksheet,'calculator-walkthroughs':Walkthroughs};const Content=components[route];if(!Content)return null;return <article className="authority-page"><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/resources/">Resources</a>{route!=='resources'&&<> / {meta[2]}</>}</nav><header><span>MYBREAKEVEN</span><h1>{meta[2]}</h1><p className="authority-date">Published <time dateTime="2026-10-10">October 10, 2026</time></p></header><Content/><ReferenceLinks/></article>}
