const makeArticle = (data) => ({
  ...data,
  image: `/images/blog/${data.calculatorSlug.replace("-break-even-calculator", "")}-featured.svg`,
  alt: `${data.name} break-even dashboard showing revenue, required ${data.unit}, operating capacity and customer demand`,
  insideImage: `/images/blog/${data.calculatorSlug.replace("-break-even-calculator", "")}-formula.svg`,
  insideAlt: `${data.name} break-even formula from price and variable costs to contribution, required ${data.unit} and capacity`,
  description: `${data.description} Learn the inputs, formula, features, capacity checks and practical steps for using the free MyBreakeven calculator.`,
  features: [
    `Exact ${data.unit} and revenue targets without hiding fractional results`,
    `A separate whole-${data.singular} operating target for real-world planning`,
    `Contribution margin after ${data.variableSummary}`,
    `Required customer inquiries based on your conversion rate`,
    `Team-capacity and feasibility comparison using productive hours`,
    `Price sensitivity, cost-drift scenarios and a transparent formula trace`,
  ],
  sections: [
    { heading: `What the ${data.name} calculator calculates`, paragraphs: [`The calculator connects unit economics, monthly financial needs, customer demand and operating capacity. It first finds contribution per ${data.singular}, then calculates the exact ${data.unit} and revenue required to cover overhead, owner pay and optional target profit. It also shows the rounded-up operating target, required inquiries and whether the team has enough productive capacity.`] },
    { heading: `Inputs to gather before you start`, paragraphs: [`Use recent, representative figures instead of best-case estimates. Enter ${data.inputSummary}. Keep fixed monthly overhead separate from costs that rise with each ${data.singular}. If a cost applies to every sale, include it in the per-${data.singular} fields.`], bullets: data.inputs },
    { heading: `The break-even formula`, paragraphs: [`Contribution per ${data.singular} = average price − payment fees − direct materials − direct labor − other variable costs − acquisition cost. Required ${data.unit} = (monthly overhead + owner pay + target profit) ÷ contribution per ${data.singular}. Exact break-even revenue = required ${data.unit} × average price. MyBreakeven keeps the exact fractional result and displays the next whole ${data.singular} separately.`] },
    { heading: `How to use the calculator step by step`, bullets: [`Select ${data.name} from the industry list.`, `Choose the currency used by your records; the tool labels values but does not convert exchange rates.`, `Enter price and every direct cost per ${data.singular}.`, `Add monthly overhead, owner pay and optional target profit.`, `Enter team hours, delivery time, productive utilization and inquiry conversion rate.`, `Review exact and whole-unit targets, contribution margin, required inquiries and the capacity gap.`, `Compare conservative and optimized scenarios before making a pricing or spending decision.`] },
    { heading: `Worked ${data.name.toLowerCase()} example`, paragraphs: [`Using the example assumptions—${data.exampleInputs}—contribution is ${data.contribution} per ${data.singular}. The exact target is ${data.exactUnits} ${data.unit} and ${data.exactRevenue} revenue. Because a fraction of a ${data.singular} normally cannot be sold, the practical target is ${data.wholeUnits} ${data.unit}, or ${data.practicalRevenue}. Estimated capacity is ${data.capacity} ${data.unit}; required inquiries are ${data.inquiries} at the example conversion rate. This example explains the calculation only and is not an industry benchmark.`] },
    { heading: `How to interpret feasibility`, paragraphs: [`A break-even target can be mathematically correct but operationally impossible. Compare required ${data.unit} with realistic productive capacity after setup, travel, administration, gaps and rework. A negative capacity gap means the current team cannot deliver the target under the assumptions entered. Test price, service mix, variable costs, utilization or staffing one change at a time.`] },
    { heading: `Common mistakes to avoid`, bullets: data.mistakes },
    { heading: `Ways to improve the result`, paragraphs: [`Focus on the assumptions with the largest verified effect rather than changing every input at once. ${data.improvement} Recalculate after each change and preserve a conservative scenario so the plan does not depend on perfect conditions.`] },
  ],
  faq: [
    { q: `What does the ${data.name} break-even calculator include?`, a: `It includes price, direct costs, payment fees, acquisition cost, monthly overhead, owner pay, target profit, required ${data.unit}, inquiries and productive capacity.` },
    { q: `Why are exact and whole ${data.unit} different?`, a: `The exact result preserves the mathematical fraction. The whole-unit target rounds up because selling only part of a ${data.singular} is usually not operationally possible.` },
    { q: `Does the calculator predict guaranteed profit?`, a: `No. It produces an assumption-based planning estimate. Actual sales, costs, cancellations, taxes and timing can differ.` },
    { q: `How often should the calculation be updated?`, a: `Update it whenever price, wages, supplier costs, advertising performance, overhead or team capacity changes materially, and review it at least monthly during active planning.` },
  ],
});

export const articles = {
  "cleaning-business-break-even": makeArticle({tag:"Cleaning",name:"Cleaning business",singular:"job",unit:"jobs",calculatorSlug:"cleaning-business-break-even-calculator",title:"Cleaning Business Break-Even Calculator: Jobs, Revenue, Leads and Capacity",description:"Calculate the monthly cleaning jobs and revenue needed to break even after labor, supplies, travel and marketing costs.",variableSummary:"supplies, cleaner labor, travel, equipment use, card fees and lead generation",inputSummary:"average job price, supplies, direct cleaner labor, travel and equipment use, marketing cost per booked job, monthly overhead and team capacity",inputs:["Average price per cleaning job","Cleaning supplies and direct labor per job","Travel, laundry or equipment use per job","Lead-generation cost and card fees","Rent, software, insurance, vehicles and other monthly overhead","Cleaner count, weekly hours, job duration, utilization and booking conversion"],exampleInputs:"$180 per job, $98.22 total variable cost and $8,700 monthly financial need",contribution:"$76.78",exactUnits:"113.31",wholeUnits:"114",exactRevenue:"$20,395.94",practicalRevenue:"$20,520",capacity:"97.50",inquiries:"377.70",mistakes:["Treating all cleaner payroll as fixed when labor changes by job","Omitting travel time, laundry, supplies or equipment wear","Using total leads instead of qualified booking inquiries","Assuming every paid hour is available for billable cleaning"],improvement:"Review route density, job minimums, recurring-client mix, cleaner utilization, supply control and quote-to-booking conversion."}),
  "landscaping-break-even": makeArticle({tag:"Landscaping",name:"Landscaping business",singular:"job",unit:"jobs",calculatorSlug:"landscaping-break-even-calculator",title:"Landscaping Break-Even Calculator: Job Pricing, Crew Capacity and Leads",description:"Estimate landscaping and lawn-care break-even revenue using labor, materials, fuel, equipment and realistic crew capacity.",variableSummary:"materials, field labor, fuel, equipment use, fees and lead generation",inputSummary:"average job price, materials, field labor, fuel and equipment use, sales cost, fixed overhead and productive crew hours",inputs:["Average landscaping or lawn-care job price","Plants, materials and direct field labor","Fuel, disposal and equipment use per job","Sales or lead cost per booked job","Vehicles, rent, insurance, software and monthly equipment costs","Crew size, weekly hours, job duration, utilization and close rate"],exampleInputs:"$320 per job, $209.28 total variable cost and $11,300 monthly financial need",contribution:"$110.72",exactUnits:"102.06",wholeUnits:"103",exactRevenue:"$32,658.96",practicalRevenue:"$32,960",capacity:"94.85",inquiries:"364.50",mistakes:["Ignoring seasonal downtime and weather disruption","Leaving fuel, disposal or equipment wear out of job cost","Using crew clock hours as fully productive hours","Mixing one-time installation jobs with recurring maintenance without a weighted average"],improvement:"Improve route density, minimum visit pricing, crew scheduling, maintenance-plan mix and material markups supported by actual costs."}),
  "photography-business-break-even": makeArticle({tag:"Photography",name:"Photography business",singular:"session",unit:"sessions",calculatorSlug:"photography-business-break-even-calculator",title:"Photography Business Break-Even Calculator: Sessions, Pricing and Capacity",description:"Find the photography sessions, revenue and inquiries required after shooting, editing, travel, studio and marketing costs.",variableSummary:"editing, delivery, travel, direct labor, payment fees and booking acquisition",inputSummary:"average session value, direct shooting and editing costs, travel, gallery delivery, booking cost, fixed overhead and available production hours",inputs:["Weighted average session or project price","Direct shooting and assistant labor","Editing, gallery, album and travel cost per session","Marketing cost per confirmed booking and payment fees","Studio, insurance, subscriptions and equipment overhead","Photographer hours, full delivery time, utilization and inquiry conversion"],exampleInputs:"$650 per session, $273.85 total variable cost and $9,100 monthly financial need",contribution:"$376.15",exactUnits:"24.19",wholeUnits:"25",exactRevenue:"$15,725.11",practicalRevenue:"$16,250",capacity:"23.57",inquiries:"109.97",mistakes:["Counting shooting time but not editing and delivery time","Ignoring album, gallery, travel or assistant costs","Using the highest package price instead of a weighted average sale","Overestimating booking conversion from unqualified inquiries"],improvement:"Test package mix, minimum booking values, editing workflow, upsells, scheduling density and lead-source quality."}),
  "agency-break-even": makeArticle({tag:"Agency & Freelancer",name:"Agency or freelancer",singular:"client",unit:"clients",calculatorSlug:"agency-break-even-calculator",title:"Agency Break-Even Calculator: Retainer Clients, Revenue and Delivery Capacity",description:"Calculate the retainer clients and revenue an agency or freelancer needs after delivery labor, contractors, software and sales costs.",variableSummary:"delivery labor, contractors, client software, processing fees and sales acquisition",inputSummary:"average monthly client value, delivery payroll, contractors, client-specific tools, sales cost, monthly overhead and team delivery capacity",inputs:["Average monthly retainer or client value","Direct team labor and contractor cost per client","Client-specific software and fulfillment expense","Sales cost per acquired client and payment fees","Core payroll, rent, software and administrative overhead","Delivery team hours, hours required per client, utilization and close rate"],exampleInputs:"$2,200 per client, $1,283.80 total variable cost and $15,200 monthly financial need",contribution:"$916.20",exactUnits:"16.59",wholeUnits:"17",exactRevenue:"$36,498.58",practicalRevenue:"$37,400",capacity:"17.69",inquiries:"82.95",mistakes:["Treating all staff cost as fixed when delivery effort scales by client","Ignoring scope creep and non-billable communication time","Using contract value instead of monthly recognized revenue","Assuming every sales conversation is a qualified opportunity"],improvement:"Improve scope control, retainer packaging, delivery templates, team utilization, client profitability reviews and qualified close rate."}),
  "mobile-detailing-break-even": makeArticle({tag:"Mobile Detailing",name:"Mobile detailing business",singular:"job",unit:"jobs",calculatorSlug:"mobile-detailing-break-even-calculator",title:"Mobile Detailing Break-Even Calculator: Jobs, Routes, Revenue and Leads",description:"Calculate detailing jobs and revenue required after chemicals, technician labor, travel, equipment and customer acquisition.",variableSummary:"chemicals, technician labor, travel, water, equipment use, fees and lead generation",inputSummary:"average ticket, chemicals, technician labor, travel and equipment use, booking cost, monthly overhead and mobile-team capacity",inputs:["Average detailing ticket based on service mix","Chemicals, towels and direct technician labor","Fuel, water and equipment use per job","Lead cost per completed booking and card fees","Vehicle, insurance, storage, software and equipment overhead","Technician count, weekly hours, full job time, utilization and booking conversion"],exampleInputs:"$240 per job, $138.96 total variable cost and $8,500 monthly financial need",contribution:"$101.04",exactUnits:"84.13",wholeUnits:"85",exactRevenue:"$20,190.02",practicalRevenue:"$20,400",capacity:"85.41",inquiries:"262.89",mistakes:["Leaving drive and setup time out of delivery hours","Ignoring water, fuel, towels or equipment replacement","Using booked appointments without allowing for cancellations","Combining basic and premium services without a weighted average ticket"],improvement:"Improve route grouping, deposits, minimum mobile-service prices, package mix, rebooking and technician setup time."}),
  "ecommerce-break-even": makeArticle({tag:"E-commerce",name:"E-commerce store",singular:"order",unit:"orders",calculatorSlug:"ecommerce-break-even-calculator",title:"E-commerce Break-Even Calculator: Orders, COGS, Returns, Shipping and Ads",description:"Calculate online-store break-even orders and revenue after COGS, fulfillment, shipping, returns, platform fees and advertising.",variableSummary:"COGS, fulfillment, shipping subsidy, returns, platform fees and acquisition",inputSummary:"average order value, product cost, fulfillment labor, shipping subsidy, returns allowance, customer acquisition cost, overhead and fulfillment capacity",inputs:["Weighted average order value","COGS and fulfillment labor per order","Shipping subsidy and expected returns allowance","Customer acquisition cost and payment/platform fees","Subscriptions, payroll, warehouse and other monthly overhead","Fulfillment team hours, handling time, utilization and store conversion rate"],exampleInputs:"$86 per order, $60.75 total variable cost and $14,800 monthly financial need",contribution:"$25.25",exactUnits:"586.19",wholeUnits:"587",exactRevenue:"$50,411.91",practicalRevenue:"$50,482",capacity:"1,267.50",inquiries:"20,935.18",mistakes:["Using gross margin before payment fees, returns and shipping subsidy","Mixing site visitors with qualified inquiries without defining the conversion denominator","Using blended ad spend without matching it to acquired orders","Ignoring fulfillment constraints during promotion periods"],improvement:"Test product mix, bundles, shipping thresholds, return reduction, payment costs, conversion rate and customer acquisition by channel."}),
  "restaurant-break-even": makeArticle({tag:"Restaurant",name:"Restaurant",singular:"order",unit:"orders",calculatorSlug:"restaurant-break-even-calculator",title:"Restaurant Break-Even Calculator: Revenue, Orders, Food Cost and Capacity",description:"Calculate restaurant break-even revenue and order volume after food, direct labor, packaging, delivery commissions and promotion.",variableSummary:"food, direct preparation labor, packaging, delivery commissions, payment fees and promotion",inputSummary:"average check, ingredients, direct order labor, packaging, delivery commission, promotion cost, overhead and kitchen capacity",inputs:["Weighted average check or order value","Food ingredients and direct preparation labor","Packaging and delivery commission per order","Promotion cost per completed order and payment fees","Rent, management payroll, utilities and fixed overhead","Kitchen/service hours, order handling time, utilization and conversion"],exampleInputs:"$34 per order, $23.59 total variable cost and $33,500 monthly financial need",contribution:"$10.41",exactUnits:"3,218.06",wholeUnits:"3,219",exactRevenue:"$109,414.02",practicalRevenue:"$109,446",capacity:"2,852.57",inquiries:"7,151.24",mistakes:["Using menu price without weighting dine-in, pickup and delivery mix","Ignoring delivery commission, packaging or waste allowance","Dividing monthly orders by 30 instead of actual operating days","Assuming kitchen throughput is identical during every daypart"],improvement:"Review menu contribution, food waste, labor scheduling, delivery-channel mix, average check and realistic daypart capacity."}),
  "salon-break-even": makeArticle({tag:"Salon",name:"Salon",singular:"appointment",unit:"appointments",calculatorSlug:"salon-break-even-calculator",title:"Salon Break-Even Calculator: Appointments, Service Mix and Stylist Capacity",description:"Find salon break-even appointments and revenue after products, stylist labor, laundry, disposables, fees and marketing.",variableSummary:"product usage, stylist labor, laundry, disposables, fees and booking acquisition",inputSummary:"weighted appointment value, product use, stylist labor, laundry and disposables, booking cost, overhead and productive stylist hours",inputs:["Weighted average appointment value across services","Product usage and direct stylist labor per appointment","Laundry, disposables and other service-level costs","Marketing cost per completed booking and payment fees","Rent, reception, utilities, software and monthly overhead","Stylist hours, average appointment duration, utilization and booking conversion"],exampleInputs:"$92 per appointment, $54.76 total variable cost and $15,800 monthly financial need",contribution:"$37.24",exactUnits:"424.27",wholeUnits:"425",exactRevenue:"$39,033.30",practicalRevenue:"$39,100",capacity:"399.90",inquiries:"1,116.51",mistakes:["Using a headline service price instead of a weighted service mix","Ignoring product usage, commission, laundry or booking fees","Treating all scheduled hours as sellable appointment time","Leaving cancellations and gaps out of utilization assumptions"],improvement:"Test rebooking, deposits, service mix, price adjustments, retail add-ons, product control and stylist scheduling."}),
};

export const articleList = Object.entries(articles).map(([slug, article]) => ({slug, ...article}));
