import React, { useEffect, useState } from "react";
import { builtFields, calculateBuiltCosts, costProfiles, otherLabels, seedCostDraft } from "./costBuilder";
import "./cost-builder.css";

export default function CostBuilder({ industryKey, input, currency = "USD", onApply }) {
  const profile = costProfiles[industryKey];
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState(() => seedCostDraft(industryKey, input));
  const [message, setMessage] = useState("");
  useEffect(() => {
    const saved = input.costBuilder;
    const savedResult = saved?.industryKey === industryKey && calculateBuiltCosts(industryKey, saved.draft);
    setDraft(savedResult?.valid && builtFields.every(key => Number(input[key]) === savedResult.patch[key]) ? saved.draft : seedCostDraft(industryKey, input));
    setMessage("");
  }, [industryKey, input.costBuilder, ...builtFields.map(key => input[key])]);
  const result = calculateBuiltCosts(industryKey, draft);
  const money = value => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);
  const update = (key, value) => { setDraft(current => ({ ...current, [key]: value })); setMessage(""); };
  const amountField = (label, value, onChange, suffix = currency, help = "") => <label><span>{label}</span><div className="cost-builder-control"><input aria-label={label} type="number" inputMode="decimal" min="0" step="any" value={value} onChange={event => { onChange(event.target.value); setMessage(""); }} aria-invalid={value === "" || Number(value) < 0} /><small>{suffix}</small></div>{help && <small className="cost-builder-field-help">{help}</small>}</label>;
  const expenseHelp = label => {
    if (/returns/i.test(label)) return "Average the unrecovered return cost across all orders: 10% returns × $20 lost = $2 per order.";
    if (/waste allowance/i.test(label)) return "Add waste only if it is not already included in your material cost.";
    if (/commission/i.test(label)) return "Enter this fee here or in payment/platform fees, once.";
    if (/shipping/i.test(label)) return "Your shipping cost minus any shipping amount paid by the customer.";
    if (/equipment/i.test(label)) return "Usage cost for this job. Keep fixed monthly equipment bills in overhead.";
    if (/Travel|fuel/i.test(label)) return "Money spent on this sale’s trip. Working travel time goes in labor and delivery time.";
    return `Amount used for one ${profile.unit}. Enter 0 if it does not apply.`;
  };
  const listFields = (labels, key) => labels.map((label, index) => <React.Fragment key={label}>{amountField(label, draft[key][index], value => setDraft(current => ({ ...current, [key]: current[key].map((amount, i) => i === index ? value : amount) })), currency, expenseHelp(label))}</React.Fragment>);
  const sameAsApplied = input.costBuilder?.industryKey === industryKey && JSON.stringify(input.costBuilder.draft) === JSON.stringify(draft) && result.valid && builtFields.every(key => Number(input[key]) === result.patch[key]);
  return <section className="cost-builder" aria-label={`${profile.unit} cost builder`}>
    <button type="button" className="cost-builder-toggle" aria-expanded={open} onClick={() => setOpen(current => !current)}><span><strong>Build my costs</strong><small>Optional · work out the cost of one {profile.unit}</small></span><b aria-hidden="true">{open ? "−" : "+"}</b></button>
    {open && <div className="cost-builder-body">
      <p><strong>What does one {profile.unit} cost you to deliver?</strong> Add the expenses below to find out. Use 0 for anything you do not pay for.</p><p className="cost-builder-notice">You are editing a preview. Your results change only when you choose <strong>Use these costs</strong>.</p>
      <label className="cost-builder-service"><span>What are you costing?</span><select value={draft.service} onChange={event => { setDraft(seedCostDraft(industryKey, input, Number(event.target.value))); setMessage(""); }}>{profile.services.map((service, index) => <option value={index} key={service}>{service}</option>)}</select></label>
      <details className="cost-builder-help"><summary>Help for your {profile.unit}</summary><p className="cost-builder-hint">{profile.context}</p><p className="cost-builder-hint">Changing the service starts a new preview from your current calculator totals. It does not load market prices or change your results.</p></details>
      <p className="cost-builder-hint">To get you started, your current materials and other-expense totals are placed in the first row of each group. These are totals to split, not estimates for those individual items. Replace them with your own breakdown, or start with zero costs.</p><button type="button" className="cost-builder-zero" onClick={() => { const fresh = seedCostDraft(industryKey, { materialCost: 0, laborCost: 0, otherVariableCost: 0, hoursPerJob: 0 }, draft.service); setDraft(fresh); setMessage("Preview cleared. Enter your expenses and working hours. Your calculator results have not changed."); }}>Start with zero costs</button>
      <details open><summary>1. Materials / products{result.valid && <small>{money(result.patch.materialCost)}</small>}</summary><p className="cost-builder-hint">Enter what you use for one {profile.unit}, not what you buy for the whole month.</p><div className="cost-builder-fields">{listFields(profile.materials, "materials")}</div></details>
      <details><summary>2. Labor and delivery time{result.valid && <small>{money(result.patch.laborCost)}</small>}</summary><p className="cost-builder-hint">Add working time for everyone involved. For example, 2 people working 2 hours each = 4 total team-hours.</p><div className="cost-builder-fields">
        <label><span>How would you like to enter labor cost?</span><select value={draft.laborMode} onChange={event => update("laborMode", event.target.value)}><option value="total">Enter the total labor cost</option><option value="hourly">Calculate hours × hourly pay</option></select></label>
        {draft.laborMode === "total" ? <>{amountField(`Direct pay per ${profile.unit}`, draft.laborTotal, value => update("laborTotal", value), currency, "Pay for this one sale. Leave out wages already included in monthly overhead or owner pay.")}{amountField(`Total team-hours per ${profile.unit}`, draft.deliveryHours, value => update("deliveryHours", value), "hours", "Add each person’s working hours, including your own. Include preparation and travel used to deliver this sale.")}</> : profile.roles.map((role, index) => <fieldset key={role}><legend>{role}</legend>{amountField(`${role}: total team-hours`, draft.roles[index].hours, value => setDraft(current => ({ ...current, roles: current.roles.map((r, i) => i === index ? { ...r, hours: value } : r) })), "hours")}{amountField(`${role}: hourly pay`, draft.roles[index].rate, value => setDraft(current => ({ ...current, roles: current.roles.map((r, i) => i === index ? { ...r, rate: value } : r) })), `${currency}/hour`, "Use 0 if this person’s pay is already covered in overhead or monthly owner pay.")}{draft.laborMode === "hourly" && <small className="cost-builder-field-help">{Number.isFinite(Number(draft.roles[index].hours) * Number(draft.roles[index].rate)) ? `${draft.roles[index].hours || 0} hours × ${money(draft.roles[index].rate || 0)}/hour = ${money(Number(draft.roles[index].hours) * Number(draft.roles[index].rate))}` : "Check hours and hourly pay."}</small>}</fieldset>)}
      </div><p className="cost-builder-hint">Hours × hourly pay replaces the direct-pay total with hours × pay; it does not add to it. Count every person's hours, including your own. For owner time paid through monthly owner pay, use 0 hourly pay here. Keep fixed payroll in overhead if already included there.</p></details>
      <details><summary>3. Other expenses{result.valid && <small>{money(result.patch.otherVariableCost)}</small>}</summary><p className="cost-builder-hint">Include expenses caused by this one {profile.unit}. Keep monthly bills in the main calculator.</p><div className="cost-builder-fields">{listFields(otherLabels(profile, draft.service), "other")}</div></details>
      <div className="cost-builder-preview" aria-live="polite">{result.valid ? <><strong>Direct cost for one {profile.unit}: {money(result.total)}</strong><span>{money(result.patch.materialCost)} materials + {money(result.patch.laborCost)} labor + {money(result.patch.otherVariableCost)} other expenses = {money(result.total)}</span><span>Working time: {Number(result.patch.hoursPerJob.toFixed(4))} total team-hours per {profile.unit}</span><small>This is not your full break-even cost or selling price. The calculator adds customer acquisition and percentage fees separately, then accounts for monthly overhead, owner pay and your profit goal.</small>
        <div className="cost-builder-comparison"><strong>What will change when you apply?</strong><table><caption className="sr-only">Current calculator values and your new cost preview</caption><thead><tr><th scope="col">Calculator input</th><th scope="col">Current</th><th scope="col">New</th></tr></thead><tbody>{[["Materials", "materialCost"], ["Direct labor", "laborCost"], ["Other expenses", "otherVariableCost"], ["Team-hours", "hoursPerJob"]].map(([label, key]) => <tr key={key}><th scope="row">{label}</th><td>{key === "hoursPerJob" ? `${Number(input[key])} hrs` : money(input[key])}</td><td>{key === "hoursPerJob" ? `${Number(result.patch[key].toFixed(4))} hrs` : money(result.patch[key])}</td></tr>)}</tbody></table><small>These new totals replace the four inputs above. They are not added on top. Profit, required sales and capacity recalculate; Pro pricing suggestions use the new costs too.</small></div>
      </> : <p role="alert">{result.message}</p>}</div>
      <div className="cost-builder-actions"><button type="button" disabled={!result.valid || sameAsApplied} onClick={() => { onApply({ ...result.patch, costBuilder: { industryKey, draft } }); setMessage("Applied. Materials, labor, other expenses and team-hours have been replaced. Your results now use these costs."); }}>{sameAsApplied ? "Costs applied" : "Use these costs"}</button><button type="button" onClick={() => { setDraft(seedCostDraft(industryKey, input, draft.service)); setMessage("Draft rebuilt from the current calculator totals. Results have not changed."); }}>Restore current calculator totals</button></div>
      <p className="cost-builder-status" role="status">{message || (sameAsApplied ? "Costs applied. Results use this breakdown." : "Preview only. Your calculator results have not changed.")}</p>
    </div>}
  </section>;
}
