import React,{useId,useMemo,useState} from 'react';
import {CURRENCIES} from './currencies';
const markets={USD:'United States USA',GBP:'United Kingdom UK',EUR:'Euro area Germany France Italy Spain Netherlands Ireland Austria Belgium Finland Portugal Greece Luxembourg Estonia Latvia Lithuania Slovakia Slovenia Croatia Cyprus Malta Bulgaria',CAD:'Canada',AUD:'Australia',NZD:'New Zealand',CHF:'Switzerland Liechtenstein',JPY:'Japan',SGD:'Singapore',HKD:'Hong Kong',KRW:'South Korea',TWD:'Taiwan',NOK:'Norway',SEK:'Sweden',DKK:'Denmark',ISK:'Iceland',PLN:'Poland',CZK:'Czechia Czech Republic',HUF:'Hungary',RON:'Romania',AED:'United Arab Emirates UAE',SAR:'Saudi Arabia',QAR:'Qatar',KWD:'Kuwait',BHD:'Bahrain',OMR:'Oman',ILS:'Israel',TRY:'Türkiye Turkey',ZAR:'South Africa',MXN:'Mexico',BRL:'Brazil',CLP:'Chile',COP:'Colombia',PEN:'Peru',ARS:'Argentina',UYU:'Uruguay',CNY:'China',INR:'India',PKR:'Pakistan',BDT:'Bangladesh',LKR:'Sri Lanka',NPR:'Nepal',IDR:'Indonesia',MYR:'Malaysia',THB:'Thailand',VND:'Vietnam',PHP:'Philippines',EGP:'Egypt',MAD:'Morocco',KES:'Kenya',NGN:'Nigeria',UAH:'Ukraine',RSD:'Serbia',GEL:'Georgia',AMD:'Armenia',KZT:'Kazakhstan',XCG:'Curaçao Sint Maarten',ZWG:'Zimbabwe'};
export const currencyOptions=CURRENCIES.map(({code,name,countries})=>({code,label:`${code} — ${name}`,search:`${code} ${name} ${countries.join(' ')} ${markets[code]||''}`.toLowerCase()}));
export default function CurrencySelector({value,onChange}){
 const id=useId(),[query,setQuery]=useState('');
 const filtered=useMemo(()=>currencyOptions.filter(c=>c.search.includes(query.trim().toLowerCase())),[query]);
 const options=filtered.some(c=>c.code===value)?filtered:[currencyOptions.find(c=>c.code===value),...filtered];
 return <div className="tool-field"><label htmlFor={`${id}-search`}>Find currency</label><input id={`${id}-search`} type="search" placeholder="Search country, currency or code" value={query} onChange={e=>setQuery(e.target.value)} aria-describedby={`${id}-matches`}/><small id={`${id}-matches`} role="status">{query?`${filtered.length} matching currencies. Your selection stays until you choose another.`:`${currencyOptions.length} currencies available.`}</small><label htmlFor={`${id}-currency`}>Currency</label><select id={`${id}-currency`} value={value} onChange={e=>onChange(e.target.value)}>{options.map(c=><option key={c.code} value={c.code}>{c.label}</option>)}</select><small>Changes currency labels only; amounts are not converted. Enter all amounts in the selected currency.</small></div>;
}
