import{describe,expect,it}from'vitest';import{calculate}from'./engine';import{industries}from'./industries';
const base={price:100,materialCost:10,laborCost:30,fixedCosts:1000,ownerPay:0,targetProfit:0,paymentFeePct:0,workers:1,hoursPerWorker:40,hoursPerJob:2,utilizationPct:100,conversionPct:25};
describe('calculation engine',()=>{it('retains exact fractional units and separates practical whole units',()=>{const r=calculate(base);expect(r.contribution).toBe(60);expect(r.jobs).toBeCloseTo(16.6666666667,9);expect(r.wholeJobs).toBe(17);expect(r.revenue).toBeCloseTo(1666.6666666667,9);expect(r.leads).toBeCloseTo(66.6666666667,9);expect(r.wholeLeads).toBe(67)});it('uses 52/12 weeks for exact monthly capacity',()=>{expect(calculate(base).capacity).toBeCloseTo(86.6666666667,9)});it('rejects non-positive contribution',()=>{expect(calculate({...base,price:40}).valid).toBe(false)});it('rejects empty and invalid percentages',()=>{expect(calculate({...base,price:''}).inputError).toBe(true);expect(calculate({...base,conversionPct:101}).inputError).toBe(true)});it('higher fixed costs never reduce jobs',()=>{expect(calculate({...base,fixedCosts:2000}).jobs).toBeGreaterThan(calculate(base).jobs)})});
describe('decimal precision and boundaries',()=>{
  it('avoids binary floating-point drift in contribution arithmetic',()=>{const r=calculate({...base,price:'0.30',materialCost:'0.10',laborCost:'0.10',fixedCosts:'0.10'});expect(r.contribution).toBe(0.1);expect(r.jobs).toBe(1);expect(r.revenue).toBe(0.3)});
  it('accepts precise decimal strings without rounding intermediate values',()=>{const r=calculate({...base,price:'123.4567',materialCost:'12.3456',laborCost:'34.5678',paymentFeePct:'2.975',fixedCosts:'9876.5432'});expect(r.valid).toBe(true);expect(r.jobs*r.contribution).toBeCloseTo(r.fixedNeed,9)});
  it('rejects zero conversion with a clear input error',()=>{const r=calculate({...base,conversionPct:0});expect(r.valid).toBe(false);expect(r.inputError).toBe(true)});
  it('keeps exact and operational revenue separate',()=>{const r=calculate(base);expect(r.practicalRevenue).toBe(r.wholeJobs*base.price);expect(r.practicalRevenue).toBeGreaterThan(r.revenue)});
  it('does not allow utilization above one hundred percent',()=>{expect(calculate({...base,utilizationPct:'100.01'}).inputError).toBe(true)});
});
describe('locked industry models',()=>{for(const [key,model] of Object.entries(industries))it(key+' produces exact, internally consistent results',()=>{const r=calculate(model.values);expect(r.valid).toBe(true);expect(r.jobs).toBeGreaterThan(0);expect(r.capacity).toBeGreaterThan(0);expect(r.revenue).toBeCloseTo(r.jobs*model.values.price,9);expect(r.jobs*r.contribution).toBeCloseTo(r.fixedNeed,9);expect(r.wholeJobs).toBe(Math.ceil(r.jobs));expect(r.wholeLeads).toBe(Math.ceil(r.leads));expect(r.scenarios).toHaveLength(3)})});
