import React from 'react';
import { freeTools } from './freeTools';
export default function FreeToolGuide({tool,slug}){
 const sibling=Object.entries(freeTools).find(([key])=>key!==slug);
 return <article className="tool-method" id="tool-guide" aria-label={`${tool.name} guide`}>
 <section id="features"><h2>What this calculator includes</h2><ul>{tool.features.map(feature=><li key={feature}>{feature}</li>)}</ul></section>
 {tool.sections.map(section=><section key={section.id} id={section.id}><h2>{section.title}</h2>{section.paragraphs?.map(p=><p key={p}>{p}</p>)}{section.steps&&<ol>{section.steps.map(step=><li key={step}>{step}</li>)}</ol>}{section.table&&<div className="tool-table-wrap"><table><caption>Illustrative scenarios using unrounded contribution values</caption><thead><tr>{section.table.headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{section.table.rows.map(row=><tr key={row[0]}>{row.map((cell,i)=>i===0?<th scope="row" key={i}>{cell}</th>:<td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>}{section.after?.map(p=><p key={p}>{p}</p>)}</section>)}
 <section id="assumptions"><h2>Assumptions and limits</h2><p>This compares one consistent product or service with an unchanged percentage fee. The discount model keeps variable cost unchanged; the price-increase model allows revised cost. Fixed overhead is assumed unchanged. Contribution funds overhead and owner pay; it is not net profit. Taxes and new monthly commitments are outside this comparison.</p><p>Sales lift and customer response are your assumptions. Capacity warnings do not cap the projection or prove demand. Required sales round upward; expected sales round downward. Money displays to two decimals while calculations retain precision. Use a separate scenario for a different product or customer group.</p></section>
 <section id="faqs"><h2>Frequently asked questions</h2>{tool.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
 <section className="tool-related"><h2>Continue your pricing plan</h2><p><a href={tool.guide}>{tool.guideLabel}</a> explains the decision with additional business scenarios.</p><p>{tool.mode==='discount'?'Considering a higher price instead of a promotion?':'Considering a promotion instead of a price rise?'} <a href={`/calculators/${sibling[0]}/`}>Use the {sibling[1].name.toLowerCase()}</a> to compare that alternative.</p><p>Explore the <a href="/blogs/">small-business planning guides</a> or return to <a href="/tools/">all free pricing tools</a>.</p></section>
 <section className="tool-cta" aria-labelledby="tool-next-step"><h2 id="tool-next-step">Turn your pricing scenario into a monthly business plan</h2><p>Check whether your contribution can fund overhead, owner pay and your profit target, then compare the required sales with your available working capacity.</p><a className="tool-primary-link" href="/#calculator">Build my full break-even plan →</a><a className="tool-secondary-link" href="/pricing/">Explore Pro plan comparisons</a></section>
 <p className="tool-reviewed">Published by <a href="/about-us/">MyBreakeven</a>. Method and examples checked <time dateTime="2026-10-06">October 6, 2026</time>. <a href="/#methodology">Business calculation methodology</a> · <a href="/contact-us/">Report a calculation issue</a>.</p>
 </article>
}
