export const industries={
 cleaning:{name:"Cleaning Business",short:"Cleaning",unit:"jobs",singular:"job",source:"Service model",extraLabel:"Travel + equipment use per job",acquisitionLabel:"Lead generation cost per booked job",values:{price:180,materialCost:18,laborCost:58,otherVariableCost:12,acquisitionCost:10,fixedCosts:3200,ownerPay:4500,targetProfit:1000,paymentFeePct:2.9,workers:3,hoursPerWorker:35,hoursPerJob:3.5,utilizationPct:75,conversionPct:30}},
 landscaping:{name:"Landscaping & Lawn Care",short:"Landscaping",unit:"jobs",singular:"job",source:"Field-service model",extraLabel:"Fuel + equipment use per job",acquisitionLabel:"Lead generation cost per booked job",values:{price:320,materialCost:62,laborCost:96,otherVariableCost:24,acquisitionCost:18,fixedCosts:4800,ownerPay:5000,targetProfit:1500,paymentFeePct:2.9,workers:4,hoursPerWorker:38,hoursPerJob:5,utilizationPct:72,conversionPct:28}},
 photography:{name:"Photography Studio",short:"Photography",unit:"sessions",singular:"session",source:"Session model",extraLabel:"Editing + gallery + travel per session",acquisitionLabel:"Marketing cost per booked session",values:{price:650,materialCost:35,laborCost:140,otherVariableCost:45,acquisitionCost:35,fixedCosts:2900,ownerPay:5000,targetProfit:1200,paymentFeePct:2.9,workers:2,hoursPerWorker:32,hoursPerJob:8,utilizationPct:68,conversionPct:22}},
 agency:{name:"Agency or Freelancer",short:"Agencies",unit:"clients",singular:"client",source:"Retainer model",extraLabel:"Client software + contractor cost",acquisitionLabel:"Sales cost per new client",values:{price:2200,materialCost:110,laborCost:850,otherVariableCost:140,acquisitionCost:120,fixedCosts:6200,ownerPay:6500,targetProfit:2500,paymentFeePct:2.9,workers:5,hoursPerWorker:35,hoursPerJob:30,utilizationPct:70,conversionPct:20}},
 detailing:{name:"Mobile Auto Detailing",short:"Mobile Detailing",unit:"jobs",singular:"job",source:"Mobile-service model",extraLabel:"Travel + water + equipment per job",acquisitionLabel:"Lead generation cost per booked job",values:{price:240,materialCost:32,laborCost:70,otherVariableCost:16,acquisitionCost:14,fixedCosts:2800,ownerPay:4500,targetProfit:1200,paymentFeePct:2.9,workers:3,hoursPerWorker:36,hoursPerJob:4,utilizationPct:73,conversionPct:32}},
 ecommerce:{name:"E-commerce Store",short:"E-commerce",unit:"orders",singular:"order",source:"Order model",extraLabel:"Shipping subsidy + returns allowance",acquisitionLabel:"Paid acquisition cost per order",values:{price:86,materialCost:29,laborCost:7,otherVariableCost:9,acquisitionCost:13,fixedCosts:7800,ownerPay:5000,targetProfit:2000,paymentFeePct:3.2,workers:3,hoursPerWorker:35,hoursPerJob:.28,utilizationPct:78,conversionPct:2.8}},
 restaurant:{name:"Restaurant Business",short:"Restaurant",unit:"orders",singular:"order",source:"Food-service model",extraLabel:"Packaging + delivery commission per order",acquisitionLabel:"Promotion cost per order",values:{price:34,materialCost:10.5,laborCost:8.5,otherVariableCost:2.2,acquisitionCost:1.2,fixedCosts:24500,ownerPay:6000,targetProfit:3000,paymentFeePct:3.5,workers:10,hoursPerWorker:32,hoursPerJob:.35,utilizationPct:72,conversionPct:45}},
 salon:{name:"Salon Business",short:"Salon",unit:"appointments",singular:"appointment",source:"Appointment model",extraLabel:"Laundry + disposables per appointment",acquisitionLabel:"Marketing cost per booked appointment",values:{price:92,materialCost:13,laborCost:29,otherVariableCost:4,acquisitionCost:6,fixedCosts:8500,ownerPay:5500,targetProfit:1800,paymentFeePct:3,workers:5,hoursPerWorker:34,hoursPerJob:1.4,utilizationPct:76,conversionPct:38}}
};
export const fieldLabels=i=>[
 [`Average price per ${i.singular}`,'price','$',{min:.01,step:.01}],[`Materials / product cost per ${i.singular}`,'materialCost','$',{step:.01}],[`Direct labor per ${i.singular}`,'laborCost','$',{step:.01}],[i.extraLabel,'otherVariableCost','$',{step:.01}],[i.acquisitionLabel,'acquisitionCost','$',{step:.01}],
 ['Monthly operating overhead','fixedCosts','$',{step:.01}],['Monthly owner pay','ownerPay','$',{step:.01}],['Target monthly profit','targetProfit','$',{step:.01}],['Payment and platform fees','paymentFeePct','%',{max:100,step:.01}],
 ['Active team members','workers','',{min:1,step:1}],['Hours per team member / week','hoursPerWorker','hrs',{step:.01}],[`Delivery hours per ${i.singular}`,'hoursPerJob','hrs',{min:.01,step:.01}],['Productive utilization','utilizationPct','%',{max:100,step:.01}],[`Inquiry-to-${i.singular} conversion`,'conversionPct','%',{min:.01,max:100,step:.01}]
];
