import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,BarChart3,BriefcaseBusiness,CheckCircle2,ChevronDown,Info,Menu,ShieldCheck,Sparkles,Target,X}from'lucide-react';
import{calculate}from'./engine';import'./styles.css';

const initial={price:180,materialCost:18,laborCost:58,fixedCosts:3200,ownerPay:4500,targetProfit:1000,paymentFeePct:2.9,workers:3,hoursPerWorker:35,hoursPerJob:3.5,utilizationPct:75,conversionPct:30};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const fields=[['Average price per job','price','$'],['Materials per job','materialCost','$'],['Labor per job','laborCost','$'],['Monthly overhead','fixedCosts','$'],['Monthly owner pay','ownerPay','$'],['Target monthly profit','targetProfit','$'],['Payment fees','paymentFeePct','%'],['Team members','workers',''],['Hours per worker / week','hoursPerWorker','hrs'],['Hours per job','hoursPerJob','hrs'],['Productive utilization','utilizationPct','%'],['Lead-to-customer conversion','conversionPct','%']];
function App(){const[input,setInput]=useState(initial),[mobile,setMobile]=useState(false);const result=useMemo(()=>calculate(input),[input]);const set=(k,v)=>setInput(s=>({...s,[k]:Math.max(0,Number(v))}));return <>
<header><a className="brand" href="#top"><span className="brandmark">M</span><span>My<span>Breakeven</span></span></a><nav className={mobile?'open':''}><a href="#calculator">Calculator</a><a href="#how">How it works</a><a href="#industries">Industries</a><a href="#methodology">Methodology</a><a href="#pricing">Pricing</a><button className="navCta">Start free <ArrowRight/></button></nav><button className="menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
<main id="top"><section className="intro"><div><div className="eyebrow"><Sparkles/> Built for service businesses</div><h1>Know your number.<br/><em>Prove you can reach it.</em></h1><p>Calculate the revenue, jobs, capacity, and leads your business needs to break even—in one transparent plan.</p><div className="trust"><span><CheckCircle2/> No signup</span><span><CheckCircle2/> Private by default</span><span><CheckCircle2/> Formula-backed</span></div></div><div className="mini-card"><div className="mini-head"><span>Monthly feasibility</span><span className="good">FEASIBLE</span></div><div className="dial"><div><strong>{result.valid?result.score:0}</strong><small>/100</small></div></div><div className="mini-grid"><span>Jobs needed<strong>{result.valid?result.jobs:'—'}</strong></span><span>Capacity<strong>{result.valid?result.capacity:'—'}</strong></span><span>Leads needed<strong>{result.valid?result.leads:'—'}</strong></span></div><p><Info/> Example updates as you edit the calculator.</p></div></section>
<section className="calculator" id="calculator"><div className="section-title"><span>FREE FEASIBILITY CALCULATOR</span><h2>Can your cleaning business break even?</h2><p>Enter monthly assumptions. Your figures stay in this browser and update instantly.</p></div><div className="workspace"><div className="inputs"><div className="panel-head"><div><span className="step">01</span><h3>Your operating model</h3></div><button onClick={()=>setInput(initial)}>Reset example</button></div><div className="field-grid">{fields.map(([label,key,suffix])=><label key={key}><span>{label}</span><div className="control">{suffix==='$'&&<b>$</b>}<input type="number" min="0" step="0.1" value={input[key]} onChange={e=>set(key,e.target.value)}/>{suffix&&suffix!=='$'&&<i>{suffix}</i>}</div></label>)}</div><div className="privacy"><ShieldCheck/><span><strong>Private calculation</strong>Your financial inputs are not sent or saved.</span></div></div><div className="results"><div className="result-head"><div><span>LIVE RESULTS</span><h3>Your monthly break-even plan</h3></div><div className={result.valid&&result.gap>=0?'badge good':'badge warn'}>{result.valid?(result.gap>=0?'Feasible':'Capacity gap'):'Fix pricing'}</div></div>{!result.valid?<div className="alert">{result.message}</div>:<><div className="hero-result"><span>Break-even revenue</span><strong>{money(result.revenue)}</strong><small>{result.jobs} jobs × {money(input.price)} average price</small></div><div className="metrics"><article><Target/><span>Jobs needed<strong>{result.jobs}<small>/ month</small></strong></span></article><article><BriefcaseBusiness/><span>Delivery capacity<strong>{result.capacity}<small>jobs / month</small></strong></span></article><article><BarChart3/><span>Leads required<strong>{result.leads}<small>/ month</small></strong></span></article></div><div className="capacity"><div><span>Capacity used</span><strong>{Math.round(result.jobs/result.capacity*100)}%</strong></div><div className="bar"><i style={{width:`${Math.min(100,result.jobs/result.capacity*100)}%`}}/></div><p>{result.gap>=0?`You have room for ${result.gap} more jobs each month.`:`You need capacity for ${Math.abs(result.gap)} additional jobs.`}</p></div><details><summary>Show the formula trace <ChevronDown/></summary><p>Contribution per job = Price − materials − labor − payment fees = <strong>{money(result.contribution)}</strong>. Required jobs = (overhead + owner pay + target profit) ÷ contribution, rounded up.</p></details></>}</div></div></section>
<section className="proof" id="how"><span>ONE NUMBER ISN'T ENOUGH</span><h2>A break-even target only works when your business can deliver it.</h2><div><article><b>01</b><h3>Economics</h3><p>See the true contribution left after direct costs and fees.</p></article><article><b>02</b><h3>Capacity</h3><p>Check whether your team has enough productive hours.</p></article><article><b>03</b><h3>Demand</h3><p>Translate jobs into the leads your conversion rate requires.</p></article><article><b>04</b><h3>Resilience</h3><p>Test how cost, price, and utilization changes move the target.</p></article></div></section>
<section className="industries" id="industries"><div><span>BUILT AROUND HOW YOU WORK</span><h2>Five focused business models. No generic spreadsheet.</h2></div><div className="chips"><button className="active">Cleaning</button><button>Landscaping</button><button>Photography</button><button>Agencies</button><button>Mobile detailing</button></div></section>
<section className="method" id="methodology"><div><span>TRANSPARENT BY DESIGN</span><h2>The math comes first.</h2><p>Every result exposes its inputs, units, formula, rounding rule and engine version. AI may explain verified results later; it will never invent or calculate your numbers.</p></div><div className="code"><small>FORMULA TRACE · ENGINE v0.1</small><code>contribution = price - direct_costs - fees</code><code>jobs_needed = ceil(fixed_need / contribution)</code><code>leads_needed = ceil(jobs_needed / conversion)</code></div></section>
<section className="pricing" id="pricing"><span>START WITHOUT AN EMAIL GATE</span><h2>Calculate free. Save when it matters.</h2><div><article><h3>Free</h3><strong>$0</strong><p>Anonymous calculator, live results, formula trace and one business model.</p><button>Use calculator</button></article><article className="pro"><small>PLANNED PRO</small><h3>Pro</h3><strong>$19 <i>/ month</i></strong><p>Saved scenarios, comparisons, cost-drift tracking and downloadable reports.</p><button>Join the early list</button></article></div></section></main>
<footer><a className="brand" href="#top"><span className="brandmark">M</span><span>My<span>Breakeven</span></span></a><p>Planning estimates based on your assumptions—not tax, legal, accounting or lending advice.</p><span>© 2026 MyBreakeven</span></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
