import React from "react";
import "./pro-user-guide.css";

const inputGroups = [
  { title: "Price and per-sale costs", rows: [
    ["Average price per job", "What a customer pays for one job. The label changes with the selected model (order, session, client or appointment)."],
    ["Materials / product cost", "Supplies or goods consumed by one sale. For a $180 cleaning job, enter the supplies cost for one job."],
    ["Direct labor", "Cost of performing one sale; do not enter the whole team's monthly payroll here as well."],
    ["Other variable cost", "Per-sale travel, packaging, equipment use, delivery or similar costs."],
    ["Lead generation cost", "Estimated acquisition cost per booked sale. The label varies by business model."],
    ["Payment and platform fees", "Percentage of the selling price charged on each transaction. Enter 2.9 for 2.9%."],
  ] },
  { title: "Monthly goal", rows: [
    ["Monthly operating overhead", "Rent, software, insurance and other monthly costs that do not rise with each sale."],
    ["Monthly owner pay", "What the owner wants to take home each month, separately from the target profit."],
    ["Target monthly profit", "Profit above overhead and owner pay. Enter 0 if you only want to cover those costs."],
  ] },
  { title: "Delivery and demand", rows: [
    ["Active team members", "Whole number of people who can deliver the work."],
    ["Hours per team member / week", "Working hours for one person, before applying productive utilization."],
    ["Delivery hours per job", "Hours one sale or job consumes. The unit name changes with the model."],
    ["Productive utilization", "Percent of working time available to deliver work, after admin and downtime. Enter 75 for 75%."],
    ["Inquiry-to-job conversion", "Percent of inquiries that become sales. If 20 of 100 inquiries buy, enter 20%."],
  ] },
];

const studioTools = [
  { id: "offer-mix", title: "Offer Mix", action: "Open the Offer Mix tab. Edit each offer's name, price, variable cost, sales mix and delivery hours. Use Add offer for another service; remove an offer with its delete button.", result: "Read weighted contribution, total sales, revenue and the capacity gap in hours. Shares are normalized, so a 70:30 mix stays proportional. A zero or loss-making offer must be corrected before the mix can be calculated.", example: "Use this when a cleaning company sells standard and deep-clean jobs at different prices." },
  { id: "price-guard", title: "Price Guard", action: "Open Price Guard and move Test discount. Compare the current price with the discounted price.", result: "Additional sales and volume lift show how much more you must sell to preserve the current owner-pay and profit goal. The maximum mathematical discount is the point where per-sale contribution reaches zero; it does not promise extra demand.", example: "Before offering 10% off, check whether the team and lead pipeline can support the extra jobs." },
  { id: "ladder", title: "Break-Even Ladder", action: "Open Break-Even Ladder. Move Safety volume buffer between 0% and 30%.", result: "Follow the four levels: expense coverage, owner-paid, target profit and safety buffer. Whole units are rounded up for a practical sales target.", example: "Use the ladder to separate keeping the business open from paying yourself and meeting a profit goal." },
  { id: "acquisition", title: "Acquisition", action: "Enter monthly channel spend, monthly leads, lead conversion and purchases per customer.", result: "Check customers acquired, CAC, contribution per customer and the purchases or leads needed to recover marketing spend. This channel view replaces the base per-sale acquisition estimate with spend-derived CAC rather than charging both.", example: "If 100 leads at 20% conversion yield 20 customers, $1,000 spend means $50 CAC per customer." },
  { id: "hire", title: "Hire Break-Even", action: "Enter monthly pay, payroll burden, other monthly cost, one-time onboarding, productive hours and expected extra sales.", result: "Read the hire's total monthly cost, extra sales and leads required, utilization needed and monthly net benefit. Payback is meaningful only if monthly net benefit is positive.", example: "Use it before hiring a fourth worker, then compare the required jobs with demand you can realistically generate." },
  { id: "timeline", title: "Timeline", action: "Enter startup investment, starting monthly sales and assumed monthly volume growth.", result: "Review the monthly operating floor, the first month that reaches target profit and the month cumulative operating profit recovers the investment. The table shows months 1–12; the model can evaluate up to 60 months.", example: "Run a 0% growth case alongside an optimistic case to see how sensitive payback is." },
  { id: "monitor", title: "Monthly Monitor", action: "Select a month. Enter completed sales, revenue, variable costs including fees, fixed overhead, owner pay and inquiries, then choose Save / update month.", result: "Compare actual profit, revenue and volume with the plan snapshot saved for that month. Up to 24 months are kept in this browser, separately for your account, model and currency. Records do not sync across devices.", example: "At month-end, enter actual figures and check whether a cost increase or lower volume explains the gap." },
];

function Callout({ children }) { return <aside className="guide-callout">{children}</aside>; }
function RouteMap() { return <figure className="guide-visual" aria-label="Path from Pro dashboard to calculator and advanced analysis"><figcaption>Visual 1 · Where Pro users find the tools</figcaption><div className="guide-route"><div><small>01 · Sign in</small><strong>Dashboard</strong><span className="guide-badge">PRO PLAN</span><span className="guide-visual-button">Open advanced analysis</span><span className="guide-visual-link">Step-by-step guide with visuals</span></div><span className="guide-arrow" aria-hidden="true">→</span><div><small>02 · Calculator page</small><strong>Business model + Currency</strong><span>Enter your assumptions</span><span>Read results and planning tools</span></div><span className="guide-arrow" aria-hidden="true">→</span><div><small>03 · Scroll to Pro</small><strong>PRO INTELLIGENCE</strong><span>Advanced dashboard</span><span>PRO DECISION STUDIO tabs</span></div></div><p>This is an illustrated navigation map. The wording matches the buttons and sections on the site.</p></figure>; }
function CalculatorMap() { return <figure className="guide-visual" aria-label="Illustration of the calculator controls and result sections"><figcaption>Visual 2 · Calculator screen map</figcaption><div className="guide-calculator-map"><div><span className="guide-marker">A</span><strong>Business model</strong><small>Cleaning, restaurant, e-commerce and five other models</small></div><div><span className="guide-marker">B</span><strong>Currency</strong><small>Choose USD or another listed currency before entering money</small></div><div className="guide-map-wide"><span className="guide-marker">C</span><strong>Operating model · 14 input fields</strong><small>Price and per-sale cost → monthly goal → capacity and conversion</small></div><div><span className="guide-marker">D</span><strong>Visual feasibility report</strong><small>Contribution, workload and demand</small></div><div><span className="guide-marker">E</span><strong>Planning tools</strong><small>Save, compare, export, decision brief</small></div><div className="guide-map-wide guide-map-pro"><span className="guide-marker">F</span><strong>PRO INTELLIGENCE</strong><small>Forecast, sensitivity, capacity, heatmap and seven decision tabs</small></div></div><p>The Pro section appears below the calculator results and planning tools. Your inputs update the analysis immediately.</p></figure>; }
function ProMap() { return <figure className="guide-visual" aria-label="Illustration of Pro analysis dashboard and its seven decision tool tabs"><figcaption>Visual 3 · What to read inside Pro</figcaption><div className="guide-pro-map"><div className="guide-pro-kpis"><span>Accounting break-even</span><span>Target-profit revenue</span><span>Margin of safety</span><span>Planned monthly profit</span></div><div className="guide-pro-controls"><b>Expected monthly jobs</b><b>Monthly growth rate</b></div><div className="guide-pro-charts"><span>12-month outlook</span><span>Risk sensitivity</span><span>Capacity solver</span><span>Price × volume heatmap</span></div><div className="guide-pro-tabs">{["Offer Mix","Price Guard","Break-Even Ladder","Acquisition","Hire Break-Even","Timeline","Monthly Monitor"].map(label=><span key={label}>{label}</span>)}</div></div><p>These are the actual names of the cards and tabs. Select a tab to open its inputs and results.</p></figure>; }

export default function ProUserGuide() {
  return <article className="pro-guide">
    <header className="pro-guide-hero"><span>MYBREAKEVEN · PRO HELP CENTER</span><h1>MyBreakeven Pro calculator: complete user guide</h1><p>Follow the exact path from your Pro dashboard to advanced break-even decisions. Every visual below maps to a real section of the product.</p><div className="pro-guide-actions"><a href="/dashboard/">Go to Pro dashboard</a><a href="/#calculator-inputs">Open calculator inputs</a></div><p className="pro-guide-updated">Updated September 24, 2026 · Illustrated screen maps are guides, not live screenshots.</p></header>
    <nav className="pro-guide-toc" aria-label="Guide sections"><strong>Jump to:</strong><a href="#where">Where to find Pro</a><a href="#inputs">Fill the calculator</a><a href="#read">Read results</a><a href="#advanced">Advanced dashboard</a><a href="#tools">Seven tools</a><a href="#save">Save and export</a><a href="#questions">Help</a></nav>
    <section id="where"><h2>1. Where is Pro on the website?</h2><p><strong>Path:</strong> <a href="/login/">Sign in</a> → <a href="/dashboard/">Dashboard</a> → look for the <strong>PRO PLAN</strong> badge → choose <strong>Open advanced analysis</strong>. That button opens the homepage calculator at its Pro section. The same dashboard card includes <strong>Step-by-step guide with visuals</strong> so you can return here anytime.</p><RouteMap/><ol><li>Sign in with the same email linked to your subscription. If you are already signed in, choose <strong>Dashboard</strong> at the top right of the site.</li><li>On the dashboard, confirm you can see <strong>PRO PLAN</strong> under your email. The Pro card is visible even if you have no saved scenarios.</li><li>Choose <strong>Open advanced analysis</strong>. The page opens at <strong>PRO INTELLIGENCE</strong>. Scroll up to edit the calculator assumptions; scroll within Pro to reach the <strong>PRO DECISION STUDIO</strong> tabs.</li><li>For help while using the Pro panel, choose <strong>Visual step-by-step guide</strong> in its heading. You can also find this guide from <a href="/pricing/">Pricing</a>.</li></ol><Callout>If you see a locked Pro panel, go back to the dashboard and confirm the PRO PLAN badge. If it says FREE PLAN after a successful checkout, use the checkout email and contact <a href="mailto:support@mybreakeven.com">support@mybreakeven.com</a> with your receipt. You do not need to buy another subscription.</Callout></section>
    <section id="inputs"><h2>2. Fill the calculator, step by step</h2><CalculatorMap/><ol><li>On the <a href="/#calculator-inputs">calculator page</a>, select <strong>Business model</strong>. There are eight models: cleaning, landscaping, photography, agency/freelancer, mobile detailing, e-commerce, restaurant and salon. Field labels and the sales unit change to fit the model.</li><li>Select <strong>Currency</strong> before entering amounts. Changing currency changes the symbol and code, but does not exchange-convert numbers. Enter all money fields in that one currency.</li><li>Under the operating model, replace the example values in all 14 fields. <strong>Reset example</strong> restores that industry's sample values, so save a plan first if you want to keep your entries.</li><li>Keep monthly totals separate from per-sale costs. A $500 monthly software bill belongs in overhead; a $5 fee on each order belongs in a per-sale cost field.</li></ol>{inputGroups.map(group=><div className="guide-input-group" key={group.title}><h3>{group.title}</h3><div className="pro-guide-table"><table><thead><tr><th>Field on calculator</th><th>What to enter</th></tr></thead><tbody>{group.rows.map(([label,explanation])=><tr key={label}><td>{label}</td><td>{explanation}</td></tr>)}</tbody></table></div></div>)}<Callout>Privacy: the calculator computes live in your browser. Inputs are stored with your account only if you choose <strong>Save scenario</strong>. Monthly Monitor has separate browser-only storage.</Callout></section>
    <section id="read"><h2>3. Read the result before opening advanced tools</h2><p>The <strong>Visual feasibility report</strong> sits immediately below the calculator inputs. It shows unit economics, team capacity and the inquiry demand needed for the selected target. After that, the <strong>Planning tools</strong> section gives you scenario comparison, exports and the Pro analysis panel.</p><div className="guide-example"><h3>Worked example · why the target changes</h3><div className="guide-example-flow"><span>$100 selling price</span><b>−</b><span>$50 total per-sale costs and fees</span><b>=</b><strong>$50 contribution per sale</strong></div><p>If monthly overhead is $1,000, owner pay $500 and target profit $500, the required contribution is $2,000. Divide $2,000 by $50 to get <strong>40 sales</strong>, or <strong>$4,000 target revenue</strong>. At 25% inquiry conversion, those 40 sales need about <strong>160 inquiries</strong>.</p></div><p>Compare required sales with the <strong>Capacity</strong> result. If the team can deliver only 30 sales, the plan has a capacity gap even though the arithmetic reaches your profit goal. Review price, hours or team size. <strong>Whole units</strong> are rounded up; exact units can be fractional because they are mathematical thresholds.</p><p>In Planning tools, Pro users see <strong>Conservative</strong>, <strong>Current plan</strong> and <strong>Optimized</strong> scenarios, a variable-cost increase slider, and the <strong>Executive Decision Brief</strong>. The built-in scenarios are assumption changes, not forecasts of customer behavior. Use <strong>Copy brief</strong> or <strong>Download brief</strong> if you want an action summary.</p></section>
    <section id="advanced"><h2>4. Use the Advanced break-even dashboard</h2><p>Open <a href="/#pro-analysis">PRO INTELLIGENCE</a>. Set <strong>Expected monthly jobs</strong> (or your model's sales unit) to your realistic sales plan, then set <strong>Monthly growth rate</strong>. Those two controls drive the planned-profit and 12-month outlook. Change the main calculator fields above to update all Pro cards.</p><ProMap/><div className="guide-detail-grid"><div><h3>Four headline cards</h3><p><strong>Accounting break-even</strong> covers overhead and owner pay. <strong>Target-profit revenue</strong> additionally includes the profit goal. <strong>Margin of safety</strong> shows how far planned revenue sits above accounting break-even; at or below that point its displayed cushion is zero. <strong>Planned monthly profit</strong> uses your expected units and contribution per sale.</p></div><div><h3>Forecast and sensitivity</h3><p><strong>12-month outlook</strong> compounds the growth rate you enter and holds price and costs constant. <strong>Risk sensitivity</strong> changes one input at a time and shows how target revenue moves. <strong>Not viable</strong> means that changed case loses positive contribution.</p></div><div><h3>Capacity solver</h3><p>Check the estimated <strong>Capacity-safe minimum price</strong>, <strong>Additional team members</strong>, planned revenue and safety cushion. These are calculated from the current hours and utilization, not a hiring recommendation.</p></div><div><h3>Price × volume heatmap</h3><p>Read across price changes from −10% to +10% and down sales volumes from 80% to 150% of the current target. Green cells show modeled profit; red cells show modeled loss. Compare several combinations before treating a price cut as safe.</p></div></div></section>
    <section id="tools"><h2>5. Open each Pro Decision Studio tool</h2><p>Below the charts, find <strong>PRO DECISION STUDIO</strong>. Select one of its seven tabs. Each tab has its own inputs; editing the main calculator above also updates the baseline used by these tools.</p>{studioTools.map((tool,index)=><section id={tool.id} className="guide-tool" key={tool.id}><div className="guide-tool-index">{String(index+1).padStart(2,"0")}</div><div><h3>{tool.title}</h3><p><strong>What to do:</strong> {tool.action}</p><p><strong>How to read it:</strong> {tool.result}</p><p className="guide-tool-example"><strong>When to use it:</strong> {tool.example}</p></div></section>)}<Callout>Monthly Monitor is saved only in the current browser. Clearing browser data or switching devices can remove access to those monthly records. Saved scenarios on the dashboard are tied to your signed-in account.</Callout></section>
    <section id="save"><h2>6. Save, compare and export your work</h2><ol><li>On a valid calculator result, find <strong>PLANNING TOOLS</strong> and choose <strong>Save scenario</strong>. Give it a name and confirm. A Pro account can keep up to 100 saved scenarios.</li><li>Return to <a href="/dashboard/">Dashboard</a>. The saved card offers <strong>Open</strong>, <strong>Rename</strong> and <strong>Delete</strong>. Open reloads its inputs into the calculator. The Pro Command Center above the list summarizes your plans and offers search, model, currency and sort filters.</li><li>Tick <strong>Compare</strong> on two or three saved cards. The comparison shows revenue, exact units, capacity and score. <strong>PRO COST DRIFT</strong> compares changes with the first selected plan as its baseline. Use the same currency when comparing money amounts.</li><li>From Planning tools choose <strong>Download CSV</strong> for scenario numbers, advanced metrics, sensitivity and a 12-month forecast. Choose <strong>Print / Save PDF</strong> to open a print-ready report, then select your browser's PDF destination. On the dashboard, <strong>Export all CSV</strong> downloads a list of saved plans.</li></ol><div className="guide-save-visual" aria-label="Illustration of save and export locations"><div><b>PLANNING TOOLS</b><span>Save scenario</span><span>Download CSV</span><span>Print / Save PDF</span></div><div><b>DASHBOARD</b><span>Open · Rename · Delete</span><span>Compare up to 3</span><span>Export all CSV</span></div></div></section>
    <section id="questions"><h2>7. Common problems and answers</h2><details><summary>Where is the Pro calculator? I only see the free calculator.</summary><p>Both plans use the same homepage inputs. After signing in with a Pro account, the advanced section unlocks below Planning tools. Dashboard → Open advanced analysis jumps to it. You can also use <a href="/#pro-analysis">this direct section link</a>.</p></details><details><summary>Why do I see FREE PLAN despite a paid receipt?</summary><p>Confirm the email on the receipt matches your sign-in email. Refresh Dashboard once. If it remains Free, email support with the receipt and account email so the subscription can be checked. Avoid buying a second subscription.</p></details><details><summary>Why do results disappear or say the plan is invalid?</summary><p>Complete all numeric fields. Price, delivery hours and whole-number team size must be positive; conversion must be above zero; percentages cannot exceed 100. Each sale must retain positive contribution after variable costs and fees.</p></details><details><summary>Do currency and industry changes convert or preserve my entries?</summary><p>Currency changes the label without converting values. Changing business model loads that model's example assumptions; save your current scenario first if you need to preserve it.</p></details><details><summary>Why is the forecast different from my real sales?</summary><p>The 12-month line compounds your chosen growth rate; it does not forecast customer demand. Try slower growth and higher costs to see the range of possible outcomes.</p></details><details><summary>Why did Monthly Monitor disappear on another browser?</summary><p>Monthly Monitor uses local browser storage for each account, model and currency. It does not sync. Dashboard saved scenarios are stored with your account and can be opened after sign-in.</p></details><details><summary>How can I change or cancel my Pro subscription?</summary><p>Sign in, open Dashboard and choose <strong>Manage subscription</strong> beside the PRO PLAN badge.</p></details></section>
    <div className="pro-guide-end"><h2>Start with one realistic plan</h2><p>Enter your real price and costs, check that your team can deliver the required sales, save the baseline, then test a price or demand change in Pro.</p><a href="/dashboard/">Open Pro dashboard</a><a href="/#calculator-inputs">Edit calculator inputs</a></div>
  </article>;
}
