import React from "react";
import "./pro-user-guide.css";

const inputGroups = [
  { title: "Price and per-sale costs", rows: [
    ["Average price per job", "What a customer pays for one job. The label changes with the selected model (order, session, client or appointment)."],
    ["Materials / product cost", "Supplies or goods consumed by one sale. For a $180 cleaning job, enter the supplies cost for one job."],
    ["Direct labor", "Cost of performing one sale; do not enter the whole team's monthly payroll here as well."],
    ["Other variable cost", "Per-sale travel, packaging, equipment use, delivery or similar costs."],
    ["Lead generation cost", "Estimated acquisition cost per booked sale. The label varies by business model."],
    ["Payment and platform fees", "Percentage of the selling price charged on each transaction. Enter 2.9 for 2.9%."],
  ] },
  { title: "Monthly goal", rows: [
    ["Monthly operating overhead", "Rent, software, insurance and other monthly costs that do not rise with each sale."],
    ["Monthly owner pay", "What the owner wants to take home each month, separately from the target profit."],
    ["Target monthly profit", "Profit above overhead and owner pay. Enter 0 if you only want to cover those costs."],
  ] },
  { title: "Delivery and demand", rows: [
    ["Active team members", "Whole number of people who can deliver the work."],
    ["Hours per team member / week", "Working hours for one person, before applying productive utilization."],
    ["Delivery hours per job", "Total working hours used by all people for one sale, including the owner. Two people working two hours each use four team-hours. The unit name changes with the model."],
    ["Productive utilization", "Percent of working time available to deliver work, after admin and downtime. Enter 75 for 75%."],
    ["Inquiry-to-job conversion", "Percent of inquiries that become sales. If 20 of 100 inquiries buy, enter 20%."],
  ] },
];

const studioTools = [
  { id: "offer-mix", title: "Offer Mix", action: "Open the Offer Mix tab. Edit each offer's name, price, variable cost, sales mix and delivery hours. Use Add offer for another service; remove an offer with its delete button.", result: "Read weighted contribution, total sales, revenue and the capacity gap in hours. Shares are normalized, so a 70:30 mix stays proportional. A zero or loss-making offer must be corrected before the mix can be calculated.", example: "Use this when a cleaning company sells standard and deep-clean jobs at different prices." },
  { id: "price-guard", title: "Price Guard", action: "Open Price Guard. Enter Expected monthly sales inside Pricing Plan; this same input also updates the dashboard and reports. Replace the starting example with your own sales estimate.", result: "Cover expenses and pay yourself shows the minimum price for per-sale costs, fees, overhead and owner pay. Also earn your target profit adds your selected monthly profit. When expected sales exceed whole team capacity, the plan uses the lower deliverable volume and states it clearly. The current-price comparison uses that same volume. Expand See the calculation in simple steps for a breakdown, or Per-sale cost floor for direct costs only. No monthly sales target is shown for that floor. PDF and CSV include the same planning inputs. Prices round up to cents; these minimums do not predict demand or recommend lowering a profitable price.", example: "With 131 expected cleaning jobs but capacity for 97, pricing is calculated for 97 jobs. Then use the existing Test discount slider to compare discount trade-offs." },
  { id: "ladder", title: "Break-Even Ladder", action: "Open Break-Even Ladder. Move Safety volume buffer between 0% and 30%.", result: "Follow the four levels: expense coverage, owner-paid, target profit and safety buffer. Whole units are rounded up for a practical sales target.", example: "Use the ladder to separate keeping the business open from paying yourself and meeting a profit goal." },
  { id: "acquisition", title: "Acquisition", action: "Enter monthly channel spend, monthly leads, lead conversion and purchases per customer.", result: "Check customers acquired, CAC, contribution per customer and the purchases or leads needed to recover marketing spend. This channel view replaces the base per-sale acquisition estimate with spend-derived CAC rather than charging both.", example: "If 100 leads at 20% conversion yield 20 customers, $1,000 spend means $50 CAC per customer." },
  { id: "hire", title: "Hire Break-Even", action: "Enter monthly pay, payroll burden, other monthly cost, one-time onboarding, productive hours and expected extra sales.", result: "Read the hire's total monthly cost, extra sales and leads required, utilization needed and monthly net benefit. Payback is meaningful only if monthly net benefit is positive.", example: "Use it before hiring a fourth worker, then compare the required jobs with demand you can realistically generate." },
  { id: "timeline", title: "Timeline", action: "Enter startup investment, starting monthly sales and assumed monthly volume growth.", result: "Review the monthly operating floor, the first month that reaches target profit and the month cumulative operating profit recovers the investment. The table shows months 1–12; the model can evaluate up to 60 months.", example: "Run a 0% growth case alongside an optimistic case to see how sensitive payback is." },
  { id: "monitor", title: "Monthly Monitor", action: "Select a month. Enter completed sales, revenue, variable costs including fees, fixed overhead, owner pay and inquiries, then choose Save / update month.", result: "Compare actual profit, revenue and volume with the plan snapshot saved for that month. Up to 24 months are kept in this browser, separately for your account, model and currency. Records do not sync across devices.", example: "At month-end, enter actual figures and check whether a cost increase or lower volume explains the gap." },
];

function Callout({ children }) { return <aside className="guide-callout">{children}</aside>; }
function RouteMap() { return <figure className="guide-visual" aria-label="Path from Pro dashboard to calculator and advanced analysis"><figcaption>Visual 1 · Where Pro users find the tools</figcaption><div className="guide-route"><div><small>01 · Sign in</small><strong>Dashboard</strong><span className="guide-badge">PRO PLAN</span><span className="guide-visual-button">Open advanced analysis</span><span className="guide-visual-link">Step-by-step guide with visuals</span></div><span className="guide-arrow" aria-hidden="true">→</span><div><small>02 · Calculator page</small><strong>Business model + Currency</strong><span>Enter your assumptions</span><span>Read results and planning tools</span></div><span className="guide-arrow" aria-hidden="true">→</span><div><small>03 · Scroll to Pro</small><strong>PRO INTELLIGENCE</strong><span>Advanced dashboard</span><span>PRO DECISION STUDIO tabs</span></div></div><p>This is an illustrated navigation map. The wording matches the buttons and sections on the site.</p></figure>; }
function CalculatorMap() { return <figure className="guide-visual" aria-label="Illustration of the calculator controls and result sections"><figcaption>Visual 2 · Calculator screen map</figcaption><div className="guide-calculator-map"><div><span className="guide-marker">A</span><strong>Business model</strong><small>Cleaning, restaurant, e-commerce and five other models</small></div><div><span className="guide-marker">B</span><strong>Currency</strong><small>Choose USD or another listed currency before entering money</small></div><div className="guide-map-wide"><span className="guide-marker">C</span><strong>Operating model · 14 input fields</strong><small>Price and per-sale cost → monthly goal → capacity and conversion</small></div><div className="guide-map-wide"><strong>Optional · Build my costs</strong><small>Below Inquiry-to-job conversion · preview a breakdown, then Use these costs</small></div><div><span className="guide-marker">D</span><strong>Visual feasibility report</strong><small>Contribution, workload and demand</small></div><div><span className="guide-marker">E</span><strong>Planning tools</strong><small>Save, compare, export, decision brief</small></div><div className="guide-map-wide guide-map-pro"><span className="guide-marker">F</span><strong>PRO INTELLIGENCE</strong><small>Forecast, sensitivity, capacity, heatmap and seven decision tabs</small></div></div><p>The Pro section appears below the calculator results and planning tools. Your inputs update the analysis immediately.</p></figure>; }
function ProMap() { return <figure className="guide-visual" aria-label="Illustration of Pro analysis dashboard and its seven decision tool tabs"><figcaption>Visual 3 · What to read inside Pro</figcaption><div className="guide-pro-map"><div className="guide-pro-kpis"><span>Costs + owner-pay revenue</span><span>Target-profit revenue</span><span>Margin of safety</span><span>Profit after owner pay</span></div><div className="guide-pro-controls"><b>Expected monthly jobs</b><b>Monthly growth rate</b></div><div className="guide-pro-charts"><span>12-month outlook</span><span>Risk sensitivity</span><span>Capacity solver</span><span>Price × volume heatmap</span></div><div className="guide-pro-tabs">{["Offer Mix","Price Guard","Break-Even Ladder","Acquisition","Hire Break-Even","Timeline","Monthly Monitor"].map(label=><span key={label}>{label}</span>)}</div></div><p>These are the actual names of the cards and tabs. Select a tab to open its inputs and results.</p></figure>; }

export default function ProUserGuide() {
  return <article className="pro-guide">
    <header className="pro-guide-hero"><span>MYBREAKEVEN · PRO HELP CENTER</span><h1>MyBreakeven Pro calculator: complete user guide</h1><p>Follow the exact path from your Pro dashboard to advanced break-even decisions. Every visual below maps to a real section of the product.</p><div className="pro-guide-actions"><a href="/dashboard/">Go to Pro dashboard</a><a href="/#calculator-inputs">Open calculator inputs</a></div><p className="pro-guide-updated">Updated October 8, 2026 · Illustrated screen maps are guides, not live screenshots.</p></header>
    <nav className="pro-guide-toc" aria-label="Guide sections"><strong>Jump to:</strong><a href="#where">Where to find Pro</a><a href="#inputs">Fill the calculator</a><a href="#cost-builder-guide">Build my costs</a><a href="#read">Read results</a><a href="#advanced">Advanced dashboard</a><a href="#pricing-plan-guide">Pricing suggestions</a><a href="#tools">Seven tools</a><a href="#save">Save and export</a><a href="#questions">Help</a></nav>
    <section id="where"><h2>1. Where is Pro on the website?</h2><p><strong>Path:</strong> <a href="/login/">Sign in</a> → <a href="/dashboard/">Dashboard</a> → look for the <strong>PRO PLAN</strong> badge → choose <strong>Open advanced analysis</strong>. That button opens the homepage calculator at its Pro section. The same dashboard card includes <strong>Step-by-step guide with visuals</strong> so you can return here anytime.</p><RouteMap/><ol><li>Sign in with the same email linked to your subscription. If you are already signed in, choose <strong>Dashboard</strong> at the top right of the site.</li><li>On the dashboard, confirm you can see <strong>PRO PLAN</strong> under your email. The Pro card is visible even if you have no saved scenarios.</li><li>Choose <strong>Open advanced analysis</strong>. The page opens at <strong>PRO INTELLIGENCE</strong>. Scroll up to edit the calculator assumptions; scroll within Pro to reach the <strong>PRO DECISION STUDIO</strong> tabs.</li><li>For help while using the Pro panel, choose <strong>Visual step-by-step guide</strong> in its heading. You can also find this guide from <a href="/pricing/">Pricing</a>.</li></ol><Callout>If you see a locked Pro panel, go back to the dashboard and confirm the PRO PLAN badge. If it says FREE PLAN after a successful checkout, use the checkout email and contact <a href="mailto:support@mybreakeven.com">support@mybreakeven.com</a> with your receipt. You do not need to buy another subscription.</Callout></section>
    <section id="inputs"><h2>2. Fill the calculator, step by step</h2><CalculatorMap/><ol><li>On the <a href="/#calculator-inputs">calculator page</a>, select <strong>Business model</strong>. There are eight models: cleaning, landscaping, photography, agency/freelancer, mobile detailing, e-commerce, restaurant and salon. Field labels and the sales unit change to fit the model.</li><li>Select <strong>Currency</strong> before entering amounts. Changing currency changes the symbol and code, but does not exchange-convert numbers. Enter all money fields in that one currency.</li><li>Under the operating model, replace the example values in all 14 fields. <strong>Reset example</strong> restores that industry's sample values, so save a plan first if you want to keep your entries.</li><li>Optional: open <strong>Build my costs</strong> below the inputs. Choose a service, split materials and other expenses into their named rows, and enter direct pay as a total or hours × hourly pay. Count total team-hours, including your own time. Review the direct-cost total and Current/New comparison (or start with zero costs), then choose <strong>Use these costs</strong>. This replaces the material, labor, other-cost and delivery-hours fields; acquisition, percentage fees and monthly totals stay separate. Save scenario keeps an applied breakdown, and Pro PDF/CSV reports include it.</li><li>Keep monthly totals separate from per-sale costs. A $500 monthly software bill belongs in overhead; a $5 fee on each order belongs in a per-sale cost field.</li></ol>{inputGroups.map(group=><div className="guide-input-group" key={group.title}><h3>{group.title}</h3><div className="pro-guide-table"><table><thead><tr><th>Field on calculator</th><th>What to enter</th></tr></thead><tbody>{group.rows.map(([label,explanation])=><tr key={label}><td>{label}</td><td>{explanation}</td></tr>)}</tbody></table></div></div>)}<Callout>Privacy: the calculator computes live in your browser. Inputs are stored with your account only if you choose <strong>Save scenario</strong>. Monthly Monitor has separate browser-only storage.</Callout></section>
    <section id="cost-builder-guide"><h2>2a. Build the cost of one sale</h2><p><strong>Where:</strong> on the calculator, below <strong>Inquiry-to-job conversion</strong>, choose <strong>Build my costs</strong>. This optional tool is available without Pro or sign-in. It helps you add up expenses instead of guessing one total.</p>
      <ol><li>Under <strong>What are you costing?</strong>, choose your service or product type. Names change with your industry; changing the type rebuilds the preview from current calculator totals, not market rates.</li><li>Choose <strong>Start with zero costs</strong> to enter your own breakdown. Otherwise, the current materials and other-expense totals start in the first row of their group. Split those totals across the rows; do not add the same amount twice.</li><li>Open <strong>1. Materials / products</strong> and enter what one sale uses. Use 0 for items you do not pay for.</li><li>Open <strong>2. Labor and delivery time</strong>. Enter the total labor cost, or choose <strong>Calculate hours × hourly pay</strong>. Add each person's working hours, including preparation and travel. Two people working two hours each use four team-hours. If your pay is already in monthly owner pay, count your hours but enter 0 hourly pay. Treat payroll already in overhead the same way.</li><li>Open <strong>3. Other expenses</strong>. Add travel, equipment use or the expenses named for your industry. Keep monthly bills in overhead.</li><li>Read the total and <strong>What will change when you apply?</strong> table. <strong>Current</strong> means the calculator values now; <strong>New</strong> means your preview. Editing the preview does not change results.</li><li>Choose <strong>Use these costs</strong>. The new materials, labor, other expenses and team-hours replace those four calculator inputs. Results recalculate. <strong>Restore current calculator totals</strong> discards preview edits and reloads the values currently in the calculator; it does not undo a previous apply.</li></ol>
      <figure className="guide-visual" aria-label="Illustrative cost builder example"><figcaption>Worked Cost Builder example · fictional USD amounts</figcaption><div className="guide-example-flow"><span>$15 supplies + $5 disposables</span><b>+</b><span>3 hours × $20 = $60 labor</span><b>+</b><span>$12 travel + $8 equipment</span><b>=</b><strong>$100 direct cost per job</strong></div><p>The calculator receives materials $20, direct labor $60, other expenses $20 and delivery time 3 team-hours. Customer acquisition and percentage fees are added separately. Monthly overhead, owner pay and target profit remain separate.</p></figure>
      <Callout>The direct-cost total is not your selling price or full monthly break-even cost. Save scenario retains an applied breakdown; Pro PDF/CSV reports include it. If you manually change a built total later, the old breakdown no longer describes that plan. Zero costs are allowed, but working time must be above zero before applying.</Callout></section>
    <section id="read"><h2>3. Read the result before opening advanced tools</h2><p>The <strong>Visual feasibility report</strong> sits immediately below the calculator inputs. It shows unit economics, team capacity and the inquiry demand needed for the selected target. After that, the <strong>Planning tools</strong> section gives you scenario comparison, exports and the Pro analysis panel.</p><div className="guide-example"><h3>Worked example · why the target changes</h3><div className="guide-example-flow"><span>$100 selling price</span><b>−</b><span>$50 total per-sale costs and fees</span><b>=</b><strong>$50 contribution per sale</strong></div><p>If monthly overhead is $1,000, owner pay $500 and target profit $500, the required contribution is $2,000. Divide $2,000 by $50 to get <strong>40 sales</strong>, or <strong>$4,000 target revenue</strong>. At 25% inquiry conversion, those 40 sales need about <strong>160 inquiries</strong>.</p></div><p>Compare required sales with the <strong>Capacity</strong> result. If the team can deliver only 30 sales, the plan has a capacity gap even though the arithmetic reaches your profit goal. Review price, hours or team size. <strong>Whole units</strong> are rounded up; exact units can be fractional because they are mathematical thresholds.</p><p>In Planning tools, Pro users see <strong>Conservative</strong>, <strong>Current plan</strong> and <strong>Optimized</strong> scenarios, a variable-cost increase slider, and the <strong>Executive Decision Brief</strong>. The built-in scenarios are assumption changes, not forecasts of customer behavior. Use <strong>Copy brief</strong> or <strong>Download brief</strong> if you want an action summary.</p></section>
    <section id="advanced"><h2>4. Use the Advanced break-even dashboard</h2><p>Open <a href="/#pro-analysis">PRO INTELLIGENCE</a>. Set <strong>Expected monthly jobs</strong> (or your model's sales unit) to your realistic sales plan, then set <strong>Monthly growth rate</strong>. Those two controls drive the planned-profit and 12-month outlook. Change the main calculator fields above to update all Pro cards.</p><ProMap/><div className="guide-detail-grid"><div><h3>Four headline cards</h3><p><strong>Costs + owner-pay revenue</strong> covers overhead and owner pay. <strong>Target-profit revenue</strong> additionally includes the profit goal. <strong>Margin of safety</strong> shows how far planned revenue sits above costs + owner-pay revenue; at or below that point its displayed cushion is zero. <strong>Profit after owner pay</strong> uses your expected units and contribution per sale, then subtracts monthly overhead and owner pay. It is before personal taxes.</p></div><div><h3>Forecast and sensitivity</h3><p><strong>12-month outlook</strong> compounds the growth rate you enter and holds price and costs constant. <strong>Risk sensitivity</strong> changes one input at a time and shows how target revenue moves. <strong>Not viable</strong> means that changed case loses positive contribution.</p></div><div><h3>Capacity solver</h3><p>Check the estimated <strong>Capacity-safe minimum price</strong>, <strong>Additional team members</strong>, planned revenue and safety cushion. These are calculated from the current hours and utilization, not a hiring recommendation.</p></div><div><h3>Price × volume heatmap</h3><p>Read across price changes from −10% to +10% and down sales volumes from 80% to 150% of the current target. Green cells show modeled profit; red cells show modeled loss. Compare several combinations before treating a price cut as safe.</p></div></div></section>
    <section id="pricing-plan-guide"><h2>4a. Find a price for your realistic sales volume</h2><p><strong>Where:</strong> sign in with Pro, scroll to <strong>PRO DECISION STUDIO</strong>, select <strong>Price Guard</strong> and read <strong>Pricing Plan</strong> above the discount controls. These prices answer: “At the number of sales I can deliver, what price covers my costs and income goal?”</p>
      <ol><li>Enter real per-sale costs, payment fees, monthly overhead, owner pay, profit goal and team hours in the main calculator. Cost Builder can help with the per-sale costs.</li><li>Enter <strong>Expected monthly jobs</strong> (or your industry's sales unit) in Pricing Plan. Replace the starting sample with your own estimate of customer demand. This input is shared with the advanced dashboard and saved/exported planning assumptions.</li><li>Read the volume actually used. If expected sales exceed whole team capacity, pricing uses the lower deliverable volume. Capacity is a working-time limit, not a promise of bookings.</li><li>Read the two prices below and compare the current-price profit at the same volume. Expand <strong>See the calculation in simple steps</strong> to follow the costs, fees and monthly amount per sale.</li></ol>
      <figure className="guide-visual" aria-label="Illustrative pricing plan for a cleaning business"><figcaption>Worked Pricing Plan example · fictional USD amounts</figcaption><p>Per-job costs including acquisition: $98. Payment fee: 2.9%. Monthly overhead: $3,200. Owner pay: $4,500. Profit goal: $1,000. Expected demand: 131 jobs. Available capacity: 97 whole jobs. <strong>Both prices use 97 jobs.</strong></p><div className="guide-detail-grid"><div><h3>Cover expenses and pay yourself</h3><strong>$182.68 per job</strong><p>Covers per-sale costs and fees, $3,200 overhead and $4,500 owner pay. It does not include the extra $1,000 profit goal.</p></div><div><h3>Also earn your target profit</h3><strong>$193.30 per job</strong><p>Covers the same costs and owner pay plus the $1,000 monthly profit goal.</p></div></div><p>At the current $180 price and 97 jobs, monthly profit after owner pay is <strong>−$252.34</strong>. At $193.30 and 97 jobs, it is <strong>$1,000.35</strong>. Prices round up to cents so the displayed price covers the entered goal.</p></figure>
      <p><strong>Follow the target-price calculation:</strong> ($3,200 overhead + $4,500 owner pay + $1,000 profit) ÷ 97 jobs = about $89.69 needed per job toward monthly goals. Add $98 per-job costs, then divide by 0.971 to allow for the 2.9% fee. The calculator keeps full precision before rounding the final price up to $193.30.</p>
      <Callout>These are cost-based minimums using your assumptions, not predictions of what customers will pay. A lower computed minimum does not mean you should cut a profitable price. <strong>Per-sale cost floor</strong> is an optional explanation of direct costs and fees only; it does not cover overhead, owner pay or a monthly profit goal.</Callout><p>Change volume or costs to test another case. A blank or zero sales input needs correcting before pricing can be calculated. If available capacity is zero, enter realistic team hours and utilization. PDF/CSV use the same pricing assumptions shown on screen.</p></section>
    <section id="tools"><h2>5. Open each Pro Decision Studio tool</h2><p>Below the charts, find <strong>PRO DECISION STUDIO</strong>. Select one of its seven tabs. Each tab has its own inputs; editing the main calculator above also updates the baseline used by these tools.</p>{studioTools.map((tool,index)=><section id={tool.id} className="guide-tool" key={tool.id}><div className="guide-tool-index">{String(index+1).padStart(2,"0")}</div><div><h3>{tool.title}</h3><p><strong>What to do:</strong> {tool.action}</p><p><strong>How to read it:</strong> {tool.result}</p><p className="guide-tool-example"><strong>When to use it:</strong> {tool.example}</p></div></section>)}<Callout>Monthly Monitor is saved only in the current browser. Clearing browser data or switching devices can remove access to those monthly records. Saved scenarios on the dashboard are tied to your signed-in account.</Callout></section>
    <section id="save"><h2>6. Save, compare and export your work</h2><ol><li>On a valid calculator result, find <strong>PLANNING TOOLS</strong> and choose <strong>Save scenario</strong>. Give it a name and confirm. A Pro account can keep up to 100 saved scenarios.</li><li>Return to <a href="/dashboard/">Dashboard</a>. The saved card offers <strong>Open</strong>, <strong>Rename</strong> and <strong>Delete</strong>. Open reloads its inputs into the calculator. The Pro Command Center above the list summarizes your plans and offers search, model, currency and sort filters.</li><li>Tick <strong>Compare</strong> on two or three saved cards. The comparison shows revenue, exact units, capacity and score. <strong>PRO COST DRIFT</strong> compares changes with the first selected plan as its baseline. Use the same currency when comparing money amounts.</li><li>From Planning tools choose <strong>Download CSV</strong> for scenario numbers, advanced metrics, sensitivity, a 12-month forecast and pricing-plan assumptions. Applied Cost Builder details are included. The PDF report also includes the same pricing inputs and applied cost breakdown. Choose <strong>Print / Save PDF</strong> to open a print-ready report, then select your browser's PDF destination. On the dashboard, <strong>Export all CSV</strong> downloads a list of saved plans.</li></ol><div className="guide-save-visual" aria-label="Illustration of save and export locations"><div><b>PLANNING TOOLS</b><span>Save scenario</span><span>Download CSV</span><span>Print / Save PDF</span></div><div><b>DASHBOARD</b><span>Open · Rename · Delete</span><span>Compare up to 3</span><span>Export all CSV</span></div></div></section>
    <section id="questions"><h2>7. Common problems and answers</h2><details><summary>Where is the Pro calculator? I only see the free calculator.</summary><p>Both plans use the same homepage inputs. After signing in with a Pro account, the advanced section unlocks below Planning tools. Dashboard → Open advanced analysis jumps to it. You can also use <a href="/#pro-analysis">this direct section link</a>.</p></details><details><summary>Do I need Pro to use Build my costs?</summary><p>No. Open it below the calculator inputs without signing in. Pro is needed for Pricing Plan in Price Guard and PDF/CSV exports.</p></details><details><summary>Why did editing Build my costs not change my results?</summary><p>You are editing a preview. Check the Current/New table and choose Use these costs. The four totals replace existing inputs; they are not added on top.</p></details><details><summary>Why does Pricing Plan use fewer sales than I entered?</summary><p>Expected sales can exceed the jobs your team can deliver. Pricing Plan uses the lower whole-unit capacity and explains the volume used. Lower your sales assumption if you expect fewer bookings than that capacity.</p></details><details><summary>Why do I see FREE PLAN despite a paid receipt?</summary><p>Confirm the email on the receipt matches your sign-in email. Refresh Dashboard once. If it remains Free, email support with the receipt and account email so the subscription can be checked. Avoid buying a second subscription.</p></details><details><summary>Why do results disappear or say the plan is invalid?</summary><p>Complete all numeric fields. Price, delivery hours and whole-number team size must be positive; conversion must be above zero; percentages cannot exceed 100. Each sale must retain positive contribution after variable costs and fees.</p></details><details><summary>Do currency and industry changes convert or preserve my entries?</summary><p>Currency changes the label without converting values. Changing business model loads that model's example assumptions; save your current scenario first if you need to preserve it.</p></details><details><summary>Why is the forecast different from my real sales?</summary><p>The 12-month line compounds your chosen growth rate; it does not forecast customer demand. Try slower growth and higher costs to see the range of possible outcomes.</p></details><details><summary>Why did Monthly Monitor disappear on another browser?</summary><p>Monthly Monitor uses local browser storage for each account, model and currency. It does not sync. Dashboard saved scenarios are stored with your account and can be opened after sign-in.</p></details><details><summary>How can I change or cancel my Pro subscription?</summary><p>Sign in, open Dashboard and choose <strong>Manage subscription</strong> beside the PRO PLAN badge.</p></details></section>
    <div className="pro-guide-end"><h2>Start with one realistic plan</h2><p>Enter your real price and costs, check that your team can deliver the required sales, save the baseline, then test a price or demand change in Pro.</p><a href="/dashboard/">Open Pro dashboard</a><a href="/#calculator-inputs">Edit calculator inputs</a></div>
  </article>;
}
