import React from "react";
import "./pro-user-guide.css";

const quickSteps = [
  ["Sign in", "Use the email linked to your Pro subscription. Your dashboard should show PRO PLAN."],
  ["Enter your numbers", "Choose a business model and currency, then replace the sample price, costs, sales assumptions and team hours."],
  ["Read the result", "Check the revenue target, whole sales needed, lead demand and whether your team has enough capacity."],
  ["Open Pro analysis", "From your dashboard choose Open advanced analysis. The calculator's Pro section responds to your current inputs."],
  ["Save and compare", "Save useful plans, open them from the dashboard, and select up to three saved plans to compare."],
];

export default function ProUserGuide() {
  return <article className="pro-guide">
    <header className="pro-guide-hero">
      <span>MYBREAKEVEN HELP CENTER · PRO</span>
      <h1>How to use MyBreakeven Pro: a complete calculator guide</h1>
      <p>Start with your real costs and capacity. Then use the Pro tools to test prices, demand, staffing and the route to your profit goal.</p>
      <div className="pro-guide-actions"><a href="/#calculator">Open calculator</a><a href="/dashboard/">Open dashboard</a></div>
      <p className="pro-guide-updated">Updated September 24, 2026 · Examples are illustrations, not business forecasts.</p>
    </header>
    <nav className="pro-guide-toc" aria-label="On this page"><strong>In this guide</strong><a href="#start">Get started</a><a href="#inputs">Enter inputs</a><a href="#results">Read results</a><a href="#pro-tools">Use Pro tools</a><a href="#saved">Save and export</a><a href="#help">Common questions</a></nav>
    <section id="start"><h2>1. Get started with Pro</h2><ol>{quickSteps.map(([title, detail]) => <li key={title}><strong>{title}.</strong> {detail}</li>)}</ol><p>If the dashboard says FREE PLAN, confirm that you signed in with the same email used at checkout. Refresh once. If it still says Free, contact <a href="mailto:support@mybreakeven.com">support@mybreakeven.com</a> with your checkout email and receipt. Do not buy another subscription to fix an account mismatch.</p></section>
    <section id="inputs"><h2>2. Enter the right numbers</h2><p>Open the <a href="/#calculator">calculator</a>. Choose the business model closest to the way you sell work, then select a currency. Currency changes the label; it does not convert your amounts, so enter every money value in the selected currency.</p><div className="pro-guide-table"><table><thead><tr><th>Input</th><th>What to enter</th></tr></thead><tbody><tr><td>Selling price</td><td>Revenue from one sale or job, before per-sale costs.</td></tr><tr><td>Materials, labor, other variable costs</td><td>Costs incurred for each sale or job. Do not put total monthly costs here.</td></tr><tr><td>Acquisition cost</td><td>Estimated cost to acquire one sale. Include it only once in the base calculator.</td></tr><tr><td>Payment fee</td><td>Percentage of the selling price charged per transaction.</td></tr><tr><td>Fixed costs and owner pay</td><td>Monthly overhead and the amount you plan to pay yourself each month.</td></tr><tr><td>Target profit</td><td>Monthly profit wanted in addition to covering costs and owner pay. Enter zero to find the basic target.</td></tr><tr><td>Workers, hours, delivery time, utilization</td><td>Team size, weekly hours per worker, hours per sale or job, and the percentage of time available for delivery.</td></tr><tr><td>Lead conversion</td><td>Percentage of inquiries that become sales. For 20 sales from 100 inquiries, enter 20%.</td></tr></tbody></table></div><p>Change one assumption at a time. The result updates as you edit. If a sale does not cover its variable costs and payment fee, adjust the price or costs before using the advanced tools.</p></section>
    <section id="results"><h2>3. Read the base result first</h2><p><strong>Contribution per sale</strong> is selling price minus payment fees and per-sale costs. The calculator divides monthly fixed costs, owner pay and target profit by that contribution to find the sales target. It also shows a whole-sale target, required revenue, estimated inquiries and your delivery capacity.</p><p>For example, a $100 sale with $50 in per-sale costs contributes $50. With $1,000 fixed costs, $500 owner pay and a $500 target profit, the target is 40 sales or $4,000 monthly revenue. At a 25% inquiry conversion rate, that target needs about 160 inquiries. These are results from the entered assumptions, not a prediction that customers will arrive.</p><p>If required sales exceed team capacity, test price, costs, staffing or delivery hours. A financially attractive target can still be impossible to deliver.</p></section>
    <section id="pro-tools"><h2>4. Work through the Pro analysis</h2><p>On the <a href="/dashboard/">dashboard</a>, select <strong>Open advanced analysis</strong>. Enter your expected monthly sales or jobs and a monthly growth assumption. The advanced panel uses your live calculator numbers; you do not have to save first.</p><div className="pro-guide-cards"><section><h3>Advanced break-even dashboard</h3><p><strong>Accounting break-even</strong> covers fixed costs and owner pay; <strong>target-profit revenue</strong> also includes your chosen profit goal. <strong>Margin of safety</strong> compares planned revenue with accounting break-even. The 12-month outlook compounds your entered monthly growth rate. Risk sensitivity changes one input at a time; “Not viable” means the revised sale no longer makes a positive contribution. The price × volume heatmap shows possible monthly profit under several combinations. The capacity solver estimates a price or extra workers needed to deliver the target.</p></section><section><h3>Offer Mix</h3><p>Edit each offer's price, variable cost, share of sales and delivery hours. Add or remove offers as needed. The tool normalizes the entered sales shares and reports weighted contribution, required sales, revenue and hours. Every included offer must have valid inputs; a loss-making offer is flagged rather than treated as profitable.</p></section><section><h3>Price Guard and Break-Even Ladder</h3><p>In Price Guard, move the discount slider to see the new contribution and how many extra sales would preserve your original target. The maximum discount shown is a mathematical contribution limit, not a pricing recommendation. In Break-Even Ladder, set a volume buffer and review the steps from overhead coverage to owner pay, target profit and a safer sales target.</p></section><section><h3>Acquisition and Hire Break-Even</h3><p>For Acquisition, enter channel spend, leads, conversion and expected purchases per customer. Review customer acquisition cost (CAC), contribution after CAC and purchases needed to recover spend. This channel model replaces the base per-sale acquisition estimate with the entered spend-derived CAC. For Hire, enter monthly pay, payroll burden, other costs, onboarding investment, productive hours and expected additional sales. Check break-even volume, lead need, capacity use and payback; if monthly benefit is not positive, payback is unavailable.</p></section><section><h3>Timeline and Monthly Monitor</h3><p>Timeline uses startup investment, starting monthly sales and assumed growth to show operating break-even, the first month your profit target is reached and cumulative investment recovery. Monthly Monitor compares actual sales, revenue, variable costs, overhead, owner pay and inquiries with a saved plan snapshot. Monitor records stay in this browser for this account, business model and currency; they do not sync to another device. Up to 24 months can be kept locally.</p></section></div></section>
    <section id="saved"><h2>5. Save, compare and export a plan</h2><ol><li>With valid calculator results, select <strong>Save scenario</strong>, give the plan a clear name and save it while signed in.</li><li>Open <strong>Dashboard</strong> to find your plan. Pro supports up to 100 saved scenarios. Use the search, model and currency filters to find one later.</li><li>Select two or three plans with <strong>Compare</strong> to see their revenue, volume, capacity and feasibility side by side. Cost drift also shows changes from the first selected plan.</li><li>Open an individual saved plan to load its assumptions into the calculator. Recheck its current results if your business costs have changed.</li><li>Use <strong>Download CSV</strong> for numbers and the forecast, or <strong>Print / Save PDF</strong> to save a report through your browser's print dialog. The Executive Decision Brief can be copied or downloaded separately.</li></ol><p>Saved scenarios are tied to your account. Monthly Monitor entries are stored only in the current browser. Export anything you need to keep before clearing browser data.</p></section>
    <section id="help"><h2>6. Common questions</h2><details><summary>Why is my Pro section locked?</summary><p>Sign in, check for the PRO PLAN badge on your dashboard, then refresh the calculator page. If the badge is missing despite a Pro receipt, contact support with the checkout email.</p></details><details><summary>Why does the calculator say a plan is invalid?</summary><p>Check blank fields, negative values, team size, percentages and selling price. Each sale must have positive contribution after per-sale costs and fees.</p></details><details><summary>Is the 12-month forecast a guarantee?</summary><p>No. It compounds the monthly growth percentage you enter and holds other assumptions constant. Run lower-growth and higher-cost cases before making a decision.</p></details><details><summary>Why is Monthly Monitor empty on another device?</summary><p>Its entries are stored in the browser where you entered them, not in your account database. Use the same browser to see those months.</p></details><details><summary>How do I manage my subscription?</summary><p>Sign in and choose <strong>Manage subscription</strong> beside the PRO PLAN badge on your dashboard.</p></details></section>
    <footer className="pro-guide-end"><h2>Ready to test your own plan?</h2><p>Start with one realistic set of inputs. Save a baseline, then vary a single assumption and compare the outcome.</p><a href="/#calculator">Open the calculator</a></footer>
  </article>;
}
